### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/Desktop' when trying to python3 run_eureka.py 

### ISSUE THREAD

**Issue by jovian-explorer** [kevin218/Eureka#212]
dev@Dev-linux:~/Desktop/JWST-Sim/NIRSpec/Stage2/JWST$ python3 run_eureka.py 

gives the following - 

2022-03-22 23:15:57,894 - stpipe - INFO - Loading KWallet
2022-03-22 23:15:57,897 - stpipe - INFO - Loading SecretService
2022-03-22 23:15:57,901 - stpipe - INFO - Loading Windows
2022-03-22 23:15:57,902 - stpipe - INFO - Loading chainer
2022-03-22 23:15:57,903 - stpipe - INFO - Loading macOS
Traceback (most recent call last):
  File "run_eureka.py", line 17, in <module>
    s1_meta = s1.rampfitJWST(eventlabel, ecf_path=ecf_path)
  File "/home/dev/.local/lib/python3.8/site-packages/eureka/S1_detector_processing/s1_process.py", line 62, in rampfitJWST
    run = util.makedirectory(meta, 'S1')
  File "/home/dev/.local/lib/python3.8/site-packages/eureka/lib/util.py", line 115, in makedirectory
    os.makedirs(meta.outputdir)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Desktop'

Idk what I am doing wrong... please help

**Comment by taylorbell57** [comment]
Can you please upload your ecf file (either compress it into a zip file and upload that below or copy-paste it into a comment below)

**Comment by taylorbell57** [comment]
Ahh wait, topdir needs to be an absolute path, so you need to put `/home/YourUsernameHere/Desktop/` for Linux or `/Users/YourUsernameHere/Desktop/` for Mac instead of just `/Desktop` or `~/Desktop`

**Comment by jovian-explorer** [comment]
That worked. Thank you.
