### ISSUE TITLE
AttributeError: 'MetaClass' object has no attribute 'slit_y_low'

### ISSUE THREAD

**Issue by jovian-explorer** [kevin218/Eureka#217]
dev@Dev-linux:~/Desktop/JWST-Sim/NIRSpec/Stage2/JWST$ python3 run_eureka.py
2022-03-23 10:24:14,815 - stpipe - INFO - Loading KWallet
2022-03-23 10:24:14,819 - stpipe - INFO - Loading SecretService
2022-03-23 10:24:14,823 - stpipe - INFO - Loading Windows
2022-03-23 10:24:14,824 - stpipe - INFO - Loading chainer
2022-03-23 10:24:14,824 - stpipe - INFO - Loading macOS

Starting Stage 1 Processing
Copying S1 control file

Found 0 data file(s) ending in uncal.fits

Total time (min): 0.0
Saving Metadata

Starting Stage 2 Reduction
Copying S2 control file

Found 1 data file(s) ending in rateints.fits
2022-03-23 10:24:15,017 - stpipe.EurekaSpec2Pipeline - INFO - EurekaSpec2Pipeline instance created.
2022-03-23 10:24:15,018 - stpipe.EurekaSpec2Pipeline.bkg_subtract - INFO - BackgroundStep instance created.
2022-03-23 10:24:15,019 - stpipe.EurekaSpec2Pipeline.assign_wcs - INFO - AssignWcsStep instance created.
2022-03-23 10:24:15,019 - stpipe.EurekaSpec2Pipeline.imprint_subtract - INFO - ImprintStep instance created.
2022-03-23 10:24:15,020 - stpipe.EurekaSpec2Pipeline.msa_flagging - INFO - MSAFlagOpenStep instance created.
2022-03-23 10:24:15,020 - stpipe.EurekaSpec2Pipeline.extract_2d - INFO - Extract2dStep instance created.
2022-03-23 10:24:15,022 - stpipe.EurekaSpec2Pipeline.master_background - INFO - MasterBackgroundNrsSlitsStep instance created.
2022-03-23 10:24:15,023 - stpipe.EurekaSpec2Pipeline.master_background.flat_field - INFO - FlatFieldStep instance created.
2022-03-23 10:24:15,023 - stpipe.EurekaSpec2Pipeline.master_background.pathloss - INFO - PathLossStep instance created.
2022-03-23 10:24:15,024 - stpipe.EurekaSpec2Pipeline.master_background.barshadow - INFO - BarShadowStep instance created.
2022-03-23 10:24:15,025 - stpipe.EurekaSpec2Pipeline.master_background.photom - INFO - PhotomStep instance created.
2022-03-23 10:24:15,025 - stpipe.EurekaSpec2Pipeline.wavecorr - INFO - WavecorrStep instance created.
2022-03-23 10:24:15,026 - stpipe.EurekaSpec2Pipeline.flat_field - INFO - FlatFieldStep instance created.
2022-03-23 10:24:15,026 - stpipe.EurekaSpec2Pipeline.srctype - INFO - SourceTypeStep instance created.
2022-03-23 10:24:15,027 - stpipe.EurekaSpec2Pipeline.straylight - INFO - StraylightStep instance created.
2022-03-23 10:24:15,028 - stpipe.EurekaSpec2Pipeline.fringe - INFO - FringeStep instance created.
2022-03-23 10:24:15,028 - stpipe.EurekaSpec2Pipeline.pathloss - INFO - PathLossStep instance created.
2022-03-23 10:24:15,029 - stpipe.EurekaSpec2Pipeline.barshadow - INFO - BarShadowStep instance created.
2022-03-23 10:24:15,029 - stpipe.EurekaSpec2Pipeline.photom - INFO - PhotomStep instance created.
2022-03-23 10:24:15,030 - stpipe.EurekaSpec2Pipeline.resample_spec - INFO - ResampleSpecStep instance created.
2022-03-23 10:24:15,032 - stpipe.EurekaSpec2Pipeline.cube_build - INFO - CubeBuildStep instance created.
2022-03-23 10:24:15,033 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Extract1dStep instance created.
Starting file 1 of 1
Traceback (most recent call last):
  File "run_eureka.py", line 19, in <module>
    s2_meta = s2.calibrateJWST(eventlabel, ecf_path=ecf_path)
  File "/home/dev/.local/lib/python3.8/site-packages/eureka/S2_calibrations/s2_calibrate.py", line 134, in calibrateJWST
    pipeline.run_eurekaS2(filename, meta, log)
  File "/home/dev/.local/lib/python3.8/site-packages/eureka/S2_calibrations/s2_calibrate.py", line 190, in run_eurekaS2
    if meta.slit_y_low != None:
AttributeError: 'MetaClass' object has no attribute 'slit_y_low'

**Comment by taylorbell57** [comment]
That parameter should have been set in your Stage 2 ecf file - please check the current templates on GitHub and/or readthedocs to make sure you have all the parameters in your ecf that you need. If there's something wrong with those templates though, let me know here and I'll look into it in my morning. For NIRSpec, be sure to use that values from that template as they differ from the other instruments

**Comment by jovian-explorer** [comment]
Worked. Thanks.
