### ISSUE TITLE
CRDS - ERROR -  (FATAL) CRDS server connection and cache load FAILED. 

### ISSUE THREAD

**Issue by jovian-explorer** [kevin218/Eureka#218]
dev@Dev-linux:~/Desktop/JWST-Sim/NIRSpec/Stage2/JWST$ python3 run_eureka.py
2022-03-23 11:18:03,225 - stpipe - INFO - Loading KWallet
2022-03-23 11:18:03,228 - stpipe - INFO - Loading SecretService
2022-03-23 11:18:03,233 - stpipe - INFO - Loading Windows
2022-03-23 11:18:03,234 - stpipe - INFO - Loading chainer
2022-03-23 11:18:03,234 - stpipe - INFO - Loading macOS

Starting Stage 1 Processing
Copying S1 control file

Found 0 data file(s) ending in uncal.fits

Total time (min): 0.0
Saving Metadata

Starting Stage 2 Reduction
Copying S2 control file

Found 1 data file(s) ending in rateints.fits
2022-03-23 11:18:03,432 - stpipe.EurekaSpec2Pipeline - INFO - EurekaSpec2Pipeline instance created.
2022-03-23 11:18:03,433 - stpipe.EurekaSpec2Pipeline.bkg_subtract - INFO - BackgroundStep instance created.
2022-03-23 11:18:03,434 - stpipe.EurekaSpec2Pipeline.assign_wcs - INFO - AssignWcsStep instance created.
2022-03-23 11:18:03,434 - stpipe.EurekaSpec2Pipeline.imprint_subtract - INFO - ImprintStep instance created.
2022-03-23 11:18:03,435 - stpipe.EurekaSpec2Pipeline.msa_flagging - INFO - MSAFlagOpenStep instance created.
2022-03-23 11:18:03,436 - stpipe.EurekaSpec2Pipeline.extract_2d - INFO - Extract2dStep instance created.
2022-03-23 11:18:03,438 - stpipe.EurekaSpec2Pipeline.master_background - INFO - MasterBackgroundNrsSlitsStep instance created.
2022-03-23 11:18:03,438 - stpipe.EurekaSpec2Pipeline.master_background.flat_field - INFO - FlatFieldStep instance created.
2022-03-23 11:18:03,439 - stpipe.EurekaSpec2Pipeline.master_background.pathloss - INFO - PathLossStep instance created.
2022-03-23 11:18:03,440 - stpipe.EurekaSpec2Pipeline.master_background.barshadow - INFO - BarShadowStep instance created.
2022-03-23 11:18:03,440 - stpipe.EurekaSpec2Pipeline.master_background.photom - INFO - PhotomStep instance created.
2022-03-23 11:18:03,441 - stpipe.EurekaSpec2Pipeline.wavecorr - INFO - WavecorrStep instance created.
2022-03-23 11:18:03,442 - stpipe.EurekaSpec2Pipeline.flat_field - INFO - FlatFieldStep instance created.
2022-03-23 11:18:03,442 - stpipe.EurekaSpec2Pipeline.srctype - INFO - SourceTypeStep instance created.
2022-03-23 11:18:03,443 - stpipe.EurekaSpec2Pipeline.straylight - INFO - StraylightStep instance created.
2022-03-23 11:18:03,444 - stpipe.EurekaSpec2Pipeline.fringe - INFO - FringeStep instance created.
2022-03-23 11:18:03,444 - stpipe.EurekaSpec2Pipeline.pathloss - INFO - PathLossStep instance created.
2022-03-23 11:18:03,445 - stpipe.EurekaSpec2Pipeline.barshadow - INFO - BarShadowStep instance created.
2022-03-23 11:18:03,446 - stpipe.EurekaSpec2Pipeline.photom - INFO - PhotomStep instance created.
2022-03-23 11:18:03,446 - stpipe.EurekaSpec2Pipeline.resample_spec - INFO - ResampleSpecStep instance created.
2022-03-23 11:18:03,448 - stpipe.EurekaSpec2Pipeline.cube_build - INFO - CubeBuildStep instance created.
2022-03-23 11:18:03,448 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Extract1dStep instance created.
Starting file 1 of 1
Running the Spec2Pipeline

2022-03-23 11:18:03,532 - stpipe.EurekaSpec2Pipeline - INFO - Step EurekaSpec2Pipeline running with args ('/home/dev/Desktop/JWST-Sim/NIRSpec/Stage2/JWST/rateints.fits',).
2022-03-23 11:18:03,543 - stpipe.EurekaSpec2Pipeline - INFO - Step EurekaSpec2Pipeline parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': '/home/dev/Desktop/JWST-Sim/NIRSpec/Stage3/JWST/S2_2022-03-23_wasp39b_run10/', 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': True, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'save_bsub': False, 'fail_on_exception': True, 'steps': {'bkg_subtract': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'save_combined_background': False, 'sigma': 3.0, 'maxiters': None}, 'assign_wcs': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'sip_approx': True, 'sip_max_pix_error': 0.25, 'sip_degree': None, 'sip_max_inv_pix_error': 0.25, 'sip_inv_degree': None, 'sip_npoints': 32, 'slit_y_low': -0.55, 'slit_y_high': 0.55}, 'imprint_subtract': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'msa_flagging': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'extract_2d': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'slit_name': None, 'extract_orders': None, 'tsgrism_extract_height': None, 'wfss_extract_half_height': 5, 'grism_objects': None, 'mmag_extract': 99.0}, 'master_background': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': True, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'force_subtract': False, 'save_background': False, 'user_background': None, 'inverse': False, 'steps': {'flat_field': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'save_interpolated_flat': False, 'user_supplied_flat': None, 'inverse': False}, 'pathloss': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'inverse': False, 'source_type': None}, 'barshadow': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'inverse': False, 'source_type': None}, 'photom': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'inverse': False, 'source_type': None}}}, 'wavecorr': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'flat_field': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'save_interpolated_flat': False, 'user_supplied_flat': None, 'inverse': False}, 'srctype': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'straylight': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'method': 'ModShepard', 'roi': 50, 'power': 1.0}, 'fringe': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'pathloss': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'inverse': False, 'source_type': None}, 'barshadow': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'inverse': False, 'source_type': None}, 'photom': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'inverse': False, 'source_type': None}, 'resample_spec': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'pixfrac': 1.0, 'kernel': 'square', 'fillval': 'INDEF', 'weight_type': 'ivm', 'pixel_scale_ratio': 1.0, 'single': False, 'blendheaders': True, 'allowed_memory': None}, 'cube_build': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': True, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': False, 'input_dir': '', 'channel': 'all', 'band': 'all', 'grating': 'all', 'filter': 'all', 'output_type': 'band', 'scale1': 0.0, 'scale2': 0.0, 'scalew': 0.0, 'weighting': 'emsm', 'coord_system': 'skyalign', 'rois': 0.0, 'roiw': 0.0, 'weight_power': 2.0, 'wavemin': None, 'wavemax': None, 'single': False, 'xdebug': None, 'ydebug': None, 'zdebug': None, 'skip_dqflagging': False}, 'extract_1d': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'smoothing_length': None, 'bkg_fit': 'poly', 'bkg_order': None, 'bkg_sigma_clip': 3.0, 'log_increment': 50, 'subtract_background': None, 'use_source_posn': None, 'apply_apcorr': True}}}
2022-03-23 11:18:04,185 - stpipe.EurekaSpec2Pipeline - INFO - Prefetching reference files for dataset: 'rateints.fits' reftypes = ['apcorr', 'area', 'camera', 'collimator', 'dflat', 'disperser', 'distortion', 'extract1d', 'fflat', 'filteroffset', 'flat', 'fore', 'fpa', 'ifufore', 'ifupost', 'ifuslicer', 'msa', 'ote', 'photom', 'regions', 'sflat', 'specwcs', 'wavelengthrange', 'wfssbkg']
2022-03-23 11:18:04,186 - CRDS - ERROR -  (FATAL) CRDS server connection and cache load FAILED.  Cannot continue.
 See https://hst-crds.stsci.edu/docs/cmdline_bestrefs/ or https://jwst-crds.stsci.edu/docs/cmdline_bestrefs/
 for more information on configuring CRDS,  particularly CRDS_PATH and CRDS_SERVER_URL. : [Errno 2] No such file or directory: '/grp/crds/cache/config/jwst/server_config'

**Comment by taylorbell57** [comment]
Please read the documentation at https://eurekadocs.readthedocs.io/en/latest/installation.html#crds-environment-variables for an explanation of how to set the CRDS variables

**Comment by jovian-explorer** [comment]
dev@Dev-linux:~/Desktop/JWST-Sim/NIRSpec/Stage2/JWST$ export CRDS_PATH =/home/dev/Desktop/JWST-Sim/NIRSpec/crds_cache
bash: export: `=/home/dev/Desktop/JWST-Sim/NIRSpec/crds_cache': not a valid identifier
dev@Dev-linux:~/Desktop/JWST-Sim/NIRSpec/Stage2/JWST$ export CRDS_SERVER_URL = https://jwst-crds.stsci.edu
bash: export: `=': not a valid identifier
bash: export: `https://jwst-crds.stsci.edu': not a valid identifier

**Comment by taylorbell57** [comment]
These commands should not be run directly in the terminal as their impact will not be saved for other terminal windows or if you open/close the terminal. Instead you should put these in your ~/.bashrc file (assuming your linux install uses bash) and then run `source ~/.bashrc` so that the edits to that file take effect for your current terminal (as this file is only used automatically when you make a new terminal). Also be careful about spaces in your commands. It should be:

`export CRDS_PATH=/home/dev/Desktop/JWST-Sim/NIRSpec/crds_cache`
`export CRDS_SERVER_URL=https://jwst-crds.stsci.edu`

**Comment by jovian-explorer** [comment]
Never mind I think I solved it

**Comment by jovian-explorer** [comment]
honestly I am new to both linux, as well as this whole idea of working with repositories. I will keep asking you for help wherever I get stuck

**Comment by jovian-explorer** [comment]
![fig1101__x1dints](https://user-images.githubusercontent.com/98839532/159761672-a30c817d-f2b3-4bde-890f-583fc0b58f8b.png)


is this what I am supposed to get? or am I still doing everything wrong?

**Comment by taylorbell57** [comment]
Yeesh, that's the output plot from Stage 2? Can you copy-paste your Stage 2 ecf into a comment on here so I can see if there is anything obviously wrong with it before I check with others to see what their plot looks like?

**Comment by jovian-explorer** [comment]
oh okay

**Comment by jovian-explorer** [comment]
# Eureka! Control File for Stage 2: Data Reduction

suffix      rateints     # Data file suffix
# Eureka! Control File for Stage 2: Data Reduction

suffix      rateints     # Data file suffix

# Controls the cross-dispersion extraction
slit_y_low			None	# Use None to rely on the default parameters
slit_y_high			None	# Use None to rely on the default parameters

# Modify the existing file to change the dispersion extraction - FIX: DOES NOT WORK CURRENTLY
waverange_start		None	# Use None to rely on the default parameters
waverange_end		None	# Use None to rely on the default parameters

# Note: different instruments and modes will use different steps by default
skip_bkg_subtract		False	# Not run for TSO observations
skip_imprint_subtract	True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_msa_flagging		True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_extract_2d			False
skip_srctype			True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_master_background	True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_wavecorr			True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_flat_field			False
skip_straylight			True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_fringe				True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_pathloss			True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_barshadow			True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_photom				False
skip_resample			True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_cube_build			True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_extract_1d			False

# Diagnostics
testing_S2 	False
hide_plots	False	# If True, plots will automatically be closed rather than popping up

# Project directory
topdir						/home/dev/Desktop/JWST-Sim/NIRSpec

# Directories relative to project directory
inputdir                                     /Stage2/JWST
outputdir	                            /Stage3/JWST

**Comment by jovian-explorer** [comment]
`# Eureka! Control File for Stage 2: Data Reduction

suffix      rateints     # Data file suffix
# Eureka! Control File for Stage 2: Data Reduction

suffix      rateints     # Data file suffix

# Controls the cross-dispersion extraction
slit_y_low			None	# Use None to rely on the default parameters
slit_y_high			None	# Use None to rely on the default parameters

# Modify the existing file to change the dispersion extraction - FIX: DOES NOT WORK CURRENTLY
waverange_start		None	# Use None to rely on the default parameters
waverange_end		None	# Use None to rely on the default parameters

# Note: different instruments and modes will use different steps by default
skip_bkg_subtract		False	# Not run for TSO observations
skip_imprint_subtract	True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_msa_flagging		True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_extract_2d			False
skip_srctype			True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_master_background	True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_wavecorr			True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_flat_field			False
skip_straylight			True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_fringe				True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_pathloss			True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_barshadow			True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_photom				False
skip_resample			True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_cube_build			True	# Not run for NIRCam Wide-Field Slitless Spectroscopy
skip_extract_1d			False

# Diagnostics
testing_S2 	False
hide_plots	False	# If True, plots will automatically be closed rather than popping up

# Project directory
topdir						/home/dev/Desktop/JWST-Sim/NIRSpec

# Directories relative to project directory
inputdir                                     /Stage2/JWST
outputdir	                            /Stage3/JWST`

**Comment by taylorbell57** [comment]
Ah, so you're using the NIRCam template for NIRSpec data - you shouldn't be doing this. You should look at the NIRSpec template as several of the settings differ between different instruments

**Comment by jovian-explorer** [comment]
shit okay I'll rectify it

**Comment by jovian-explorer** [comment]
sorry

**Comment by jovian-explorer** [comment]
![fig3303-file1-source_pos](https://user-images.githubusercontent.com/98839532/159764179-78b51efb-6167-4b73-b24d-a6310dad9040.png)

**Comment by jovian-explorer** [comment]
![fig1101__x1dints](https://user-images.githubusercontent.com/98839532/159764293-219a9180-2ca4-4fa6-bb2d-92aeffc74764.png)

**Comment by taylorbell57** [comment]
Wonderful, that is much better!!!

**Comment by jovian-explorer** [comment]
finally!!

**Comment by jovian-explorer** [comment]
thank you so much for your help :smile:

**Comment by jovian-explorer** [comment]
keshav@dev:~/Downloads/JWST_Sim/NIRSpec/Stage2$ pip install scipy
Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (1.3.3)
keshav@dev:~/Downloads/JWST_Sim/NIRSpec/Stage2$ python3 run_eureka.py 
Traceback (most recent call last):
  File "run_eureka.py", line 4, in <module>
    import eureka.S1_detector_processing.s1_process as s1
  File "/home/keshav/.local/lib/python3.8/site-packages/eureka/__init__.py", line 13, in <module>
    from . import S3_data_reduction
  File "/home/keshav/.local/lib/python3.8/site-packages/eureka/S3_data_reduction/__init__.py", line 7, in <module>
    from . import niriss
  File "/home/keshav/.local/lib/python3.8/site-packages/eureka/S3_data_reduction/niriss.py", line 19, in <module>
    from skimage import filters, feature
  File "/home/keshav/.local/lib/python3.8/site-packages/skimage/_shared/lazy.py", line 62, in __getattr__
    return importlib.import_module(f'{package_name}.{name}')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/keshav/.local/lib/python3.8/site-packages/skimage/feature/__init__.py", line 4, in <module>
    from ._cascade import Cascade
  File "skimage/feature/_cascade.pyx", line 20, in init skimage.feature._cascade
  File "/home/keshav/.local/lib/python3.8/site-packages/skimage/transform/__init__.py", line 4, in <module>
    from .radon_transform import (radon, iradon, iradon_sart,
  File "/home/keshav/.local/lib/python3.8/site-packages/skimage/transform/radon_transform.py", line 5, in <module>
    from scipy.fft import fft, ifft, fftfreq, fftshift
ModuleNotFoundError: No module named 'scipy.fft'

**Comment by taylorbell57** [comment]
Can you please copy-paste the results from the following command:
`pip show scipy`
