### ISSUE TITLE
numpy.ma.core.MaskedArray fails to make figures if there are any actual masked values

### ISSUE THREAD

**Issue by lcmayor** [kevin218/Eureka#228]
plots_s3 functions don't actually plot when a value is masked.

This includes at least `profile` and `optimal_spectrum`.

Can be tested using MIRI file 22 of 42.

**Comment by taylorbell57** [comment]
I think this may the issue that Kevin and I were just talking about, but want to make sure that it's the same issue

**Comment by lcmayor** [comment]
TypeError: '<=' not supported between instances of 'str' and 'int' Or some sort of variety of the str and int problem.

I was just complaining to him.

**Comment by taylorbell57** [comment]
Ahh okay, yup that was the issue we were just discussing. I will try making a bug patch for that now - I think plt.imshow doesn't know about masked arrays while plt.plot does. Why matplotlib decided to do that I have no idea, but I'll just convert things to NaNs when making the imshow figures

**Comment by lcmayor** [comment]
It's also in the plt.errorbar.

**Comment by taylorbell57** [comment]
Gah, okay thanks for the heads up - then maybe masked arrays aren't the way to go... @kevin218 what do you think - just NaN replace things instead of masking or edit every plotting function?

**Comment by lcmayor** [comment]
profile specifically gives `ValueError: minvalue must be less than or equal to maxvalue` when trying to save the figure which seems related.

**Comment by lcmayor** [comment]
related to https://github.com/kevin218/Eureka/issues/108

**Comment by taylorbell57** [comment]
Aha, good point! Can close two issues with one patch!

**Comment by taylorbell57** [comment]
Sorry, are you using the most up-to-date code on main? Is the commit number when you run `git log -1` commit 57cb0f1a576dfbbef9ba616b7a13a28c42efb876 (the full name is longer than that but GitHub truncates it)? I just need to make sure a fix for some of this hasn't already been implemented. And which simulation is that MIRI file 22 of 42 for (with ramp, no ramp, with companion)?

**Comment by lcmayor** [comment]
I have pulled the latest commit and am rerunning. I'm using no ramp, no companion.

**Comment by taylorbell57** [comment]
Okay, there's no guarantee that any/many of the issues will be resolved with the latest main updates, but I wanted to check that first while I'm eating lunch now

**Comment by lcmayor** [comment]
> profile specifically gives `ValueError: minvalue must be less than or equal to maxvalue` when trying to save the figure which seems related.

Can confirm this is still in the latest commit:
```Traceback (most recent call last):
  File "/Users/mayorlc1/Projects/JWST/MIRI_Sim/step.py", line 12, in <module>
    s3_meta = s3.reduceJWST(eventlabel, ecf_path=ecf_path)
  File "/Users/mayorlc1/Eureka/eureka/S3_data_reduction/s3_reduce.py", line 297, in reduceJWST
    data.optspec[n], data.opterr[n], mask = optspex.optimize(data.apdata[n], data.apmask[n], data.apbg[n],
  File "/Users/mayorlc1/Eureka/eureka/S3_data_reduction/optspex.py", line 491, in optimize
    plots_s3.profile(eventdir, profile, submask, n, hide_plots=hide_plots)
  File "/Users/mayorlc1/Eureka/eureka/S3_data_reduction/plots_s3.py", line 212, in profile
    plt.savefig(eventdir+'figs/fig3305-'+str(n)+'-Profile.png')
  File "/Users/mayorlc1/anaconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/pyplot.py", line 958, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/Users/mayorlc1/anaconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/figure.py", line 3019, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/Users/mayorlc1/anaconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2295, in print_figure
    self.figure.draw(renderer)
  File "/Users/mayorlc1/anaconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/artist.py", line 73, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/Users/mayorlc1/anaconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/Users/mayorlc1/anaconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/figure.py", line 2810, in draw
    mimage._draw_list_compositing_images(
  File "/Users/mayorlc1/anaconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/mayorlc1/anaconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/Users/mayorlc1/anaconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 3082, in draw
    mimage._draw_list_compositing_images(
  File "/Users/mayorlc1/anaconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/mayorlc1/anaconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer)
  File "/Users/mayorlc1/anaconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/image.py", line 646, in draw
    im, l, b, trans = self.make_image(
  File "/Users/mayorlc1/anaconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/image.py", line 956, in make_image
    return self._make_image(self._A, bbox, transformed_bbox, clip,
  File "/Users/mayorlc1/anaconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/image.py", line 547, in _make_image
    output = self.norm(resampled_masked)
  File "/Users/mayorlc1/anaconda3/envs/eureka/lib/python3.9/site-packages/matplotlib/colors.py", line 1245, in __call__
    raise ValueError("minvalue must be less than or equal to maxvalue")
ValueError: minvalue must be less than or equal to maxvalue

**Comment by taylorbell57** [comment]
Okay, thanks so much for checking!

**Comment by taylorbell57** [comment]
While I'm working on this, if this bug is keeping you from moving forward with other stages, just set is_plots=1 to avoid making all those buggy plots.

**Comment by taylorbell57** [comment]
Aha, the issue with the profile plot is that the errorbars don't share the same mask as the values which plt.errorbar is buggy about. That should be quite easy to fix without removing the masking utility. Looking into the imshow type plots now

**Comment by taylorbell57** [comment]
Okay, can you try out the edits I made in the issue228 branch when you get the chance (`git checkout issue228`)? As far as I can tell I've resolved the optimal_spectrum plot error, but I wasn't able to reproduce the error with the profile plot so I can't tell if that is fixed as well. If it isn't can you copy-paste your Stage 3 ecf into a comment on here so that I'm able to reproduce the error and debug it more
