### ISSUE TITLE
[Bug]: "RuntimeError: Invalid DISPLAY variable" when running S2

### ISSUE THREAD

**Issue by Witchblade101** [kevin218/Eureka#250]
### Contact Details

dlong@stsci.edu

### Instrument

NIRSpec (Stages 1-3)

### What happened?

I started an over night Eureka run on a remote server, using the 'screen' command, since I knew my ssh connection would time out from inactivity. For every step I set hide_plots to True. 

My S2 .ecf file looks like:

# Eureka! Control File for Stage 2: Data Reduction

suffix                  rateints    # Data file suffix

# Controls the cross-dispersion extraction
slit_y_low              -1      # Use None to rely on the default parameters
slit_y_high             50      # Use None to rely on the default parameters

# Modify the existing file to change the dispersion extraction - FIX: DOES NOT WORK CURRENTLY
waverange_start         6e-08   # Use None to rely on the default parameters
waverange_end           6e-06   # Use None to rely on the default parameters

# Note: different instruments and modes will use different steps by default
skip_bkg_subtract       False   # Not run for TSO observations
skip_imprint_subtract   True    # Not run for NIRSpec Fixed Slit
skip_msa_flagging       True    # Not run for NIRSpec Fixed Slit
skip_extract_2d         False
skip_srctype            False
skip_master_background  True    # Not run for NIRSpec Fixed Slit
skip_wavecorr           False
skip_flat_field         True    # ***NOTE*** At the time the NIRSpec ERS Hackathon simulated data was created, this step did not work correctly and is by default turned off.
skip_straylight         True    # Not run for NIRSpec Fixed Slit
skip_fringe             True    # Not run for NIRSpec Fixed Slit
skip_pathloss           False   # Not run for TSO observations
skip_barshadow          True    # Not run for NIRSpec Fixed Slit
skip_photom             True
skip_resample           False   # Not run for TSO observations
skip_cube_build         True    # Not run for NIRSpec Fixed Slit
skip_extract_1d         False

# Diagnostics
testing_S2              False
hide_plots              True   # If True, plots will automatically be closed rather than popping up

# Project directory
topdir                  /astro/jtste/simobs/2022-DataShowcase/NIRSpec/

# Directories relative to project dir
inputdir                Stage_1_Output
outputdir               dlong/Stage2

### Error traceback output

2022-03-30 21:54:59,149 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-03-30 21:55:00,657 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-03-30 21:55:02,171 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-03-30 21:55:03,689 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-03-30 21:55:05,208 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-03-30 21:55:06,728 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-03-30 21:55:08,248 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-03-30 21:55:09,770 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-03-30 21:55:11,293 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-03-30 21:55:12,805 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-03-30 21:55:14,322 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-03-30 21:55:15,833 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-03-30 21:55:17,357 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-03-30 21:55:18,872 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-03-30 21:55:20,385 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-03-30 21:55:21,899 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-03-30 21:55:23,405 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-03-30 21:55:24,649 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - All 8192 integrations done
2022-03-30 21:55:24,650 - stpipe.EurekaSpec2Pipeline.extract_1d - WARNING - INTSTART not found; assuming a value of 1.
2022-03-30 21:55:24,650 - stpipe.EurekaSpec2Pipeline.extract_1d - WARNING - INTEND not found; assuming a value of 8192.
2022-03-30 21:55:24,650 - stpipe.EurekaSpec2Pipeline.extract_1d - WARNING - There is no INT_TIMES table in the input file.
2022-03-31 01:22:34,476 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Saved model in /astro/jtste/simobs/2022-DataShowcase/NIRSpec/dlong/Stage2/S2_2022-03-30_wasp39b_run5/jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_MOD_injected_x1dints.fits
2022-03-31 01:22:34,477 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Step extract_1d done
2022-03-31 01:22:34,491 - stpipe.EurekaSpec2Pipeline - INFO - Finished processing product /astro/jtste/simobs/2022-DataShowcase/NIRSpec/Stage_1_Output/jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_MOD_injected
2022-03-31 01:22:34,491 - stpipe.EurekaSpec2Pipeline - INFO - Ending calwebb_spec2
2022-03-31 01:23:03,691 - stpipe.EurekaSpec2Pipeline - INFO - Saved model in /astro/jtste/simobs/2022-DataShowcase/NIRSpec/dlong/Stage2/S2_2022-03-30_wasp39b_run5/jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_MOD_injected_calints.fits
2022-03-31 01:23:03,691 - stpipe.EurekaSpec2Pipeline - INFO - Step EurekaSpec2Pipeline done

Generating x1dints figure
Traceback (most recent call last):
  File "/home/dlong/JWST/run_eureka.py", line 19, in <module>
    s2_meta = s2.calibrateJWST(eventlabel, ecf_path=ecf_path)
  File "/home/dlong/miniconda3/envs/Eureka/lib/python3.9/site-packages/eureka/S2_calibrations/s2_calibrate.py", line 134, in calibrateJWST
    pipeline.run_eurekaS2(filename, meta, log)
  File "/home/dlong/miniconda3/envs/Eureka/lib/python3.9/site-packages/eureka/S2_calibrations/s2_calibrate.py", line 251, in run_eurekaS2
    plt.figure(int('11{}'.format(str(0).zfill(int(np.floor(np.log10(max_m))+1)))), figsize=[15,5])
  File "/home/dlong/miniconda3/envs/Eureka/lib/python3.9/site-packages/matplotlib/pyplot.py", line 787, in figure
    manager = new_figure_manager(
  File "/home/dlong/miniconda3/envs/Eureka/lib/python3.9/site-packages/matplotlib/pyplot.py", line 306, in new_figure_manager
    return _backend_mod.new_figure_manager(*args, **kwargs)
  File "/home/dlong/miniconda3/envs/Eureka/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 3494, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/dlong/miniconda3/envs/Eureka/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 3499, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure)
  File "/home/dlong/miniconda3/envs/Eureka/lib/python3.9/site-packages/matplotlib/backends/backend_qtagg.py", line 21, in __init__
    super().__init__(figure=figure)
  File "/home/dlong/miniconda3/envs/Eureka/lib/python3.9/site-packages/matplotlib/backends/backend_qt.py", line 220, in __init__
    _create_qApp()
  File "/home/dlong/miniconda3/envs/Eureka/lib/python3.9/site-packages/matplotlib/backends/backend_qt.py", line 112, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
I'm not sure this is a Eureka specific issue - it seems that the code is crashing when you call plt.figure which is a pretty basic command and not something I can help much with. I'd recommend trying to google search a solution to your issue (e.g. search for something like "matplotlib RuntimeError: Invalid DISPLAY variable") and see what websites like stackoverflow suggest. Then let me know if there is a setting you need to be implemented into Eureka

**Comment by Witchblade101** [comment]
From the matplotlib documentation : https://matplotlib.org/stable/users/explain/backends.html

It sounds like there are 2 types of backends: "interactive backends" and "non-interactive backends". The default appears to be interactive, which will show a plot on the screen. If you want to just save to a file you have to explicitly switch to a non-interactive backend when you import matplotlib.

When I have the time I'll try creating a fork that specifies a non-interactive backend and try that running on a remote server again.

**Comment by taylorbell57** [comment]
Interesting, well we do currently have a method to set rcParams which should help (see the `eureka.lib.plots.set_rc()` function). I am realizing that we never actually call that function in the pipeline though, nor do we allow users to provide any inputs that would get passed into that function. That is definitely not as intended, so I'll open a new issue related to this one. For the time being, you can likely set any required rcParams settings in your `run_eureka.py` file before the lines importing eureka code and those settings should then hopefully carry forward
