### ISSUE TITLE
some error in stage 4.

### ISSUE THREAD

**Issue by jovian-explorer** [kevin218/Eureka#318]
### Instrument

NIRSpec stage 4

### What happened?

Idk, earlier I was successful in running it to stage 6 full, but some new error has popped up this time

### Error traceback output

Traceback (most recent call last):
  File "run_eureka.py", line 25, in <module>
    s4_meta = s4.lcJWST(eventlabel, ecf_path=ecf_path)
  File "/home/keshav/.local/lib/python3.8/site-packages/eureka/S4_generate_lightcurves/s4_genLC.py", line 101, in lcJWST
    meta = load_specific_s3_meta_info(old_meta, ecf_path, run_i, spec_hw_val, bg_hw_val)
  File "/home/keshav/.local/lib/python3.8/site-packages/eureka/S4_generate_lightcurves/s4_genLC.py", line 305, in load_specific_s3_meta_info
    new_meta = read_s3_meta(meta)
  File "/home/keshav/.local/lib/python3.8/site-packages/eureka/S4_generate_lightcurves/s4_genLC.py", line 256, in read_s3_meta
    raise AssertionError('Unable to find an output metadata file from Eureka!\'s S3 step '
AssertionError: Unable to find an output metadata file from Eureka!'s S3 step in the inputdir: 
"/home/keshav/Downloads/JWST_Sim/NIRSpec/Stage3/S3_2022-04-01_wasp39b_ap6_bg7_run2/"!

### What operating system are you using?

linux ubuntu 20.04

### What version of Python are you running?

python 3.7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kevin218** [comment]
Can you look in your input directory (/home/keshav/Downloads/JWST_Sim/NIRSpec/Stage3/S3_2022-04-01_wasp39b_ap6_bg7_run2/) and confirm that there is a Stage 3 metadata save file present?  Maybe the missing files are in a different location?

**Comment by jovian-explorer** [comment]
the issue is not that it is searchnig for an old file and cannot find it. the issue is why is it looking for an old file when it should be running the files generated in the previous step.

**Comment by jovian-explorer** [comment]
(base) keshav@dev:~/Eureka/demos/JWST$ python3 run_eureka.py 
Traceback (most recent call last):
  File "/home/keshav/Eureka/demos/JWST/run_eureka.py", line 3, in <module>
    import eureka.lib.plots
  File "/home/keshav/Eureka/demos/JWST/../../eureka/__init__.py", line 20, in <module>
    from . import S3_data_reduction
  File "/home/keshav/Eureka/demos/JWST/../../eureka/S3_data_reduction/__init__.py", line 5, in <module>
    from . import miri
  File "/home/keshav/Eureka/demos/JWST/../../eureka/S3_data_reduction/miri.py", line 4, in <module>
    import astraeus.xarrayIO as xrio
ModuleNotFoundError: No module named 'astraeus.xarrayIO'

**Comment by kevin218** [comment]
If it's not finding the right run, you can tell the code where to find the desired run by specifying the input directory in the ECF file.

**Comment by jovian-explorer** [comment]
I did that. but the issue is with the dates. It is searching for files from the last month, from the correct directory. nevermind I'll just close this as I am trying to install it from scratch now.
