### ISSUE TITLE
Some error with the CRDS commands

### ISSUE THREAD

**Issue by jovian-explorer** [kevin218/Eureka#329]
### Instrument

NIRSpec (Stages 1-3)

### What happened?

    (base) keshav@dev:~/Data/JWST-Sim/NIRSpec$ export CRDS_PATH=/home/keshav/Desktop/JWST-Sim/NIRSpec/crds_cache
    (base) keshav@dev:~/Data/JWST-Sim/NIRSpec$ export CRDS_SERVER_URL=https://jwst-crds.stsci.edu
    (base) keshav@dev:~/Data/JWST-Sim/NIRSpec$ python3 run_eureka.py 

    WARNING: Unable to find an output metadata file from Eureka!'s S2 in the folder:
    "/home/keshav/Data/JWST-Sim/NIRSpec/Stage1/"
    Assuming this S2 data was produced by the JWST pipeline instead.
    
    Starting Stage 2 Reduction
    Input directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage1/
    Output directory: /home/keshav/Data/JWST-Sim/NIRSpec/Stage2/S2_2022-05-22_wasp39b_run3/
    Copying S2 control file
    
    Found 1 data file(s) ending in rateints.fits
    2022-05-22 10:05:56,676 - stpipe.EurekaSpec2Pipeline - INFO - EurekaSpec2Pipeline instance created.
    2022-05-22 10:05:56,677 - stpipe.EurekaSpec2Pipeline.bkg_subtract - INFO - BackgroundStep instance created.
    2022-05-22 10:05:56,677 - stpipe.EurekaSpec2Pipeline.assign_wcs - INFO - AssignWcsStep instance created.
    2022-05-22 10:05:56,678 - stpipe.EurekaSpec2Pipeline.imprint_subtract - INFO - ImprintStep instance created.
    2022-05-22 10:05:56,678 - stpipe.EurekaSpec2Pipeline.msa_flagging - INFO - MSAFlagOpenStep instance created.
    2022-05-22 10:05:56,679 - stpipe.EurekaSpec2Pipeline.extract_2d - INFO - Extract2dStep instance created.
    2022-05-22 10:05:56,681 - stpipe.EurekaSpec2Pipeline.master_background - INFO - MasterBackgroundNrsSlitsStep instance created.
    2022-05-22 10:05:56,682 - stpipe.EurekaSpec2Pipeline.master_background.flat_field - INFO - FlatFieldStep instance created.
    2022-05-22 10:05:56,682 - stpipe.EurekaSpec2Pipeline.master_background.pathloss - INFO - PathLossStep instance created.
    2022-05-22 10:05:56,683 - stpipe.EurekaSpec2Pipeline.master_background.barshadow - INFO - BarShadowStep instance created.
    2022-05-22 10:05:56,683 - stpipe.EurekaSpec2Pipeline.master_background.photom - INFO - PhotomStep instance created.
    2022-05-22 10:05:56,684 - stpipe.EurekaSpec2Pipeline.wavecorr - INFO - WavecorrStep instance created.
    2022-05-22 10:05:56,685 - stpipe.EurekaSpec2Pipeline.flat_field - INFO - FlatFieldStep instance created.
    2022-05-22 10:05:56,685 - stpipe.EurekaSpec2Pipeline.srctype - INFO - SourceTypeStep instance created.
    2022-05-22 10:05:56,686 - stpipe.EurekaSpec2Pipeline.straylight - INFO - StraylightStep instance created.
    2022-05-22 10:05:56,686 - stpipe.EurekaSpec2Pipeline.fringe - INFO - FringeStep instance created.
    2022-05-22 10:05:56,687 - stpipe.EurekaSpec2Pipeline.pathloss - INFO - PathLossStep instance created.
    2022-05-22 10:05:56,687 - stpipe.EurekaSpec2Pipeline.barshadow - INFO - BarShadowStep instance created.
    2022-05-22 10:05:56,688 - stpipe.EurekaSpec2Pipeline.photom - INFO - PhotomStep instance created.
    2022-05-22 10:05:56,689 - stpipe.EurekaSpec2Pipeline.resample_spec - INFO - ResampleSpecStep instance created.
    2022-05-22 10:05:56,690 - stpipe.EurekaSpec2Pipeline.cube_build - INFO - CubeBuildStep instance created.
    2022-05-22 10:05:56,690 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Extract1dStep instance created.
    Starting file 1 of 1
    Editing (in place) the waverange in the input file
    2022-05-22 10:05:56,767 - stpipe - WARNING - /home/keshav/miniconda3/lib/python3.9/site-packages/asdf/entry_points.py:46: AsdfWarning: asdf.extensions plugin from package asdf-astropy==0.2.1 failed to load:
    
    ContextualVersionConflict: (PyYAML 3.10 (/home/keshav/miniconda3/lib/python3.9/site-packages), Requirement.parse('PyYAML>=3.13'), {'astropy'})
      warnings.warn(
    
    2022-05-22 10:05:56,779 - stpipe - WARNING - /home/keshav/miniconda3/lib/python3.9/site-packages/asdf/entry_points.py:46: AsdfWarning: asdf.extensions plugin from package gwcs==0.18.1 failed to load:
    
    ContextualVersionConflict: (PyYAML 3.10 (/home/keshav/miniconda3/lib/python3.9/site-packages), Requirement.parse('PyYAML>=3.13'), {'astropy'})
      warnings.warn(
    
    2022-05-22 10:05:56,779 - stpipe - WARNING - /home/keshav/miniconda3/lib/python3.9/site-packages/asdf/entry_points.py:46: AsdfWarning: asdf_extensions plugin from package astropy==5.0.4 failed to load:
    
    VersionConflict: (PyYAML 3.10 (/home/keshav/miniconda3/lib/python3.9/site-packages), Requirement.parse('PyYAML>=3.13'))
      warnings.warn(
    
    2022-05-22 10:05:56,920 - stpipe - WARNING - /home/keshav/miniconda3/lib/python3.9/site-packages/asdf/entry_points.py:46: AsdfWarning: asdf_extensions plugin from package jwst==1.3.3 failed to load:
    
    ContextualVersionConflict: (PyYAML 3.10 (/home/keshav/miniconda3/lib/python3.9/site-packages), Requirement.parse('PyYAML>=3.13'), {'astropy'})
      warnings.warn(
    
    2022-05-22 10:05:56,931 - stpipe - WARNING - /home/keshav/miniconda3/lib/python3.9/site-packages/asdf/entry_points.py:46: AsdfWarning: asdf_extensions plugin from package stpipe==0.3.3 failed to load:
    
    ContextualVersionConflict: (PyYAML 3.10 (/home/keshav/miniconda3/lib/python3.9/site-packages), Requirement.parse('PyYAML>=3.13'), {'astropy'})
      warnings.warn(
    
    2022-05-22 10:05:56,933 - stpipe - WARNING - /home/keshav/miniconda3/lib/python3.9/site-packages/asdf/entry_points.py:46: AsdfWarning: asdf.resource_mappings plugin from package asdf-astropy==0.2.1 failed to load:
    
    ContextualVersionConflict: (PyYAML 3.10 (/home/keshav/miniconda3/lib/python3.9/site-packages), Requirement.parse('PyYAML>=3.13'), {'astropy'})
      warnings.warn(

### Error traceback output

    Traceback (most recent call last):
      File "/home/keshav/Data/JWST-Sim/NIRSpec/run_eureka.py", line 25, in <module>
        s2_meta = s2.calibrateJWST(eventlabel, ecf_path=ecf_path)
      File "/home/keshav/miniconda3/lib/python3.9/site-packages/eureka/S2_calibrations/s2_calibrate.py", line 148, in calibrateJWST
        pipeline.run_eurekaS2(filename, meta, log)
      File "/home/keshav/miniconda3/lib/python3.9/site-packages/eureka/S2_calibrations/s2_calibrate.py", line 214, in run_eurekaS2
        with datamodels.open(filename) as m:
      File "/home/keshav/miniconda3/lib/python3.9/site-packages/jwst/datamodels/util.py", line 198, in open
        model = new_class(init, **kwargs)
      File "/home/keshav/miniconda3/lib/python3.9/site-packages/jwst/datamodels/cube.py", line 44, in __init__
        super(CubeModel, self).__init__(init=init, **kwargs)
      File "/home/keshav/miniconda3/lib/python3.9/site-packages/stdatamodels/model_base.py", line 164, in __init__
        schema = asdf_schema.load_schema(self.schema_url, resolve_references=True)
      File "/home/keshav/miniconda3/lib/python3.9/site-packages/asdf/schema.py", line 443, in load_schema
        return copy.deepcopy(_load_schema_cached(url, resolver, resolve_references, resolve_local_refs))
      File "/home/keshav/miniconda3/lib/python3.9/site-packages/asdf/schema.py", line 490, in _load_schema_cached
        schema, url = loader(url)
      File "/home/keshav/miniconda3/lib/python3.9/site-packages/asdf/schema.py", line 367, in load_schema
        return _load_schema(url)
      File "/home/keshav/miniconda3/lib/python3.9/site-packages/asdf/schema.py", line 331, in _load_schema
        raise FileNotFoundError("Unable to fetch schema from non-file URL: " + url)
    FileNotFoundError: Unable to fetch schema from non-file URL: http://stsci.edu/schemas/jwst_datamodel/cube.schema

### What operating system are you using?

linux ubuntu 20.04

### What version of Python are you running?

Python 3.9.7

### What Python packages do you have installed?

    (base) keshav@dev:~/Data/JWST-Sim/NIRSpec$ conda list
    # packages in environment at /home/keshav/miniconda3:
    #
    # Name                    Version                   Build  Channel
    _libgcc_mutex             0.1                        main  
    _openmp_mutex             4.5                       1_gnu  
    alabaster                 0.7.12                   pypi_0    pypi
    asdf                      2.10.1                   pypi_0    pypi
    asdf-astropy              0.2.1                    pypi_0    pypi
    asdf-coordinates-schemas  0.1.0                    pypi_0    pypi
    asdf-standard             1.0.2                    pypi_0    pypi
    asdf-transform-schemas    0.2.2                    pypi_0    pypi
    asdf-wcs-schemas          0.1.1                    pypi_0    pypi
    asteval                   0.9.26                   pypi_0    pypi
    astraeus                  0.1                      pypi_0    pypi
    astropy                   5.0.4                    pypi_0    pypi
    astropy-healpix           0.6                      pypi_0    pypi
    astroquery                0.4.6                    pypi_0    pypi
    astroscrappy              1.1.0                    pypi_0    pypi
    asttokens                 2.0.5                    pypi_0    pypi
    attrs                     21.4.0                   pypi_0    pypi
    babel                     2.10.1                   pypi_0    pypi
    backcall                  0.2.0                    pypi_0    pypi
    batman                    0.7.0                    pypi_0    pypi
    batman-package            2.4.8                    pypi_0    pypi
    bayesicfitting            3.0.1                    pypi_0    pypi
    beautifulsoup4            4.11.1                   pypi_0    pypi
    bleach                    5.0.0                    pypi_0    pypi
    bokeh                     2.4.3                    pypi_0    pypi
    bottleneck                1.3.4                    pypi_0    pypi
    brotlipy                  0.7.0           py39h27cfd23_1003  
    ca-certificates           2021.10.26           h06a4308_2  
    ccdproc                   2.3.1                    pypi_0    pypi
    celerite                  0.4.2                    pypi_0    pypi
    certifi                   2021.10.8        py39h06a4308_2  
    cffi                      1.15.0           py39hd667e15_1  
    cftime                    1.6.0                    pypi_0    pypi
    charset-normalizer        2.0.4              pyhd3eb1b0_0  
    cloudpickle               2.0.0                    pypi_0    pypi
    colorcet                  3.0.0                    pypi_0    pypi
    commonmark                0.9.1                    pypi_0    pypi
    conda                     4.11.0           py39h06a4308_0  
    conda-content-trust       0.1.1              pyhd3eb1b0_0  
    conda-package-handling    1.7.3            py39h27cfd23_1  
    corner                    2.2.1                    pypi_0    pypi
    crds                      11.14.0                  pypi_0    pypi
    cryptography              36.0.0           py39h9ce1e76_0  
    cycler                    0.11.0                   pypi_0    pypi
    cython                    0.29.28                  pypi_0    pypi
    dask                      2022.5.0                 pypi_0    pypi
    decorator                 5.1.1                    pypi_0    pypi
    defusedxml                0.7.1                    pypi_0    pypi
    distlib                   0.3.4                    pypi_0    pypi
    docutils                  0.17.1                   pypi_0    pypi
    drizzle                   1.13.4                   pypi_0    pypi
    dynesty                   1.2.2                    pypi_0    pypi
    emcee                     3.1.2                    pypi_0    pypi
    entrypoints               0.4                      pypi_0    pypi
    eureka                    0.0.1                    pypi_0    pypi
    executing                 0.8.3                    pypi_0    pypi
    exo-k                     1.1.1                    pypi_0    pypi
    fastjsonschema            2.15.3                   pypi_0    pypi
    filelock                  3.6.0                    pypi_0    pypi
    fonttools                 4.33.3                   pypi_0    pypi
    fsspec                    2022.3.0                 pypi_0    pypi
    future                    0.18.2                   pypi_0    pypi
    george                    0.4.0                    pypi_0    pypi
    greenlet                  1.1.2                    pypi_0    pypi
    gwcs                      0.18.1                   pypi_0    pypi
    h5netcdf                  1.0.0                    pypi_0    pypi
    h5py                      3.1.0                    pypi_0    pypi
    holoviews                 1.14.9                   pypi_0    pypi
    html5lib                  1.1                      pypi_0    pypi
    idna                      3.3                pyhd3eb1b0_0  
    imageio                   2.19.1                   pypi_0    pypi
    imagesize                 1.3.0                    pypi_0    pypi
    importlib-metadata        4.11.3                   pypi_0    pypi
    iniconfig                 1.1.1                    pypi_0    pypi
    ipython                   8.3.0                    pypi_0    pypi
    jedi                      0.18.1                   pypi_0    pypi
    jeepney                   0.8.0                    pypi_0    pypi
    jinja2                    3.1.2                    pypi_0    pypi
    jmespath                  1.0.0                    pypi_0    pypi
    joblib                    1.1.0                    pypi_0    pypi
    jsonschema                3.2.0                    pypi_0    pypi
    jupyter-client            7.3.1                    pypi_0    pypi
    jupyter-core              4.10.0                   pypi_0    pypi
    jupyterlab-pygments       0.2.2                    pypi_0    pypi
    jwst                      1.3.3                    pypi_0    pypi
    keyring                   23.5.0                   pypi_0    pypi
    kiwisolver                1.4.2                    pypi_0    pypi
    ld_impl_linux-64          2.35.1               h7274673_9  
    libffi                    3.3                  he6710b0_2  
    libgcc-ng                 9.3.0               h5101ec6_17  
    libgomp                   9.3.0               h5101ec6_17  
    libstdcxx-ng              9.3.0               hd4cf53a_17  
    llvmlite                  0.38.1                   pypi_0    pypi
    lmfit                     1.0.3                    pypi_0    pypi
    locket                    1.0.0                    pypi_0    pypi
    lxml                      4.8.0                    pypi_0    pypi
    markdown                  3.3.7                    pypi_0    pypi
    markdown-it-py            2.1.0                    pypi_0    pypi
    markupsafe                2.1.1                    pypi_0    pypi
    matplotlib                3.5.2                    pypi_0    pypi
    matplotlib-inline         0.1.3                    pypi_0    pypi
    mdit-py-plugins           0.3.0                    pypi_0    pypi
    mdurl                     0.1.1                    pypi_0    pypi
    mistune                   0.8.4                    pypi_0    pypi
    molmass                   2021.6.18                pypi_0    pypi
    myst-parser               0.17.2                   pypi_0    pypi
    nbclient                  0.6.3                    pypi_0    pypi
    nbconvert                 6.5.0                    pypi_0    pypi
    nbformat                  5.4.0                    pypi_0    pypi
    nbsphinx                  0.8.8                    pypi_0    pypi
    ncurses                   6.3                  h7f8727e_2  
    nest-asyncio              1.5.5                    pypi_0    pypi
    netcdf4                   1.5.8                    pypi_0    pypi
    networkx                  2.8                      pypi_0    pypi
    numba                     0.55.1                   pypi_0    pypi
    numpy                     1.21.6                   pypi_0    pypi
    numpydoc                  1.3.1                    pypi_0    pypi
    openssl                   1.1.1m               h7f8727e_0  
    packaging                 21.3                     pypi_0    pypi
    pandas                    1.4.2                    pypi_0    pypi
    pandeia-engine            1.7                      pypi_0    pypi
    pandexo-engine            1.5.3.1                  pypi_0    pypi
    pandocfilters             1.5.0                    pypi_0    pypi
    panel                     0.13.1rc2                pypi_0    pypi
    param                     1.12.1                   pypi_0    pypi
    parsley                   1.3                      pypi_0    pypi
    parso                     0.8.3                    pypi_0    pypi
    partd                     1.2.0                    pypi_0    pypi
    pbr                       5.9.0                    pypi_0    pypi
    petitradtrans             2.4.2                    pypi_0    pypi
    pexpect                   4.8.0                    pypi_0    pypi
    photutils                 1.1.0                    pypi_0    pypi
    picaso                    2.3.1                    pypi_0    pypi
    pickleshare               0.7.5                    pypi_0    pypi
    pillow                    9.1.0                    pypi_0    pypi
    pip                       21.2.4           py39h06a4308_0  
    platformdirs              2.5.2                    pypi_0    pypi
    pluggy                    1.0.0                    pypi_0    pypi
    poppy                     1.0.2                    pypi_0    pypi
    prompt-toolkit            3.0.29                   pypi_0    pypi
    psutil                    5.9.0                    pypi_0    pypi
    ptyprocess                0.7.0                    pypi_0    pypi
    pure-eval                 0.2.2                    pypi_0    pypi
    py                        1.11.0                   pypi_0    pypi
    pycosat                   0.6.3            py39h27cfd23_0  
    pycparser                 2.21               pyhd3eb1b0_0  
    pyct                      0.4.8                    pypi_0    pypi
    pyerfa                    2.0.0.1                  pypi_0    pypi
    pyfftw                    0.13.0                   pypi_0    pypi
    pygments                  2.12.0                   pypi_0    pypi
    pymiescatt                1.8.1.1                  pypi_0    pypi
    pymultinest               2.11                     pypi_0    pypi
    pyopenssl                 21.0.0             pyhd3eb1b0_1  
    pyparsing                 3.0.9                    pypi_0    pypi
    pyrsistent                0.18.1                   pypi_0    pypi
    pysocks                   1.7.1            py39h06a4308_0  
    pysynphot                 2.0.0                    pypi_0    pypi
    pytest                    7.1.2                    pypi_0    pypi
    python                    3.9.7                h12debd9_1  
    python-dateutil           2.8.2                    pypi_0    pypi
    pytz                      2022.1                   pypi_0    pypi
    pyviz-comms               2.2.0                    pypi_0    pypi
    pyvo                      1.3                      pypi_0    pypi
    pywavelets                1.3.0                    pypi_0    pypi
    pyyaml                    3.10                     pypi_0    pypi
    pyzmq                     22.3.0                   pypi_0    pypi
    readline                  8.1.2                h7f8727e_1  
    recommonmark              0.7.1                    pypi_0    pypi
    reproject                 0.8                      pypi_0    pypi
    requests                  2.27.1             pyhd3eb1b0_0  
    ruamel_yaml               0.15.100         py39h27cfd23_0  
    scikit-image              0.19.2                   pypi_0    pypi
    scipy                     1.8.0                    pypi_0    pypi
    seaborn                   0.11.2                   pypi_0    pypi
    secretstorage             3.3.2                    pypi_0    pypi
    semantic-version          2.9.0                    pypi_0    pypi
    setuptools                58.0.4           py39h06a4308_0  
    shapely                   1.8.2                    pypi_0    pypi
    six                       1.16.0             pyhd3eb1b0_0  
    snowballstemmer           2.2.0                    pypi_0    pypi
    soupsieve                 2.3.2.post1              pypi_0    pypi
    spherical-geometry        1.2.22                   pypi_0    pypi
    sphinx                    4.5.0                    pypi_0    pypi
    sphinx-rtd-theme          1.0.0                    pypi_0    pypi
    sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
    sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
    sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
    sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
    sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
    sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
    sqlalchemy                1.4.36                   pypi_0    pypi
    sqlite                    3.37.0               hc218d9a_0  
    stack-data                0.2.0                    pypi_0    pypi
    stcal                     0.6.4                    pypi_0    pypi
    stdatamodels              0.2.4                    pypi_0    pypi
    stevedore                 3.5.0                    pypi_0    pypi
    stpipe                    0.3.3                    pypi_0    pypi
    stsci-image               2.3.5                    pypi_0    pypi
    stsci-imagestats          1.6.3                    pypi_0    pypi
    stsci-stimage             0.2.5                    pypi_0    pypi
    stsynphot                 1.1.0                    pypi_0    pypi
    svo-filters               0.4.1                    pypi_0    pypi
    synphot                   1.1.1                    pypi_0    pypi
    tifffile                  2022.5.4                 pypi_0    pypi
    tinycss2                  1.1.1                    pypi_0    pypi
    tk                        8.6.11               h1ccaba5_0  
    tomli                     2.0.1                    pypi_0    pypi
    toolz                     0.11.2                   pypi_0    pypi
    tornado                   6.1                      pypi_0    pypi
    tqdm                      4.62.3             pyhd3eb1b0_1  
    traitlets                 5.2.0                    pypi_0    pypi
    tweakwcs                  0.7.4                    pypi_0    pypi
    typing-extensions         4.2.0                    pypi_0    pypi
    tzdata                    2021e                hda174b7_0  
    uncertainties             3.1.6                    pypi_0    pypi
    urllib3                   1.26.9                   pypi_0    pypi
    virga-exo                 0.3.4                    pypi_0    pypi
    virtualenv                20.14.1                  pypi_0    pypi
    virtualenv-clone          0.5.7                    pypi_0    pypi
    virtualenvwrapper         4.0                      pypi_0    pypi
    wcwidth                   0.2.5                    pypi_0    pypi
    webencodings              0.5.1                    pypi_0    pypi
    wheel                     0.37.1             pyhd3eb1b0_0  
    xarray                    2022.3.0                 pypi_0    pypi
    xz                        5.2.5                h7b6447c_0  
    yaml                      0.2.5                h7b6447c_0  
    zipp                      3.8.0                    pypi_0    pypi
    zlib                      1.2.11               h7f8727e_4  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jovian-explorer** [comment]
@AarynnCarter
