### ISSUE TITLE
[Bug]: S2 not working for NIRISS due to missing 'master_background' attribute

### ISSUE THREAD

**Issue by afeinstein20** [kevin218/Eureka#334]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

NIRISS (Stages 1-3)

### What happened?

'EurekaSpec2Pipeline.master_background' attribute missing, causing S2 reduction to fail on line 245 of `s2_calibrate.py`. I have run this for the new NIRISS tiny data set as well as the data set from the March data challenge. S2 had been working in previous versions of my/main branches.

### Error traceback output

Starting Stage 2 Reduction
Input directory: /Users/belugawhale/Documents/niriss_sim/tiny/Stage1/
Output directory: /Users/belugawhale/Documents/niriss_sim/tiny/Stage2/S2_2022-05-27_niriss_run6/
Copying S2 control file

Found 1 data file(s) ending in rampfitstep.fits
2022-05-27 10:33:46,027 - stpipe.EurekaSpec2Pipeline - INFO - EurekaSpec2Pipeline instance created.
2022-05-27 10:33:46,027 - stpipe.EurekaSpec2Pipeline.bkg_subtract - INFO - BackgroundStep instance created.
2022-05-27 10:33:46,028 - stpipe.EurekaSpec2Pipeline.assign_wcs - INFO - AssignWcsStep instance created.
2022-05-27 10:33:46,029 - stpipe.EurekaSpec2Pipeline.imprint_subtract - INFO - ImprintStep instance created.
2022-05-27 10:33:46,029 - stpipe.EurekaSpec2Pipeline.msa_flagging - INFO - MSAFlagOpenStep instance created.
2022-05-27 10:33:46,030 - stpipe.EurekaSpec2Pipeline.extract_2d - INFO - Extract2dStep instance created.
2022-05-27 10:33:46,032 - stpipe.EurekaSpec2Pipeline.master_background_mos - INFO - MasterBackgroundMosStep instance created.
2022-05-27 10:33:46,032 - stpipe.EurekaSpec2Pipeline.master_background_mos.flat_field - INFO - FlatFieldStep instance created.
2022-05-27 10:33:46,033 - stpipe.EurekaSpec2Pipeline.master_background_mos.pathloss - INFO - PathLossStep instance created.
2022-05-27 10:33:46,033 - stpipe.EurekaSpec2Pipeline.master_background_mos.barshadow - INFO - BarShadowStep instance created.
2022-05-27 10:33:46,034 - stpipe.EurekaSpec2Pipeline.master_background_mos.photom - INFO - PhotomStep instance created.
2022-05-27 10:33:46,034 - stpipe.EurekaSpec2Pipeline.wavecorr - INFO - WavecorrStep instance created.
2022-05-27 10:33:46,035 - stpipe.EurekaSpec2Pipeline.flat_field - INFO - FlatFieldStep instance created.
2022-05-27 10:33:46,035 - stpipe.EurekaSpec2Pipeline.srctype - INFO - SourceTypeStep instance created.
2022-05-27 10:33:46,036 - stpipe.EurekaSpec2Pipeline.straylight - INFO - StraylightStep instance created.
2022-05-27 10:33:46,036 - stpipe.EurekaSpec2Pipeline.fringe - INFO - FringeStep instance created.
2022-05-27 10:33:46,037 - stpipe.EurekaSpec2Pipeline.pathloss - INFO - PathLossStep instance created.
2022-05-27 10:33:46,037 - stpipe.EurekaSpec2Pipeline.barshadow - INFO - BarShadowStep instance created.
2022-05-27 10:33:46,038 - stpipe.EurekaSpec2Pipeline.wfss_contam - INFO - WfssContamStep instance created.
2022-05-27 10:33:46,039 - stpipe.EurekaSpec2Pipeline.photom - INFO - PhotomStep instance created.
2022-05-27 10:33:46,039 - stpipe.EurekaSpec2Pipeline.resample_spec - INFO - ResampleSpecStep instance created.
2022-05-27 10:33:46,040 - stpipe.EurekaSpec2Pipeline.cube_build - INFO - CubeBuildStep instance created.
2022-05-27 10:33:46,041 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Extract1dStep instance created.
Starting file 1 of 1
master background mos:  False
Traceback (most recent call last):
  File "/Users/belugawhale/Documents/GitHub/Eureka/test_script.py", line 15, in <module>
    s2_meta = s2.calibrateJWST(eventlabel, ecf_path=ecf_path)
  File "/Users/belugawhale/Documents/GitHub/Eureka/eureka/S2_calibrations/s2_calibrate.py", line 157, in calibrateJWST
    pipeline.run_eurekaS2(filename, meta, log)
  File "/Users/belugawhale/Documents/GitHub/Eureka/eureka/S2_calibrations/s2_calibrate.py", line 246, in run_eurekaS2
    self.master_background.skip = meta.skip_master_background
AttributeError: 'EurekaSpec2Pipeline' object has no attribute 'master_background'

### What operating system are you using?

Mac OS 12.2.1

### What version of Python are you running?

Python 3.9.7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
My initial guess is that NIRISS doesn't have a master_background step, and this website seems to confirm that:
https://jwst-pipeline.readthedocs.io/en/latest/jwst/pipeline/calwebb_spec2.html

**Comment by afeinstein20** [comment]
Hmm, ok I've added an if not NIRISS, do this step (which seems to work). Using Kevin's ECF file now instead of mine, I get

`File "/Users/belugawhale/Documents/GitHub/Eureka/test_script.py", line 15, in <module>
    s2_meta = s2.calibrateJWST(eventlabel, ecf_path=ecf_path)
  File "/Users/belugawhale/Documents/GitHub/Eureka/eureka/S2_calibrations/s2_calibrate.py", line 158, in calibrateJWST
    pipeline.run_eurekaS2(filename, meta, log)
  File "/Users/belugawhale/Documents/GitHub/Eureka/eureka/S2_calibrations/s2_calibrate.py", line 281, in run_eurekaS2
    with datamodels.open(meta.outputdir+x1d_fname+'.fits') as sp1d:
  File "/Users/belugawhale/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/jwst/datamodels/util.py", line 129, in open
    hdulist = fits.open(init, memmap=memmap)
  File "/Users/belugawhale/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 176, in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, cache,
  File "/Users/belugawhale/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 411, in fromfile
    return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
  File "/Users/belugawhale/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 1071, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/Users/belugawhale/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/Users/belugawhale/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/file.py", line 175, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/Users/belugawhale/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/file.py", line 564, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/Users/belugawhale/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/util.py", line 388, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/belugawhale/Documents/niriss_sim/tiny/Stage2/S2_2022-05-27_niriss_run1/WASP39_NIS_SOSS-seg002_CLEAR_tiny_3_0_x1dints.fits'
`

which I'm not sure why it's not generating this file anymore

**Comment by afeinstein20** [comment]
There's an `x1d.fits` file, but no `x1dints.fits`?

**Comment by kevin218** [comment]
S2 fails when there is only 1 integration in the file. Try the slightly larger file with 3 integrations.
