### ISSUE TITLE
[Bug]: Incorrect time arrays in S3 traced back to S1 custom ramp fitting stripping int_times from header

### ISSUE THREAD

**Issue by erinmmay** [kevin218/Eureka#396]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

NIRSpec (Stages 1-3)

### What happened?

After stage 1 all headers contain no data in the int_times keyword. 

As a result in stage 3 it assumes it is simulated data (i.e with no int_times values) and creates time arrays that have length=intend where intend is the number of the last integration in that segment. For a single segment this works, but for multiple segments, when running segment 2+, this results in a time array that is too long and you get the error below.

Best @cpiaulet, @AarynnCarter, and I can trace it back to is the custom ramp fitting in stage 1 which does set the int_times array to empty in multiple places. Assuming this is a holdover from the simulated data? We need some assistance from someone more familiar with this step!

### Error traceback output

Traceback (most recent call last):
 File “/home/mayem1/Analysis/JWST/wasp39b/nirspec_prism/run_eureka.py”, line 28, in <module>
  s3_spec, s3_meta = s3.reduce(eventlabel, ecf_path=ecf_path)
 File “/home/mayem1/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/s3_reduce.py”, line 236, in reduce
  data, meta, log = inst.read(meta.segment_list[i], data,
 File “/home/mayem1/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/nirspec.py”, line 85, in read
  data[‘flux’] = xrio.makeFluxLikeDA(sci, time, flux_units, time_units,
 File “/home/mayem1/anaconda3/envs/eureka/lib/python3.9/site-packages/astraeus/xarrayIO.py”, line 114, in makeFluxLikeDA
  da = xr.DataArray(
 File “/home/mayem1/anaconda3/envs/eureka/lib/python3.9/site-packages/xarray/core/dataarray.py”, line 402, in __init__
  coords, dims = _infer_coords_and_dims(data.shape, coords, dims)
 File “/home/mayem1/anaconda3/envs/eureka/lib/python3.9/site-packages/xarray/core/dataarray.py”, line 152, in _infer_coords_and_dims
  raise ValueError(
ValueError: conflicting sizes for dimension ‘time’: length 6100 on the data but length 12200 on coordinate ‘time’

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Can you try commenting out https://github.com/kevin218/Eureka/blob/71d9abc3a1566256fc650ba06a3708cfc05dd0d1/src/eureka/S1_detector_processing/ramp_fitting.py#L741 and https://github.com/kevin218/Eureka/blob/71d9abc3a1566256fc650ba06a3708cfc05dd0d1/src/eureka/S1_detector_processing/ramp_fitting.py#L749 and see if that fixes it?

**Comment by AarynnCarter** [comment]
Going to take a look now

**Comment by taylorbell57** [comment]
If that ends up fixing it, then it was a mistake on my part caused by trying to update the stcal package version for jwst==1.6.0 in PR #373 because stcal removed int_times from the contents of integ_info. If that doesn't fix it, it's likely still somehow related to that change in stcal version and how the custom ramp model was written (Aarynn and Eva-Maria are the ones that wrote Stage 1 and are likely the ones best suited to investigate the issue)

**Comment by erinmmay** [comment]
Commenting out line 741 removes int_times completely from the header. Line 749 isn't in the most up to date version of ramp_fitting.py.

**Comment by taylorbell57** [comment]
Ah thanks, yeah I don't know how I ended up navigating to that old version of the pipeline. Okay, well someone is going to have to look into how we're supposed to get the int_times array since it was removed from the integ_info returned from the a function in stcal

**Comment by erinmmay** [comment]
unfortunately I'm out of town for a week starting tomorrow morning or I'd try to help diagnose this. in the meantime I'm forging ahead with someone else's files that went through the standard jwst pipeline stage 1 and will hopefully not find too many other bugs :D

**Comment by taylorbell57** [comment]
All good! FYI, you'll likely want to make sure you're working with the very newest commit on the repo FYI - there's been a lot of PRs merged in the past 2 days since v0.2

**Comment by AarynnCarter** [comment]
I think I've fixed it but I've managed to mess up my dev/alc branch... will try to get a PR up soon

**Comment by kcrasmus** [comment]
Hey, I'm having a similar issue with NIRSpec data I've downloaded from MAST and have been running from Stage 2. Errors out with 

Found 5 data file(s) ending in calints.fits
WARNING: Are you using real JWST data? If so, you should edit the flag_bg() function in nirspec.py and look at Issue #193 on Github!
Starting file 1 of 5
  WARNING: Manually setting INTSTART to 1 and INTEND to NINTS
Traceback (most recent call last):
  File "/Users/rasmussen/Research/WORKING_Eureka/demos/run_JN_eureka.py", line 37, in <module>
    s3_spec, s3_meta = s3.reduce(eventlabel, ecf_path=ecf_path,
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/s3_reduce.py", line 224, in reduce
    data, meta, log = inst.read(meta.segment_list[i], data, 
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/nirspec.py", line 63, in read
    int_times = hdulist['INT_TIMES', 1].data
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 322, in __getitem__
    self._positive_index_of(key))
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 777, in _positive_index_of
    index = self.index_of(key)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 758, in index_of
    raise KeyError(f'Extension {key!r} not found.')
KeyError: "Extension ('INT_TIMES', 1) not found."
