### ISSUE TITLE
[Bug]: Issue with finding source position if it is close to the edge of the detector

### ISSUE THREAD

**Issue by lauraflagg** [kevin218/Eureka#436]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

NIRSpec (Stages 1-3)

### What happened?

For G395H, because the trace is curved, sometimes the initial source position is fairly close to the edge of the detector and the spec_hw puts it over the edge of the detector.  So, when pos_max-meta.spec_hw is calculated, it returns a negative number, obviously results in the code breaking when the negative number is used to index the array.  

I was able to fix this fairly easily by checking if pos_max-meta.spec_hw is less than 0  (or meta.ywindow[0]) and if so, setting it to 0 (or meta.ywindow[0]).

### Error traceback output

Traceback (most recent call last):
  File "/Users/lflagg/OneDrive - Cornell University/Eureka/demos/WASP39b_G395/run_eureka_nrs1.py", line 29, in <module>
    s3_spec, s3_meta = s3.reduce(eventlabel, ecf_path=ecf_path)
  File "/Users/lflagg/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/s3_reduce.py", line 287, in reduce
    data, meta, log = source_pos.source_pos_wrapper(data, meta,
  File "/Users/lflagg/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/source_pos.py", line 99, in source_pos_wrapper
    meta.src_ypos = source_pos(flux[integ], meta, data.attrs['shdr'],
  File "/Users/lflagg/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/source_pos.py", line 160, in source_pos
    src_ypos, src_ywidth = source_pos_gauss(flux, meta, m, n, plot)
  File "/Users/lflagg/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/source_pos.py", line 359, in source_pos_gauss
    print(np.ma.max(sum_row))
  File "/Users/lflagg/anaconda3/envs/eureka/lib/python3.9/site-packages/numpy/ma/core.py", line 6716, in max
    return obj.max(axis=axis, fill_value=fill_value, out=out, **kwargs)
  File "/Users/lflagg/anaconda3/envs/eureka/lib/python3.9/site-packages/numpy/ma/core.py", line 5837, in max
    result = self.filled(fill_value).max(
  File "/Users/lflagg/anaconda3/envs/eureka/lib/python3.9/site-packages/numpy/core/_methods.py", line 40, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jovian-explorer** [comment]
I am facing the exact same issue with the jw01366003001_04101_00001-seg001_nrs1_rateints.fits uploaded on the box folder.

**Comment by taylorbell57** [comment]
> I am facing the exact same issue with the jw01366003001_04101_00001-seg001_nrs1_rateints.fits uploaded on the box folder.

@jovian-explorer, is the file you mention a G395H file or a PRISM file? If it is a PRISM file, then your issue is likely unrelated and you should just be able to set src_pos_type to gaussian and have that work.

**Comment by jovian-explorer** [comment]
> > I am facing the exact same issue with the jw01366003001_04101_00001-seg001_nrs1_rateints.fits uploaded on the box folder.
> 
> @jovian-explorer, is the file you mention a G395H file or a PRISM file? If it is a PRISM file, then your issue is likely unrelated and you should just be able to set src_pos_type to gaussian and have that work.

**Comment by taylorbell57** [comment]
This has been resolved by PR #441, so closing this issue now
