### ISSUE TITLE
Stage 2 stalls after finishing integration extractions and aperture corrections

### ISSUE THREAD

**Issue by kcrasmus** [kevin218/Eureka#438]
### Instrument

NIRSpec (Stages 1-3)

### What happened?

After completing the ~12,000 integration extractions and aperture corrections, Eureka does not move onto the next step for several hours. Looking at other issues (250) makes me think something should be printed immediately after it finishes this step. When I ctrl-c out of the code, I get a series of tracebacks that make me think something is not being written to a header correctly.

### Error traceback output

2022-07-29 15:15:20,788 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-07-29 15:15:21,876 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Extracting integration 12202
2022-07-29 15:15:22,046 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-07-29 15:15:23,190 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Extracting integration 12203
2022-07-29 15:15:23,372 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-07-29 15:15:29,045 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Extracting integration 12204
2022-07-29 15:15:29,267 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Applying Aperture correction.
2022-07-29 15:15:30,418 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - All 12204 integrations done
^CTraceback (most recent call last):
  File "/Users/rasmussen/Research/WORKING_Eureka/demos/run_JN_eureka.py", line 33, in <module>
    #s2_meta = s2.calibrateJWST(eventlabel, ecf_path=ecf_path)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S2_calibrations/s2_calibrate.py", line 159, in calibrateJWST
    pipeline.run_eurekaS2(filename, meta, log)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S2_calibrations/s2_calibrate.py", line 252, in run_eurekaS2
    self(filename)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stpipe/step.py", line 485, in run
    step_result = self.process(*args)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 117, in process
    result = self.process_exposure_product(
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 307, in process_exposure_product
    x1d = self.extract_1d(resampled)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stpipe/step.py", line 529, in run
    self.save_model(result, idx=idx, format=self.name_format)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stpipe/step.py", line 993, in save_model
    output_path = model.save(
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stdatamodels/model_base.py", line 523, in save
    self.to_fits(output_path, *args, **kwargs)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stdatamodels/model_base.py", line 635, in to_fits
    hdulist, tree = fits_support.to_fits(self._instance, self._schema)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 433, in to_fits
    _save_from_schema(hdulist, tree, schema)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 369, in _save_from_schema
    validator.validate(tree, _schema=schema)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/jsonschema/validators.py", line 267, in validate
    for error in self.iter_errors(*args, **kwargs):
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/asdf/schema.py", line 315, in iter_errors
    yield from super(ASDFValidator, self).iter_errors(instance)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/jsonschema/validators.py", line 242, in iter_errors
    for error in errors:
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 219, in _fits_comment_section_handler
    for error in validator.descend(
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/jsonschema/validators.py", line 259, in descend
    for error in self.evolve(schema=schema).iter_errors(instance):
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/asdf/schema.py", line 315, in iter_errors
    yield from super(ASDFValidator, self).iter_errors(instance)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/jsonschema/validators.py", line 242, in iter_errors
    for error in errors:
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 296, in _fits_item_recurse
    for error in validator.descend(item, items, path=index):
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/jsonschema/validators.py", line 259, in descend
    for error in self.evolve(schema=schema).iter_errors(instance):
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/asdf/schema.py", line 315, in iter_errors
    yield from super(ASDFValidator, self).iter_errors(instance)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/jsonschema/validators.py", line 242, in iter_errors
    for error in errors:
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 219, in _fits_comment_section_handler
    for error in validator.descend(
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/jsonschema/validators.py", line 259, in descend
    for error in self.evolve(schema=schema).iter_errors(instance):
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/asdf/schema.py", line 315, in iter_errors
    yield from super(ASDFValidator, self).iter_errors(instance)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/jsonschema/validators.py", line 241, in iter_errors
    errors = validator(self, v, instance, _schema) or ()
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 237, in _fits_element_writer
    hdu = _get_or_make_hdu(fits_context.hdulist, hdu_name, index=fits_context.sequence_index)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 180, in _get_or_make_hdu
    hdu = get_hdu(hdulist, hdu_name, index=index)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/stdatamodels/fits_support.py", line 134, in get_hdu
    hdu = hdulist[pair]
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 322, in __getitem__
    self._positive_index_of(key))
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 777, in _positive_index_of
    index = self.index_of(key)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 753, in index_of
    (_ver is None or _ver == hdu.ver)):
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/hdu/base.py", line 209, in ver
    return self._header.get('EXTVER', 1)
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/header.py", line 887, in get
    return self[key]
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/header.py", line 163, in __getitem__
    value = card.value
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/card.py", line 293, in value
    if conf.strip_header_whitespace and isinstance(value, str):
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/config/configuration.py", line 303, in __get__
    return self()
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/config/configuration.py", line 430, in __call__
    options.append((sec[self.name], self.module, self.name))
  File "/Users/rasmussen/opt/anaconda3/envs/eureka/lib/python3.9/site-packages/astropy/extern/configobj/configobj.py", line 550, in __getitem__
    def __getitem__(self, key):
KeyboardInterrupt

### What operating system are you using?

Mac OSX with M1 chip

### What version of Python are you running?

3.9

### What Python packages do you have installed?

# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
appnope                   0.1.2           py39hca03da5_1001    anaconda
asdf                      2.12.0                   pypi_0    pypi
asdf-astropy              0.2.1                    pypi_0    pypi
asdf-coordinates-schemas  0.1.0                    pypi_0    pypi
asdf-standard             1.0.2                    pypi_0    pypi
asdf-transform-schemas    0.2.2                    pypi_0    pypi
asdf-wcs-schemas          0.1.1                    pypi_0    pypi
asteval                   0.9.27                   pypi_0    pypi
astraeus                  0.2                      pypi_0    pypi
astropy                   5.1                      pypi_0    pypi
astropy-healpix           0.6                      pypi_0    pypi
astroquery                0.4.6                    pypi_0    pypi
astroscrappy              1.1.0                    pypi_0    pypi
asttokens                 2.0.5              pyhd3eb1b0_0    anaconda
attrs                     21.4.0                   pypi_0    pypi
babel                     2.10.3                   pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0    anaconda
bayesicfitting            3.0.1                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
blas                      1.0                    openblas  
bokeh                     2.4.3                    pypi_0    pypi
bottleneck                1.3.5                    pypi_0    pypi
brotli                    1.0.7                hc377ac9_0  
c-ares                    1.18.1               h1a28f6b_0  
ca-certificates           2022.07.19           hca03da5_0  
ccdproc                   2.3.1                    pypi_0    pypi
celerite                  0.4.2                    pypi_0    pypi
certifi                   2022.5.18.1              pypi_0    pypi
cftime                    1.6.1                    pypi_0    pypi
charset-normalizer        2.1.0                    pypi_0    pypi
cloudpickle               2.1.0                    pypi_0    pypi
corner                    2.2.1                    pypi_0    pypi
crds                      11.16.6                  pypi_0    pypi
cycler                    0.11.0             pyhd3eb1b0_0  
cython                    0.29.30                  pypi_0    pypi
dask                      2022.7.1                 pypi_0    pypi
debugpy                   1.5.1            py39hc377ac9_0    anaconda
decorator                 5.1.1              pyhd3eb1b0_0    anaconda
docutils                  0.19                     pypi_0    pypi
drizzle                   1.13.4                   pypi_0    pypi
dynesty                   1.2.3                    pypi_0    pypi
emcee                     3.1.2                    pypi_0    pypi
entrypoints               0.4              py39hca03da5_0    anaconda
eureka                    0.4.dev0+g03256a1.d20220726          pypi_0    pypi
executing                 0.8.3              pyhd3eb1b0_0    anaconda
exotic-ld                 2.0.0                    pypi_0    pypi
expat                     2.4.4                hc377ac9_0  
filelock                  3.7.1                    pypi_0    pypi
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.11.0               h1192e45_0  
fsspec                    2022.5.0                 pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
george                    0.4.0                    pypi_0    pypi
giflib                    5.2.1                h1a28f6b_0  
gwcs                      0.18.1                   pypi_0    pypi
h5netcdf                  1.0.1                    pypi_0    pypi
h5py                      3.6.0            py39h7fe8675_0  
hdf5                      1.12.1               h160e8cb_2  
html5lib                  1.1                      pypi_0    pypi
idna                      3.3                      pypi_0    pypi
imageio                   2.20.0                   pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        4.12.0                   pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
ipykernel                 6.9.1            py39hca03da5_0    anaconda
ipython                   8.2.0            py39hca03da5_0    anaconda
jedi                      0.18.1           py39hca03da5_1    anaconda
jinja2                    3.1.2                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
jpeg                      9e                   h1a28f6b_0  
jsonschema                4.7.2                    pypi_0    pypi
jupyter_client            7.2.2            py39hca03da5_0    anaconda
jupyter_core              4.9.2            py39hca03da5_0    anaconda
jwst                      1.6.2                    pypi_0    pypi
keyring                   23.7.0                   pypi_0    pypi
kiwisolver                1.4.2            py39hc377ac9_0  
krb5                      1.19.2               h3b8d789_0  
lcms2                     2.12                 hba8e193_0  
libcurl                   7.82.0               hc6d1d07_0  
libcxx                    12.0.0               hf6beb65_1  
libedit                   3.1.20210910         h1a28f6b_0  
libev                     4.33                 h1a28f6b_1  
libffi                    3.4.2                hc377ac9_4  
libgfortran               5.0.0           11_2_0_he6877d6_26  
libgfortran5              11.2.0              he6877d6_26  
libiconv                  1.16                 h1a28f6b_2  
libnghttp2                1.46.0               h95c9599_0  
libopenblas               0.3.20               hea475bc_0  
libpng                    1.6.37               hb8d0fd4_0  
libsodium                 1.0.18               h1a28f6b_0    anaconda
libssh2                   1.10.0               hf27765b_0  
libtiff                   4.2.0                h01837e1_1  
libwebp                   1.2.2                h68602c7_0  
libwebp-base              1.2.2                h1a28f6b_0  
llvm-openmp               12.0.0               haf9daa7_1  
lmfit                     1.0.3                    pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
lxml                      4.9.1                    pypi_0    pypi
lz4-c                     1.9.3                hc377ac9_0  
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.1            py39hca03da5_1  
matplotlib-base           3.5.1            py39hc377ac9_1  
matplotlib-inline         0.1.2              pyhd3eb1b0_2    anaconda
munkres                   1.1.4                      py_0  
ncurses                   6.3                  h1a28f6b_3  
nest-asyncio              1.5.5            py39hca03da5_0    anaconda
netcdf4                   1.6.0                    pypi_0    pypi
networkx                  2.8.5                    pypi_0    pypi
numpy                     1.22.4                   pypi_0    pypi
numpy-base                1.22.3           py39h974a1f5_0  
numpydoc                  1.4.0                    pypi_0    pypi
openssl                   1.1.1q               h1a28f6b_0  
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.4.3                    pypi_0    pypi
parsley                   1.3                      pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0    anaconda
partd                     1.2.0                    pypi_0    pypi
pexpect                   4.8.0              pyhd3eb1b0_3    anaconda
photutils                 1.5.0                    pypi_0    pypi
pickleshare               0.7.5           pyhd3eb1b0_1003    anaconda
pillow                    9.2.0            py39h4d1bdd5_1  
pip                       22.1.2           py39hca03da5_0  
pluggy                    1.0.0                    pypi_0    pypi
poppy                     1.0.3                    pypi_0    pypi
prompt-toolkit            3.0.20             pyhd3eb1b0_0    anaconda
psutil                    5.9.1                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2    anaconda
pure_eval                 0.2.2              pyhd3eb1b0_0    anaconda
py                        1.11.0                   pypi_0    pypi
pyerfa                    2.0.0.1                  pypi_0    pypi
pygments                  2.11.2             pyhd3eb1b0_0    anaconda
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
pysynphot                 2.0.0                    pypi_0    pypi
pytest                    7.1.2                    pypi_0    pypi
python                    3.9.7                hc70090a_1  
python-dateutil           2.8.2              pyhd3eb1b0_0    anaconda
pytz                      2022.1                   pypi_0    pypi
pyvo                      1.3                      pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     22.3.0           py39hc377ac9_2    anaconda
readline                  8.1.2                h1a28f6b_1  
reproject                 0.8                      pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scipy                     1.7.3            py39h2f0f56f_0  
semantic-version          2.10.0                   pypi_0    pypi
setuptools                61.2.0           py39hca03da5_0  
six                       1.16.0             pyhd3eb1b0_1    anaconda
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
spherical-geometry        1.2.22                   pypi_0    pypi
sphinx                    5.1.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.38.5               h1058600_0  
stack_data                0.2.0              pyhd3eb1b0_0    anaconda
stcal                     1.0.0                    pypi_0    pypi
stdatamodels              0.4.3                    pypi_0    pypi
stpipe                    0.4.1                    pypi_0    pypi
stsci-image               2.3.5                    pypi_0    pypi
stsci-imagestats          1.6.3                    pypi_0    pypi
stsci-stimage             0.2.5                    pypi_0    pypi
svo-filters               0.4.3                    pypi_0    pypi
tifffile                  2022.5.4                 pypi_0    pypi
tk                        8.6.12               hb8d0fd4_0  
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
tornado                   6.1              py39h1a28f6b_0    anaconda
tqdm                      4.64.0           py39hca03da5_0  
traitlets                 5.1.1              pyhd3eb1b0_0    anaconda
tweakwcs                  0.7.4                    pypi_0    pypi
typing-extensions         4.3.0                    pypi_0    pypi
tzdata                    2022a                hda174b7_0  
uncertainties             3.1.7                    pypi_0    pypi
urllib3                   1.26.11                  pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0    anaconda
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
wiimatch                  0.3.1                    pypi_0    pypi
xarray                    2022.6.0                 pypi_0    pypi
xz                        5.2.5                h1a28f6b_1  
zeromq                    4.3.4                hc377ac9_0    anaconda
zipp                      3.8.1                    pypi_0    pypi
zlib                      1.2.12               h5a0b063_2  
zstd                      1.5.2                h8574219_0 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Unfortunately this does not seem to be an issue with Eureka but rather with the `jwst` pipeline. Please contact them directly at https://github.com/spacetelescope/jwst/issues as there is nothing we can really do on our end

**Comment by kcrasmus** [comment]
Gotcha, thanks for pointing me in the right direction!

Kaitlin
