### ISSUE TITLE
astraeus package unknown

### ISSUE THREAD

**Issue by svaverbe** [kevin218/Eureka#493]
### What happened?

While installing the latest version of Eureka using pip setup.py install, there is a package called astraeus that can't be downloaded.

### Error traceback output

Installed /home/siegfried/anaconda3/lib/python3.8/site-packages/astroquery-0.4.7.dev8076-py3.8.egg
Searching for astraeus@ git+https://github.com/kevin218/Astraeus@main
Reading https://pypi.org/simple/astraeus/
Couldn't find index page for 'astraeus' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for astraeus@ git+https://github.com/kevin218/Astraeus@main
error: Could not find suitable distribution for Requirement.parse('astraeus@ git+https://github.com/kevin218/Astraeus@main')

### What operating system are you using?

Windows subsystem for Linux on windows 10

### What version of Python are you running?

Python 3.8.3

### What Python packages do you have installed?

All packages in a conda environment called eureka according to setup.py

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jbrande** [comment]
If the recommended install instructions for Eureka! aren't working to install Astraeus, you might try the Astraeus install instructions separately: https://kevin218.github.io/Astraeus/#installation

Let us know if that also doesn't work.

**Comment by taylorbell57** [comment]
Are you sure you're following our installation instructions closely? There are no `pip setup.py install` instructions. You should be doing something more like `pip install '.[jwst]'`

**Comment by taylorbell57** [comment]
If you haven't seen the installation instructions yet, they're here: https://eurekadocs.readthedocs.io/en/latest/installation.html

**Comment by svaverbe** [comment]
The Astraeus package seems to be correctly installed using pip install '.[jwst]'.  After setting the CDRS environment variables, I get the following error message: 

/mnt/d/eureka/MyFirstEureka/JWST$ python run_eureka.py
Traceback (most recent call last):
  File "/mnt/d/eureka/MyFirstEureka/JWST/run_eureka.py", line 23, in <module>
    s2_meta = s2.calibrateJWST(eventlabel, ecf_path=ecf_path)
  File "/home/siegfried/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S2_calibrations/s2_calibrate.py", line 69, in calibrateJWST
    meta = readECF.MetaClass(ecf_path, ecffile)
  File "/home/siegfried/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/lib/readECF.py", line 57, in __init__
    self.read(folder, file)
  File "/home/siegfried/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/lib/readECF.py", line 200, in read
    self.inputdir = os.path.join(self.topdir,
AttributeError: 'MetaClass' object has no attribute 'topdir'

**Comment by kevin218** [comment]
It looks like topdir isn't defined in your Stage 2 ECF.

**Comment by svaverbe** [comment]
All directories are set and eureka runs through its stages,  At the end of stage 2, it stumbles upon an issue with qt:

2022-12-04 18:00:15,489 - stpipe.EurekaSpec2Pipeline - INFO - Saved model in /mnt/d/eureka/data_analysis/stage2/S2_2022-12-04_wasp39b_run7/jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_TINY_injected_calints.fits
2022-12-04 18:00:15,489 - stpipe.EurekaSpec2Pipeline - INFO - Step EurekaSpec2Pipeline done

Generating x1dints figure
QObject::moveToThread: Current thread (0x556bb8db9d70) is not the object's thread (0x556bb22201a0).
Cannot move to target thread (0x556bb8db9d70)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/siegfried/anaconda3/envs/eureka/lib/python3.9/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, minimal, minimalegl, offscreen, vnc, webgl.

Aborted

**Comment by kevin218** [comment]
This appears to be a problem finding qt. Try this link for possible
solutions:
https://forum.qt.io/topic/111553/solved-qt-qpa-plugin-could-not-find-the-qt-platform-plugin-xcb-in
.

**Comment by taylorbell57** [comment]
Are you running this on a remote computer without a screen? Matplotlib can have issues in that case. If that's the case, maybe at least trying to set hide_plots to True in the Stage 2-6 ECFs

**Comment by svaverbe** [comment]
No I am working with windows subsystem for linux on a windows 10 laptop.  I am going to look at the link you just sent me.

**Comment by taylorbell57** [comment]
Ah, I've done that too and unless you've setup forwarding of the Linux display to Windows, then you basically are using a computer without a display and setting hide_plots to True might help. It might not solve all of the problem though.

**Comment by kevin218** [comment]
https://jwst-docs.stsci.edu/

**Comment by svaverbe** [comment]
Also checked the download script for JWST data.  The script uses the package keyring that I  have in my conda environment, but it is entirely clear what I should do next:

python  download_data_JWST_template.py
Traceback (most recent call last):
  File "/mnt/d/eureka/MyFirstEureka/jWST/download_data_JWST_template.py", line 38, in <module>
    md.login(mast_token)
  File "/home/siegfried/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/lib/mastDownload.py", line 87, in login
    Observations.login(mast_token)
  File "/home/siegfried/anaconda3/envs/eureka/lib/python3.9/site-packages/astroquery-0.4.7.dev8076-py3.9.egg/astroquery/query.py", line 153, in login
    bases[0].login(*args, **kwargs)
  File "/home/siegfried/anaconda3/envs/eureka/lib/python3.9/site-packages/astroquery-0.4.7.dev8076-py3.9.egg/astroquery/query.py", line 516, in login
    self._authenticated = self._login(*args, **kwargs)
  File "/home/siegfried/anaconda3/envs/eureka/lib/python3.9/site-packages/astroquery-0.4.7.dev8076-py3.9.egg/astroquery/mast/core.py", line 66, in _login
    return self._auth_obj.login(token, store_token, reenter_token)
  File "/home/siegfried/anaconda3/envs/eureka/lib/python3.9/site-packages/astroquery-0.4.7.dev8076-py3.9.egg/astroquery/mast/auth.py", line 67, in login
    token = keyring.get_password("astroquery:mast.stsci.edu.token", "masttoken")
  File "/home/siegfried/anaconda3/envs/eureka/lib/python3.9/site-packages/keyring-23.11.0-py3.9.egg/keyring/core.py", line 55, in get_password
    return get_keyring().get_password(service_name, username)
  File "/home/siegfried/anaconda3/envs/eureka/lib/python3.9/site-packages/keyring-23.11.0-py3.9.egg/keyring/backends/fail.py", line 25, in get_password
    raise NoKeyringError(msg)
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.

**Comment by svaverbe** [comment]
All issues solved after downloading the keyring-alt package.  I have downloaded data for WASP-96b and WASP-39b.  I will close the thread here.
