### ISSUE TITLE
'MetaClass' object has no attribute 'isplots'

### ISSUE THREAD

**Issue by amitmazz** [kevin218/Eureka#515]
### Instrument

NIRSpec (Stages 1-3)

### What happened?

I was running stage 1 using the ecf file S1_nirx_template.ecf. The source is  wasp39-b and I had the nrs1 data. It stopped at an a error which I fixed. Later I am getting the following thing:

Starting Stage 1 Processing
Input directory: /home/amit/Eureka_files/JWST/uncalibrated/
Output directory: /home/amit/Eureka_files/JWST/Stage1/S1_2023-04-04_nirspec_fs_template_run3/
Copying S1 control file

Found 4 data file(s) ending in uncal.fits
Starting file 1 of 4: jw01366004001_04101_00001-seg001_nrs1_uncal.fits
2023-04-04 00:09:41,328 - stpipe.EurekaS1Pipeline - INFO - EurekaS1Pipeline instance created.
2023-04-04 00:09:41,328 - stpipe.EurekaS1Pipeline.group_scale - INFO - GroupScaleStep instance created.
2023-04-04 00:09:41,329 - stpipe.EurekaS1Pipeline.dq_init - INFO - DQInitStep instance created.
2023-04-04 00:09:41,330 - stpipe.EurekaS1Pipeline.saturation - INFO - SaturationStep instance created.
2023-04-04 00:09:41,330 - stpipe.EurekaS1Pipeline.ipc - INFO - IPCStep instance created.
2023-04-04 00:09:41,331 - stpipe.EurekaS1Pipeline.superbias - INFO - SuperBiasStep instance created.
2023-04-04 00:09:41,332 - stpipe.EurekaS1Pipeline.refpix - INFO - RefPixStep instance created.
2023-04-04 00:09:41,332 - stpipe.EurekaS1Pipeline.rscd - INFO - RscdStep instance created.
2023-04-04 00:09:41,333 - stpipe.EurekaS1Pipeline.firstframe - INFO - FirstFrameStep instance created.
2023-04-04 00:09:41,334 - stpipe.EurekaS1Pipeline.lastframe - INFO - LastFrameStep instance created.
2023-04-04 00:09:41,334 - stpipe.EurekaS1Pipeline.linearity - INFO - LinearityStep instance created.
2023-04-04 00:09:41,335 - stpipe.EurekaS1Pipeline.dark_current - INFO - DarkCurrentStep instance created.
2023-04-04 00:09:41,335 - stpipe.EurekaS1Pipeline.reset - INFO - ResetStep instance created.
2023-04-04 00:09:41,336 - stpipe.EurekaS1Pipeline.persistence - INFO - PersistenceStep instance created.
2023-04-04 00:09:41,337 - stpipe.EurekaS1Pipeline.jump - INFO - JumpStep instance created.
2023-04-04 00:09:41,338 - stpipe.EurekaS1Pipeline.ramp_fit - INFO - RampFitStep instance created.
2023-04-04 00:09:41,338 - stpipe.EurekaS1Pipeline.gain_scale - INFO - GainScaleStep instance created.
2023-04-04 00:09:41,340 - stpipe.Eureka_RampFitStep - INFO - Eureka_RampFitStep instance created.
2023-04-04 00:09:41,486 - stpipe.EurekaS1Pipeline - INFO - Step EurekaS1Pipeline running with args ('/home/amit/Eureka_files/JWST/uncalibrated/jw01366004001_04101_00001-seg001_nrs1_uncal.fits',).
2023-04-04 00:09:41,494 - stpipe.EurekaS1Pipeline - INFO - Step EurekaS1Pipeline parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': '/home/amit/Eureka_files/JWST/Stage1/S1_2023-04-04_nirspec_fs_template_run3/', 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': True, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'save_calibrated_ramp': False, 'steps': {'group_scale': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'dq_init': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'saturation': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'n_pix_grow_sat': 1}, 'ipc': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'superbias': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'refpix': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'odd_even_columns': True, 'use_side_ref_pixels': True, 'side_smoothing_length': 11, 'side_gain': 1.0, 'odd_even_rows': True}, 'rscd': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'type': 'baseline'}, 'firstframe': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'lastframe': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'linearity': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'dark_current': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'dark_output': None}, 'reset': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'persistence': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'input_trapsfilled': '', 'flag_pers_cutoff': 40.0, 'save_persistence': False, 'save_trapsfilled': True}, 'jump': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'rejection_threshold': 4.0, 'three_group_rejection_threshold': 6.0, 'four_group_rejection_threshold': 5.0, 'maximum_cores': 'none', 'flag_4_neighbors': True, 'max_jump_to_flag_neighbors': 1000.0, 'min_jump_to_flag_neighbors': 10.0}, 'ramp_fit': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'int_name': '', 'save_opt': False, 'opt_name': '', 'maximum_cores': 'none'}, 'gain_scale': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}}}
2023-04-04 00:09:42,650 - stpipe.EurekaS1Pipeline - INFO - Prefetching reference files for dataset: 'jw01366004001_04101_00001-seg001_nrs1_uncal.fits' reftypes = ['dark', 'gain', 'linearity', 'mask', 'readnoise', 'refpix', 'reset', 'rscd', 'saturation', 'superbias']
2023-04-04 00:09:45,075 - stpipe.EurekaS1Pipeline - INFO - Prefetch for DARK reference file is '/home/amit/Eureka_files_2/temp/crds_cache/references/jwst/nirspec/jwst_nirspec_dark_0322.fits'.
2023-04-04 00:09:45,076 - stpipe.EurekaS1Pipeline - INFO - Prefetch for GAIN reference file is '/home/amit/Eureka_files_2/temp/crds_cache/references/jwst/nirspec/jwst_nirspec_gain_0027.fits'.
2023-04-04 00:09:45,076 - stpipe.EurekaS1Pipeline - INFO - Prefetch for LINEARITY reference file is '/home/amit/Eureka_files_2/temp/crds_cache/references/jwst/nirspec/jwst_nirspec_linearity_0024.fits'.
2023-04-04 00:09:45,076 - stpipe.EurekaS1Pipeline - INFO - Prefetch for MASK reference file is '/home/amit/Eureka_files_2/temp/crds_cache/references/jwst/nirspec/jwst_nirspec_mask_0035.fits'.
2023-04-04 00:09:45,076 - stpipe.EurekaS1Pipeline - INFO - Prefetch for READNOISE reference file is '/home/amit/Eureka_files_2/temp/crds_cache/references/jwst/nirspec/jwst_nirspec_readnoise_0036.fits'.
2023-04-04 00:09:45,076 - stpipe.EurekaS1Pipeline - INFO - Prefetch for REFPIX reference file is 'N/A'.
2023-04-04 00:09:45,076 - stpipe.EurekaS1Pipeline - INFO - Prefetch for RESET reference file is 'N/A'.
2023-04-04 00:09:45,076 - stpipe.EurekaS1Pipeline - INFO - Prefetch for RSCD reference file is 'N/A'.
2023-04-04 00:09:45,076 - stpipe.EurekaS1Pipeline - INFO - Prefetch for SATURATION reference file is '/home/amit/Eureka_files_2/temp/crds_cache/references/jwst/nirspec/jwst_nirspec_saturation_0029.fits'.
2023-04-04 00:09:45,076 - stpipe.EurekaS1Pipeline - INFO - Prefetch for SUPERBIAS reference file is '/home/amit/Eureka_files_2/temp/crds_cache/references/jwst/nirspec/jwst_nirspec_superbias_0304.fits'.
2023-04-04 00:09:45,077 - stpipe.EurekaS1Pipeline - INFO - Starting calwebb_detector1 ...
2023-04-04 00:09:46,370 - stpipe.EurekaS1Pipeline.group_scale - INFO - Step group_scale running with args (<RampModel(6100, 5, 32, 512) from jw01366004001_04101_00001-seg001_nrs1_uncal.fits>,).
2023-04-04 00:09:46,371 - stpipe.EurekaS1Pipeline.group_scale - INFO - Step group_scale parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '/home/amit/Eureka_files/JWST/uncalibrated'}
2023-04-04 00:09:46,900 - stpipe.EurekaS1Pipeline.group_scale - INFO - NFRAMES and FRMDIVSR are equal; correction not needed
2023-04-04 00:09:46,900 - stpipe.EurekaS1Pipeline.group_scale - INFO - Step will be skipped
2023-04-04 00:09:46,902 - stpipe.EurekaS1Pipeline.group_scale - INFO - Step group_scale done
2023-04-04 00:09:47,019 - stpipe.EurekaS1Pipeline.dq_init - INFO - Step dq_init running with args (<RampModel(6100, 5, 32, 512) from jw01366004001_04101_00001-seg001_nrs1_uncal.fits>,).
2023-04-04 00:09:47,020 - stpipe.EurekaS1Pipeline.dq_init - INFO - Step dq_init parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '/home/amit/Eureka_files/JWST/uncalibrated'}
2023-04-04 00:09:47,039 - stpipe.EurekaS1Pipeline.dq_init - INFO - Using MASK reference file /home/amit/Eureka_files_2/temp/crds_cache/references/jwst/nirspec/jwst_nirspec_mask_0035.fits
2023-04-04 00:09:47,689 - stpipe.EurekaS1Pipeline.dq_init - INFO - Extracting mask subarray to match science data
2023-04-04 00:09:47,702 - stpipe.EurekaS1Pipeline.dq_init - INFO - Step dq_init done
2023-04-04 00:09:47,820 - stpipe.EurekaS1Pipeline.saturation - INFO - Step saturation running with args (<RampModel(6100, 5, 32, 512) from jw01366004001_04101_00001-seg001_nrs1_uncal.fits>,).
2023-04-04 00:09:47,820 - stpipe.EurekaS1Pipeline.saturation - INFO - Step saturation parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '/home/amit/Eureka_files/JWST/uncalibrated', 'n_pix_grow_sat': 1}
2023-04-04 00:09:47,840 - stpipe.EurekaS1Pipeline.saturation - INFO - Using SATURATION reference file /home/amit/Eureka_files_2/temp/crds_cache/references/jwst/nirspec/jwst_nirspec_saturation_0029.fits
2023-04-04 00:09:48,396 - stpipe.EurekaS1Pipeline.saturation - INFO - Extracting reference file subarray to match science data
2023-04-04 00:09:59,853 - stpipe.EurekaS1Pipeline.saturation - INFO - Detected 705 saturated pixels
2023-04-04 00:09:59,971 - stpipe.EurekaS1Pipeline.saturation - INFO - Detected 0 A/D floor pixels
2023-04-04 00:09:59,979 - stpipe.EurekaS1Pipeline.saturation - INFO - Step saturation done
2023-04-04 00:10:00,217 - stpipe.EurekaS1Pipeline.ipc - INFO - Step ipc running with args (<RampModel(6100, 5, 32, 512) from jw01366004001_04101_00001-seg001_nrs1_uncal.fits>,).
2023-04-04 00:10:00,218 - stpipe.EurekaS1Pipeline.ipc - INFO - Step ipc parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '/home/amit/Eureka_files/JWST/uncalibrated'}
2023-04-04 00:10:00,218 - stpipe.EurekaS1Pipeline.ipc - INFO - Step skipped.
2023-04-04 00:10:00,221 - stpipe.EurekaS1Pipeline.ipc - INFO - Step ipc done
2023-04-04 00:10:00,504 - stpipe.EurekaS1Pipeline.superbias - INFO - Step superbias running with args (<RampModel(6100, 5, 32, 512) from jw01366004001_04101_00001-seg001_nrs1_uncal.fits>,).
2023-04-04 00:10:00,505 - stpipe.EurekaS1Pipeline.superbias - INFO - Step superbias parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '/home/amit/Eureka_files/JWST/uncalibrated'}
2023-04-04 00:10:00,532 - stpipe.EurekaS1Pipeline.superbias - INFO - Using SUPERBIAS reference file /home/amit/Eureka_files_2/temp/crds_cache/references/jwst/nirspec/jwst_nirspec_superbias_0304.fits
2023-04-04 00:10:01,493 - stpipe.EurekaS1Pipeline.superbias - INFO - Step superbias done
2023-04-04 00:10:01,832 - stpipe.EurekaS1Pipeline.refpix - INFO - Step refpix running with args (<RampModel(6100, 5, 32, 512) from jw01366004001_04101_00001-seg001_nrs1_uncal.fits>,).
2023-04-04 00:10:01,833 - stpipe.EurekaS1Pipeline.refpix - INFO - Step refpix parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '/home/amit/Eureka_files/JWST/uncalibrated', 'odd_even_columns': True, 'use_side_ref_pixels': True, 'side_smoothing_length': 11, 'side_gain': 1.0, 'odd_even_rows': True}
2023-04-04 00:10:02,368 - stpipe.EurekaS1Pipeline.refpix - INFO - NIR subarray data
2023-04-04 00:10:02,370 - stpipe.EurekaS1Pipeline.refpix - INFO - Single readout amplifier used
2023-04-04 00:10:02,370 - stpipe.EurekaS1Pipeline.refpix - INFO - No valid reference pixels.  This step wil have no effect
2023-04-04 00:10:02,390 - stpipe.EurekaS1Pipeline.refpix - INFO - Step refpix done
2023-04-04 00:10:02,676 - stpipe.EurekaS1Pipeline.linearity - INFO - Step linearity running with args (<RampModel(6100, 5, 32, 512) from jw01366004001_04101_00001-seg001_nrs1_uncal.fits>,).
2023-04-04 00:10:02,677 - stpipe.EurekaS1Pipeline.linearity - INFO - Step linearity parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '/home/amit/Eureka_files/JWST/uncalibrated'}
2023-04-04 00:10:02,698 - stpipe.EurekaS1Pipeline.linearity - INFO - Using Linearity reference file /home/amit/Eureka_files_2/temp/crds_cache/references/jwst/nirspec/jwst_nirspec_linearity_0024.fits
2023-04-04 00:10:02,747 - stpipe.EurekaS1Pipeline.linearity - WARNING - Keyword BAD_LIN_CORR does not correspond to an existing DQ mnemonic, so will be ignored
2023-04-04 00:10:06,340 - stpipe.EurekaS1Pipeline.linearity - INFO - Step linearity done
2023-04-04 00:10:06,502 - stpipe.EurekaS1Pipeline.dark_current - INFO - Step dark_current running with args (<RampModel(6100, 5, 32, 512) from jw01366004001_04101_00001-seg001_nrs1_uncal.fits>,).
2023-04-04 00:10:06,503 - stpipe.EurekaS1Pipeline.dark_current - INFO - Step dark_current parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': '/home/amit/Eureka_files/JWST/Stage1/S1_2023-04-04_nirspec_fs_template_run3/', 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '/home/amit/Eureka_files/JWST/uncalibrated', 'dark_output': None}
2023-04-04 00:10:06,522 - stpipe.EurekaS1Pipeline.dark_current - INFO - Using DARK reference file /home/amit/Eureka_files_2/temp/crds_cache/references/jwst/nirspec/jwst_nirspec_dark_0322.fits
2023-04-04 00:10:06,572 - stpipe.EurekaS1Pipeline.dark_current - INFO - Science data nints=6100, ngroups=5, nframes=1, groupgap=0
2023-04-04 00:10:06,573 - stpipe.EurekaS1Pipeline.dark_current - INFO - Dark data nints=1, ngroups=30, nframes=1, groupgap=0
2023-04-04 00:10:08,058 - stpipe.EurekaS1Pipeline.dark_current - INFO - Step dark_current done
2023-04-04 00:10:08,201 - stpipe.EurekaS1Pipeline.jump - INFO - Step jump running with args (<RampModel(6100, 5, 32, 512) from jw01366004001_04101_00001-seg001_nrs1_uncal.fits>,).
2023-04-04 00:10:08,202 - stpipe.EurekaS1Pipeline.jump - INFO - Step jump parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '/home/amit/Eureka_files/JWST/uncalibrated', 'rejection_threshold': 4.0, 'three_group_rejection_threshold': 6.0, 'four_group_rejection_threshold': 5.0, 'maximum_cores': 'none', 'flag_4_neighbors': True, 'max_jump_to_flag_neighbors': 1000.0, 'min_jump_to_flag_neighbors': 10.0}
2023-04-04 00:10:08,202 - stpipe.EurekaS1Pipeline.jump - INFO - Step skipped.
2023-04-04 00:10:08,204 - stpipe.EurekaS1Pipeline.jump - INFO - Step jump done
2023-04-04 00:10:08,325 - stpipe.Eureka_RampFitStep - INFO - Step Eureka_RampFitStep running with args (<RampModel(6100, 5, 32, 512) from jw01366004001_04101_00001-seg001_nrs1_uncal.fits>,).
2023-04-04 00:10:08,326 - stpipe.Eureka_RampFitStep - INFO - Step Eureka_RampFitStep parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': '/home/amit/Eureka_files/JWST/Stage1/S1_2023-04-04_nirspec_fs_template_run3/', 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'int_name': '', 'save_opt': False, 'opt_name': '', 'maximum_cores': 'none'}
  Masking Curved Trace.
  Running Group Level Background Subtraction.
  Performing background subtraction...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6100/6100 [00:08<00:00, 695.30it/s]
  Performing background subtraction...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6100/6100 [00:08<00:00, 688.23it/s]
  Performing background subtraction...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6100/6100 [00:08<00:00, 687.75it/s]
  Performing background subtraction...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6100/6100 [00:08<00:00, 691.51it/s]
Traceback (most recent call last):
  File "/home/amit/Eureka_files/JWST/run_eureka.py", line 21, in <module>
    s1_meta = s1.rampfitJWST(eventlabel, ecf_path=ecf_path)
  File "/home/amit/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S1_detector_processing/s1_process.py", line 108, in rampfitJWST
    EurekaS1Pipeline().run_eurekaS1(filename, meta, log)
  File "/home/amit/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S1_detector_processing/s1_process.py", line 221, in run_eurekaS1
    self(filename)
  File "/home/amit/anaconda3/envs/eureka/lib/python3.9/site-packages/stpipe/step.py", line 454, in run
    step_result = self.process(*args)
  File "/home/amit/anaconda3/envs/eureka/lib/python3.9/site-packages/jwst/pipeline/calwebb_detector1.py", line 134, in process
    input, ints_model = self.ramp_fit(input)
  File "/home/amit/anaconda3/envs/eureka/lib/python3.9/site-packages/stpipe/step.py", line 454, in run
    step_result = self.process(*args)
  File "/home/amit/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S1_detector_processing/ramp_fitting.py", line 113, in process
    input_model = group_level.GLBS(input_model,
  File "/home/amit/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S1_detector_processing/group_level.py", line 67, in GLBS
    meta.isplots)
AttributeError: 'MetaClass' object has no attribute 'isplots'

### Error traceback output

Traceback (most recent call last):
  File "/home/amit/Eureka_files/JWST/run_eureka.py", line 21, in <module>
    s1_meta = s1.rampfitJWST(eventlabel, ecf_path=ecf_path)
  File "/home/amit/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S1_detector_processing/s1_process.py", line 108, in rampfitJWST
    EurekaS1Pipeline().run_eurekaS1(filename, meta, log)
  File "/home/amit/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S1_detector_processing/s1_process.py", line 221, in run_eurekaS1
    self(filename)
  File "/home/amit/anaconda3/envs/eureka/lib/python3.9/site-packages/stpipe/step.py", line 454, in run
    step_result = self.process(*args)
  File "/home/amit/anaconda3/envs/eureka/lib/python3.9/site-packages/jwst/pipeline/calwebb_detector1.py", line 134, in process
    input, ints_model = self.ramp_fit(input)
  File "/home/amit/anaconda3/envs/eureka/lib/python3.9/site-packages/stpipe/step.py", line 454, in run
    step_result = self.process(*args)
  File "/home/amit/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S1_detector_processing/ramp_fitting.py", line 113, in process
    input_model = group_level.GLBS(input_model,
  File "/home/amit/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S1_detector_processing/group_level.py", line 67, in GLBS
    meta.isplots)
AttributeError: 'MetaClass' object has no attribute 'isplots'

### What operating system are you using?

Linux-Ubuntu

### What version of Python are you running?

python 3.9.13

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kevin218** [comment]
Can you make sure you're using the latest version of Eureka!? The latest version doesn't use meta.isplots in Stage 1.

**Comment by taylorbell57** [comment]
This error message is a new issue, and you've already opened a different issue about this on GitHub, so I'm going to mark this original issue as resolved here
