### ISSUE TITLE
Having a problem with v0.9 installation.

### ISSUE THREAD

**Issue by cdfortenbach** [kevin218/Eureka#523]
### Instrument

NIRSpec (Stages 1-3)

### What happened?

I was previously able to cleanly install Eureka v0.9 on a machine with Ubuntu 18.04, but now I need to install it on an AWS instance, with Amazon Linux 2, and I'm having problems.  I had v0.8 installed previously on the AWS instance successfully, so I don't think it's an AWS/OS issue.  It seems to be failing in the "pip install -e '.[jwst]'" step, specifically at "Building editable for eureka (pyproject.toml) . . . ".  I tried the 'pip only' installation too, but got the same result.  I tried updating the setuptools pkg, but that didn't solve the problem.  Any thoughts would be appreciated.

### Error traceback output

(eureka) [ec2-user@ip-172-31-4-143 Eureka]$ pip install -e '.[jwst]'
Obtaining file:///home/ec2-user/Eureka
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting astraeus@ git+https://github.com/kevin218/Astraeus@main
  Cloning https://github.com/kevin218/Astraeus (to revision main) to /tmp/pip-install-nfyhsygq/astraeus_40b239fc031a4c6da1c3b54ebc0add71
  Running command git clone --filter=blob:none --quiet https://github.com/kevin218/Astraeus /tmp/pip-install-nfyhsygq/astraeus_40b239fc031a4c6da1c3b54ebc0add71
  Resolved https://github.com/kevin218/Astraeus to commit 14c2e434e6f40185cf64978c745f1de796f1ace5
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting celerite
  Using cached celerite-0.4.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (295 kB)
Collecting photutils
  Using cached photutils-1.7.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (855 kB)
Collecting numpy<=1.22,>=1.20.0
  Using cached numpy-1.22.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Collecting george
  Using cached george-0.4.0-cp39-cp39-manylinux2014_x86_64.whl (404 kB)
Collecting pandas
  Using cached pandas-2.0.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
Collecting crds
  Using cached crds-11.16.22-py3-none-any.whl (1.2 MB)
Collecting cython
  Using cached Cython-0.29.34-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (2.0 MB)
Collecting h5py<3.2
  Using cached h5py-3.1.0-cp39-cp39-manylinux1_x86_64.whl (4.4 MB)
Collecting corner
  Using cached corner-2.2.2-py3-none-any.whl (15 kB)
Collecting ccdproc
  Using cached ccdproc-2.4.0-py3-none-any.whl (355 kB)
Collecting scipy>=1.4.0
  Using cached scipy-1.10.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
Collecting batman-package
  Using cached batman_package-2.4.9-cp39-cp39-linux_x86_64.whl
Collecting gwcs
  Using cached gwcs-0.18.3-py3-none-any.whl (108 kB)
Collecting bokeh<3.0
  Using cached bokeh-2.4.3-py3-none-any.whl (18.5 MB)
Collecting matplotlib
  Using cached matplotlib-3.7.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
Collecting jsonschema<4.10.0
  Using cached jsonschema-4.9.1-py3-none-any.whl (79 kB)
Collecting astropy
  Using cached astropy-5.2.2-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (11.2 MB)
Collecting dask<2022.6.1
  Using cached dask-2022.6.0-py3-none-any.whl (1.1 MB)
Collecting stdatamodels
  Using cached stdatamodels-1.3.1-py3-none-any.whl (297 kB)
Requirement already satisfied: setuptools-scm in /home/ec2-user/efs-mount-point/anaconda3/envs/eureka/lib/python3.9/site-packages (from eureka==0.9) (7.1.0)
Collecting emcee>3.0.0
  Using cached emcee-3.1.4-py2.py3-none-any.whl (46 kB)
Collecting dynesty>1.0
  Using cached dynesty-2.1.1-py2.py3-none-any.whl (106 kB)
Collecting astroquery
  Using cached astroquery-0.4.6-py3-none-any.whl (4.5 MB)
Collecting svo-filters
  Using cached svo_filters-0.4.4-py2.py3-none-any.whl (1.4 MB)
Collecting exotic-ld
  Using cached exotic_ld-3.0.0-py3-none-any.whl
Collecting tqdm
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting lmfit
  Using cached lmfit-1.2.0-py3-none-any.whl (93 kB)
Collecting stcal>=1.0.0
  Using cached stcal-1.3.5-py3-none-any.whl (83 kB)
Collecting asdf
  Using cached asdf-2.15.0-py3-none-any.whl (431 kB)
Collecting jwst==1.8.2
  Using cached jwst-1.8.2-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.0 MB)
Collecting requests>=2.22
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting drizzle>=1.13.6
  Using cached drizzle-1.13.7-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (298 kB)
Collecting wiimatch>=0.2.1
  Using cached wiimatch-0.3.1-py3-none-any.whl (17 kB)
Collecting asdf-astropy>=0.2.2
  Using cached asdf_astropy-0.4.0-py3-none-any.whl (73 kB)
Collecting stpipe<1.0,>=0.4.2
  Using cached stpipe-0.4.6-py3-none-any.whl (81 kB)
Collecting BayesicFitting>=3.0.1
  Using cached BayesicFitting-3.1.1-py3-none-any.whl (5.6 MB)
Collecting poppy>=1.0.2
  Using cached poppy-1.0.3-py3-none-any.whl (2.8 MB)
Collecting stcal>=1.0.0
  Using cached stcal-1.2.2-py3-none-any.whl (81 kB)
Collecting stdatamodels
  Using cached stdatamodels-0.4.5-py3-none-any.whl (35 kB)
Collecting stsci.imagestats>=1.6.3
  Using cached stsci.imagestats-1.6.3-cp39-cp39-linux_x86_64.whl
Collecting tweakwcs>=0.8.0
  Using cached tweakwcs-0.8.2-py3-none-any.whl (83 kB)
Collecting stsci.image>=2.3.5
  Using cached stsci.image-2.3.5-cp39-cp39-linux_x86_64.whl
Collecting spherical-geometry>=1.2.22
  Using cached spherical_geometry-1.2.23-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (946 kB)
Collecting scikit-image>=0.17.2
  Using cached scikit_image-0.20.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.2 MB)
Collecting certifi==2022.5.18.1
  Using cached certifi-2022.5.18.1-py3-none-any.whl (155 kB)
Collecting pyparsing>=2.2.1
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting psutil>=5.7.2
  Using cached psutil-5.9.5-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (282 kB)
Requirement already satisfied: packaging>=19 in /home/ec2-user/efs-mount-point/anaconda3/envs/eureka/lib/python3.9/site-packages (from asdf->eureka==0.9) (23.1)
Collecting importlib-metadata>=4.11.4
  Using cached importlib_metadata-6.5.0-py3-none-any.whl (22 kB)
Collecting pyyaml>=5.4.1
  Using cached PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (661 kB)
Collecting semantic-version>=2.8
  Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Collecting asdf-transform-schemas>=0.3
  Using cached asdf_transform_schemas-0.3.0-py3-none-any.whl (195 kB)
Collecting asdf-standard>=1.0.1
  Using cached asdf_standard-1.0.3-py3-none-any.whl (71 kB)
Collecting jmespath>=0.6.2
  Using cached jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting asdf-unit-schemas>=0.1
  Using cached asdf_unit_schemas-0.1.0-py3-none-any.whl (11 kB)
Collecting pyerfa>=2.0
  Using cached pyerfa-2.0.0.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (741 kB)
Collecting pillow>=7.1.0
  Using cached Pillow-9.5.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Requirement already satisfied: typing-extensions>=3.10.0 in /home/ec2-user/efs-mount-point/anaconda3/envs/eureka/lib/python3.9/site-packages (from bokeh<3.0->eureka==0.9) (4.5.0)
Collecting Jinja2>=2.9
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting tornado>=5.1
  Using cached tornado-6.3-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (426 kB)
Collecting filelock
  Using cached filelock-3.12.0-py3-none-any.whl (10 kB)
Collecting parsley
  Using cached Parsley-1.3-py2.py3-none-any.whl (88 kB)
Collecting partd>=0.3.10
  Using cached partd-1.4.0-py3-none-any.whl (18 kB)
Collecting toolz>=0.8.2
  Using cached toolz-0.12.0-py3-none-any.whl (55 kB)
Collecting cloudpickle>=1.1.1
  Using cached cloudpickle-2.2.1-py3-none-any.whl (25 kB)
Collecting fsspec>=0.6.0
  Using cached fsspec-2023.4.0-py3-none-any.whl (153 kB)
Collecting asdf-wcs-schemas
  Using cached asdf_wcs_schemas-0.1.1-py3-none-any.whl
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Using cached pyrsistent-0.19.3-py3-none-any.whl (57 kB)
Collecting attrs>=17.4.0
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting h5netcdf
  Using cached h5netcdf-1.1.0-py2.py3-none-any.whl (26 kB)
Collecting bottleneck
  Using cached Bottleneck-1.3.7-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (353 kB)
Collecting netCDF4
  Using cached netCDF4-1.6.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.2 MB)
Collecting xarray
  Using cached xarray-2023.4.1-py3-none-any.whl (977 kB)
Collecting beautifulsoup4>=4.3.2
  Using cached beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
Collecting keyring>=4.0
  Using cached keyring-23.13.1-py3-none-any.whl (37 kB)
Collecting pyvo>=1.1
  Using cached pyvo-1.4.1-py3-none-any.whl (887 kB)
Collecting html5lib>=0.999
  Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Collecting astroscrappy>=1.0.8
  Using cached astroscrappy-1.1.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.3 MB)
Collecting reproject>=0.7
  Using cached reproject-0.10.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.5 MB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.4.4-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
Collecting contourpy>=1.0.1
  Using cached contourpy-1.0.7-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (299 kB)
Collecting importlib-resources>=3.2.0
  Using cached importlib_resources-5.12.0-py3-none-any.whl (36 kB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.39.3-py3-none-any.whl (1.0 MB)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting asteval>=0.9.28
  Using cached asteval-0.9.29-py3-none-any.whl (18 kB)
Collecting uncertainties>=3.1.4
  Using cached uncertainties-3.1.7-py2.py3-none-any.whl (98 kB)
Collecting pytz>=2020.1
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
Collecting tzdata>=2022.1
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Requirement already satisfied: tomli>=1.0.0 in /home/ec2-user/efs-mount-point/anaconda3/envs/eureka/lib/python3.9/site-packages (from setuptools-scm->eureka==0.9) (2.0.1)
Requirement already satisfied: setuptools in /home/ec2-user/efs-mount-point/anaconda3/envs/eureka/lib/python3.9/site-packages (from setuptools-scm->eureka==0.9) (66.0.0)
Collecting pytest
  Using cached pytest-7.3.1-py3-none-any.whl (320 kB)
Collecting pysynphot
  Using cached pysynphot-2.0.0-cp39-cp39-linux_x86_64.whl
Collecting numpydoc
  Using cached numpydoc-1.5.0-py3-none-any.whl (52 kB)
Collecting ipython
  Using cached ipython-8.12.0-py3-none-any.whl (796 kB)
Collecting asdf-coordinates-schemas>=0.1
  Using cached asdf_coordinates_schemas-0.2.0-py3-none-any.whl (19 kB)
Collecting future
  Using cached future-0.18.3-py3-none-any.whl
Collecting soupsieve>1.2
  Using cached soupsieve-2.4.1-py3-none-any.whl (36 kB)
Collecting six>=1.9
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting webencodings
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting zipp>=0.5
  Using cached zipp-3.15.0-py3-none-any.whl (6.8 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting jeepney>=0.4.2
  Using cached jeepney-0.8.0-py3-none-any.whl (48 kB)
Collecting SecretStorage>=3.2
  Using cached SecretStorage-3.3.3-py3-none-any.whl (15 kB)
Collecting jaraco.classes
  Using cached jaraco.classes-3.2.3-py3-none-any.whl (6.0 kB)
Collecting locket
  Using cached locket-1.0.0-py2.py3-none-any.whl (4.4 kB)
Collecting astropy-healpix>=0.6
  Using cached astropy_healpix-0.7-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (197 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
Collecting scipy>=1.4.0
  Using cached scipy-1.9.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.9 MB)
Collecting lazy_loader>=0.1
  Using cached lazy_loader-0.2-py3-none-any.whl (8.6 kB)
Collecting tifffile>=2019.7.26
  Using cached tifffile-2023.4.12-py3-none-any.whl (219 kB)
Collecting networkx>=2.8
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting imageio>=2.4.1
  Using cached imageio-2.27.0-py3-none-any.whl (3.4 MB)
Collecting PyWavelets>=1.1.1
  Using cached PyWavelets-1.4.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.9 MB)
Collecting stsci.stimage
  Using cached stsci.stimage-0.2.6-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (163 kB)
Collecting traitlets>=5
  Using cached traitlets-5.9.0-py3-none-any.whl (117 kB)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting jedi>=0.16
  Using cached jedi-0.18.2-py2.py3-none-any.whl (1.6 MB)
Collecting pexpect>4.3
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting matplotlib-inline
  Using cached matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting backcall
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting stack-data
  Using cached stack_data-0.6.2-py3-none-any.whl (24 kB)
Collecting prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30
  Using cached prompt_toolkit-3.0.38-py3-none-any.whl (385 kB)
Collecting pygments>=2.4.0
  Using cached Pygments-2.15.1-py3-none-any.whl (1.1 MB)
Collecting decorator
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting cftime
  Using cached cftime-1.6.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
Collecting sphinx>=4.2
  Using cached sphinx-6.1.3-py3-none-any.whl (3.0 MB)
Collecting iniconfig
  Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Collecting exceptiongroup>=1.0.0rc8
  Using cached exceptiongroup-1.1.1-py3-none-any.whl (14 kB)
Collecting pluggy<2.0,>=0.12
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting parso<0.9.0,>=0.8.0
  Using cached parso-0.8.3-py2.py3-none-any.whl (100 kB)
Collecting ptyprocess>=0.5
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.6-py2.py3-none-any.whl (29 kB)
Collecting cryptography>=2.0
  Using cached cryptography-40.0.2-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
Collecting sphinxcontrib-htmlhelp>=2.0.0
  Using cached sphinxcontrib_htmlhelp-2.0.1-py3-none-any.whl (99 kB)
Collecting sphinxcontrib-serializinghtml>=1.1.5
  Using cached sphinxcontrib_serializinghtml-1.1.5-py2.py3-none-any.whl (94 kB)
Collecting sphinxcontrib-devhelp
  Using cached sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl (84 kB)
Collecting docutils<0.20,>=0.18
  Using cached docutils-0.19-py3-none-any.whl (570 kB)
Collecting sphinxcontrib-applehelp
  Using cached sphinxcontrib_applehelp-1.0.4-py3-none-any.whl (120 kB)
Collecting alabaster<0.8,>=0.7
  Using cached alabaster-0.7.13-py3-none-any.whl (13 kB)
Collecting sphinxcontrib-qthelp
  Using cached sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl (90 kB)
Collecting snowballstemmer>=2.0
  Using cached snowballstemmer-2.2.0-py2.py3-none-any.whl (93 kB)
Collecting sphinxcontrib-jsmath
  Using cached sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Collecting imagesize>=1.3
  Using cached imagesize-1.4.1-py2.py3-none-any.whl (8.8 kB)
Collecting babel>=2.9
  Using cached Babel-2.12.1-py3-none-any.whl (10.1 MB)
Collecting more-itertools
  Using cached more_itertools-9.1.0-py3-none-any.whl (54 kB)
Collecting pure-eval
  Using cached pure_eval-0.2.2-py3-none-any.whl (11 kB)
Collecting executing>=1.2.0
  Using cached executing-1.2.0-py2.py3-none-any.whl (24 kB)
Collecting asttokens>=2.1.0
  Using cached asttokens-2.2.1-py2.py3-none-any.whl (26 kB)
Collecting cffi>=1.12
  Using cached cffi-1.15.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Building wheels for collected packages: astraeus, eureka
  Building wheel for astraeus (pyproject.toml) ... done
  Created wheel for astraeus: filename=Astraeus-0.3-py3-none-any.whl size=6634 sha256=3596b9d718e298dfae7665b21f585b39650de283d4551b17cf6137a8778daaa7
  Stored in directory: /tmp/pip-ephem-wheel-cache-jzc3ndbs/wheels/5a/d6/c3/6414a9e1e1e4184e28601c312ba96ebda3b034f0c61bb5e7bc
  Building editable for eureka (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building editable for eureka (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [102 lines of output]
      /tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/config/setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running editable_wheel
      creating /tmp/pip-wheel-ba1a4lw_/.tmp-b3253gjf/eureka.egg-info
      writing /tmp/pip-wheel-ba1a4lw_/.tmp-b3253gjf/eureka.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-wheel-ba1a4lw_/.tmp-b3253gjf/eureka.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-wheel-ba1a4lw_/.tmp-b3253gjf/eureka.egg-info/requires.txt
      writing top-level names to /tmp/pip-wheel-ba1a4lw_/.tmp-b3253gjf/eureka.egg-info/top_level.txt
      writing manifest file '/tmp/pip-wheel-ba1a4lw_/.tmp-b3253gjf/eureka.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-wheel-ba1a4lw_/.tmp-b3253gjf/eureka.egg-info/SOURCES.txt'
      creating '/tmp/pip-wheel-ba1a4lw_/.tmp-b3253gjf/eureka-0.9.dist-info'
      creating /tmp/pip-wheel-ba1a4lw_/.tmp-b3253gjf/eureka-0.9.dist-info/WHEEL
      running build_py
      running build_ext
      building 'eureka.S3_data_reduction.niriss_cython' extension
      creating /tmp/tmpocjuel6a.build-temp/src
      creating /tmp/tmpocjuel6a.build-temp/src/eureka
      creating /tmp/tmpocjuel6a.build-temp/src/eureka/S3_data_reduction
      gcc -pthread -B /home/ec2-user/efs-mount-point/anaconda3/envs/eureka/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /home/ec2-user/efs-mount-point/anaconda3/envs/eureka/include -I/home/ec2-user/efs-mount-point/anaconda3/envs/eureka/include -fPIC -O2 -isystem /home/ec2-user/efs-mount-point/anaconda3/envs/eureka/include -fPIC -I/home/ec2-user/efs-mount-point/anaconda3/envs/eureka/include/python3.9 -c src/eureka/S3_data_reduction/niriss_cython.c -o /tmp/tmpocjuel6a.build-temp/src/eureka/S3_data_reduction/niriss_cython.o
      Traceback (most recent call last):
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/_distutils/spawn.py", line 57, in spawn
          proc = subprocess.Popen(cmd, env=env)
        File "/home/ec2-user/efs-mount-point/anaconda3/envs/eureka/lib/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/home/ec2-user/efs-mount-point/anaconda3/envs/eureka/lib/python3.9/subprocess.py", line 1821, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'gcc'
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 185, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/_distutils/spawn.py", line 63, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command 'gcc' failed: No such file or directory
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 147, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 328, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 259, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py", line 286, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py", line 600, in compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 187, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command 'gcc' failed: No such file or directory
      /tmp/pip-build-env-l0k669of/overlay/lib/python3.9/site-packages/setuptools/command/editable_wheel.py:151: _DebuggingTips: An error happened while installing 'eureka' in editable mode.
      
              ************************************************************************
              The following steps are recommended to help debugging this problem:
      
              - Try to install the project normally, without using the editable mode.
                Does the error still persists?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.
      
              After following the steps above, if the problem still persist and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:
      
                  https://github.com/pypa/setuptools/issues
      
              More information about editable installs can be found in the docs:
      
                  https://setuptools.pypa.io/en/latest/userguide/development_mode.html
              ************************************************************************
      
        _DebuggingTips.warn(project)
      error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for eureka
Successfully built astraeus
Failed to build eureka
ERROR: Could not build wheels for eureka, which is required to install pyproject.toml-based projects

### What operating system are you using?

Amazon Linux 2

### What version of Python are you running?

Python 3.9.7

### What Python packages do you have installed?

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
ca-certificates           2023.01.10           h06a4308_0  
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
ncurses                   6.4                  h6a678d5_0  
openssl                   1.1.1t               h7f8727e_0  
packaging                 23.1                     pypi_0    pypi
pip                       23.0.1           py39h06a4308_0  
python                    3.9.7                h12debd9_1  
readline                  8.2                  h5eee18b_0  
setuptools                66.0.0           py39h06a4308_0  
setuptools-scm            7.1.0                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1                    pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0  
wheel                     0.38.4           py39h06a4308_0  
xz                        5.2.10               h5eee18b_1  
zlib                      1.2.13               h5eee18b_0  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cdfortenbach** [comment]
Thanks!  This solved the problem.  I was able to complete the installation.  My apologies for missing this in your FAQ.  I thought I had read through it, but obviously missed this.
