### ISSUE TITLE
[Bug]: AttributeError: No attribute 'wcs'

### ISSUE THREAD

**Issue by taylorbell57** [kevin218/Eureka#569]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

NIRCam (Stages 1-3)

### What happened?

I'm currently unable to get Stage 2 to run for some new NIRCam data that I'm trying to work on, getting an error message that I've copied below. I've tried running Stage 2 on newer Stage 1 files (where I encountered this issue) and old Stage 1 files (where I know Stage 2 previously worked) from different datasets, and the result is the same either way, so the issue isn't with the particular dataset I'm using. I've also tried different choices of `tsgrism_extract_height` (`128`, `64`, `None`, or removed from the ECF) and `slit_y_low` and `slit_y_high` (removed from the ECF, or both set to `None`), and had no success either.

I don't have all the information about my old environment (got corrupted), but I do know that I was using jwst=1.8.3; CRDS=11.16.16; and pmap=1019 when Stage 2 previously worked for me on one specific dataset. Currently, I'm using jwst=1.10.2; CRDS=11.17.2; and pmap=1137 which is giving me this current issue. I've tried
- downgrading crds from 11.17.2 to 11.16.16 (while changing no other important packages) which didn't fix the problem, and
- downgrading jwst from 1.10.2 to 1.8.3 (which also changed stcal 1.3.8->1.2.2 and stdatamodels 1.3.1->0.4.5) which also didn't fix the problem.

I'm a bit at a loss as to what is causing this issue with the assign_wcs step (which then cascades down to the later steps), but I'm logging these details here and will circle back to try fixing this when I get the chance. If anyone else has encountered and overcode this issue, please let me know.

### Error traceback output

```
2023-10-16 17:49:27,794 - stpipe.EurekaSpec2Pipeline.assign_wcs - INFO - Step assign_wcs running with args (<CubeModel(190, 256, 2048) from jw01185002001_04103_00001-seg001_nrcalong_rateints.fits>,).
2023-10-16 17:49:27,796 - stpipe.EurekaSpec2Pipeline.assign_wcs - INFO - Step assign_wcs parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '/Volumes/DataDrive/WASP-80b_Transit_F322W2/Stage1/S1_2022-12-14_WASP80b_transit_F322W2_run1', 'sip_approx': True, 'sip_max_pix_error': 0.1, 'sip_degree': None, 'sip_max_inv_pix_error': 0.1, 'sip_inv_degree': None, 'sip_npoints': 12, 'slit_y_low': -0.55, 'slit_y_high': 0.55}
2023-10-16 17:49:28,176 - stpipe.EurekaSpec2Pipeline.assign_wcs - INFO - Added Barycentric velocity correction: 0.9999031902262419
2023-10-16 17:49:29,317 - stpipe.EurekaSpec2Pipeline.assign_wcs - WARNING - /Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/stdatamodels/validate.py:38: ValidationWarning: While validating wcs the following error occurred:
[<Polynomial2D(3, c0_0=-40.95308741, c1_0=0.03452866, c2_0=-0.00001798, c3_0=0., c0_1=0.00613772, c0_2=0.0000072, c0_3=-0., c1_1=-0.00001475, c1_2=0., c2_1=0.)>, <Polynomial2D(3, c0_0=36.1952759, c1_0=-0.06538841, c2_0=0.00003367, c3_0=-0.00000001, c0_1=-0.00570083, c0_2=-0.00001767, c0_3=0., c1_1=0.00002132, c1_2=0., c2_1=-0.00000001)>, <Polynomial2D(3, c0_0=-20.02206904, c1_0=0.03284551, c2_0=-0.0000166, c3_0=0., c0_1=-0.00243588, c0_2=0.00001326, c0_3=-0., c1_1=-0.00000786, c1_2=-0., c2_1=0.)>] is not of type 'object'

Failed validating 'type' in schema['allOf'][1]['properties']['ymodels']['items']:
    {'$schema': 'http://stsci.edu/schemas/yaml-schema/draft-01',
     'additionalProperties': True,
     'definitions': {'bound': {'anyOf': [{'type': 'number'},
                                         {'type': 'null'}]}},
     'description': 'These objects are designed to be nested in arbitrary '
                    'ways to build up transformation pipelines out of a '
                    'number of low-level pieces.\n',
     'examples': [['A transform with no bounding_box or '
                   'compound_bounding_box',
                   '!transform/transform-1.2.0\n'
                   '  name: test\n'
                   "  inputs: ['x', 'y']\n"
                   "  outputs: ['z']\n"
                   '  fixed:\n'
                   '    a: True\n'
                   '    b: False\n'
                   '  bounds:\n'
                   '    c: [-1, 2]\n'
                   '    d: [-3, null]\n'],
                  ['A transform with old-style 1D bounding_box',
                   '!transform/transform-1.2.0\n'
                   '  name: test\n'
                   "  inputs: ['x']\n"
                   "  outputs: ['y']\n"
                   '  bounding_box: [1.0, 2.0]\n'],
                  ['A transform with new-style 1D bounding_box',
                   '!transform/constant-1.4.0\n'
                   '  name: test\n'
                   '  value: 1\n'
      ...
  warnings.warn(errmsg, ValidationWarning)

2023-10-16 17:49:29,319 - stpipe.EurekaSpec2Pipeline.assign_wcs - INFO - COMPLETED assign_wcs
2023-10-16 17:49:29,341 - stpipe.EurekaSpec2Pipeline.assign_wcs - INFO - Step assign_wcs done
2023-10-16 17:49:29,453 - stpipe.EurekaSpec2Pipeline.imprint_subtract - INFO - Step imprint_subtract running with args (<CubeModel(190, 256, 2048) from jw01185002001_04103_00001-seg001_nrcalong_rateints.fits>, []).
2023-10-16 17:49:29,454 - stpipe.EurekaSpec2Pipeline.imprint_subtract - INFO - Step imprint_subtract parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '/Volumes/DataDrive/WASP-80b_Transit_F322W2/Stage1/S1_2022-12-14_WASP80b_transit_F322W2_run1'}
2023-10-16 17:49:29,454 - stpipe.EurekaSpec2Pipeline.imprint_subtract - INFO - Step skipped.
2023-10-16 17:49:29,458 - stpipe.EurekaSpec2Pipeline.imprint_subtract - INFO - Step imprint_subtract done
2023-10-16 17:49:29,560 - stpipe.EurekaSpec2Pipeline.bkg_subtract - INFO - Step bkg_subtract running with args (<CubeModel(190, 256, 2048) from jw01185002001_04103_00001-seg001_nrcalong_rateints.fits>, []).
2023-10-16 17:49:29,561 - stpipe.EurekaSpec2Pipeline.bkg_subtract - INFO - Step bkg_subtract parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '/Volumes/DataDrive/WASP-80b_Transit_F322W2/Stage1/S1_2022-12-14_WASP80b_transit_F322W2_run1', 'save_combined_background': False, 'sigma': 3.0, 'maxiters': None, 'wfss_mmag_extract': None}
2023-10-16 17:49:29,561 - stpipe.EurekaSpec2Pipeline.bkg_subtract - INFO - Step skipped.
2023-10-16 17:49:29,566 - stpipe.EurekaSpec2Pipeline.bkg_subtract - INFO - Step bkg_subtract done
2023-10-16 17:49:29,683 - stpipe.EurekaSpec2Pipeline.msa_flagging - INFO - Step msa_flagging running with args (<CubeModel(190, 256, 2048) from jw01185002001_04103_00001-seg001_nrcalong_rateints.fits>,).
2023-10-16 17:49:29,684 - stpipe.EurekaSpec2Pipeline.msa_flagging - INFO - Step msa_flagging parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '/Volumes/DataDrive/WASP-80b_Transit_F322W2/Stage1/S1_2022-12-14_WASP80b_transit_F322W2_run1'}
2023-10-16 17:49:29,685 - stpipe.EurekaSpec2Pipeline.msa_flagging - INFO - Step skipped.
2023-10-16 17:49:29,691 - stpipe.EurekaSpec2Pipeline.msa_flagging - INFO - Step msa_flagging done
2023-10-16 17:49:29,810 - stpipe.EurekaSpec2Pipeline.flat_field - INFO - Step flat_field running with args (<CubeModel(190, 256, 2048) from jw01185002001_04103_00001-seg001_nrcalong_rateints.fits>,).
2023-10-16 17:49:29,811 - stpipe.EurekaSpec2Pipeline.flat_field - INFO - Step flat_field parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '/Volumes/DataDrive/WASP-80b_Transit_F322W2/Stage1/S1_2022-12-14_WASP80b_transit_F322W2_run1', 'save_interpolated_flat': False, 'user_supplied_flat': None, 'inverse': False}
2023-10-16 17:49:31,013 - stpipe.EurekaSpec2Pipeline.flat_field - INFO - Extracting matching subarray from flat
2023-10-16 17:49:32,558 - stpipe.EurekaSpec2Pipeline.flat_field - INFO - Step flat_field done
2023-10-16 17:49:32,672 - stpipe.EurekaSpec2Pipeline.extract_2d - INFO - Step extract_2d running with args (<CubeModel(190, 256, 2048) from jw01185002001_04103_00001-seg001_nrcalong_rateints.fits>,).
2023-10-16 17:49:32,673 - stpipe.EurekaSpec2Pipeline.extract_2d - INFO - Step extract_2d parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '/Volumes/DataDrive/WASP-80b_Transit_F322W2/Stage1/S1_2022-12-14_WASP80b_transit_F322W2_run1', 'slit_name': None, 'extract_orders': None, 'grism_objects': None, 'tsgrism_extract_height': None, 'wfss_extract_half_height': 5, 'wfss_mmag_extract': None, 'wfss_nbright': 1000}
2023-10-16 17:49:32,708 - stpipe.EurekaSpec2Pipeline.extract_2d - INFO - EXP_TYPE is NRC_TSGRISM
2023-10-16 17:49:32,708 - stpipe.EurekaSpec2Pipeline.extract_2d - INFO - Setting extraction height to 64
2023-10-16 17:49:32,732 - stpipe.EurekaSpec2Pipeline.extract_2d - INFO - Using default order extraction from reference file
2023-10-16 17:49:32,732 - stpipe.EurekaSpec2Pipeline.extract_2d - INFO - Extracting order: [1]
Traceback (most recent call last):
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/stdatamodels/properties.py", line 327, in __getattr__
    val = self._instance[attr]
KeyError: 'wcs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 120, in process
    result = self.process_exposure_product(
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 264, in process_exposure_product
    calibrated = self._process_grism(calibrated)
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 470, in _process_grism
    calibrated = self.extract_2d(calibrated)
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/stpipe/step.py", line 454, in run
    step_result = self.process(*args)
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/jwst/extract_2d/extract_2d_step.py", line 37, in process
    output_model = extract_2d.extract2d(dm, self.slit_name,
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/jwst/extract_2d/extract_2d.py", line 74, in extract2d
    output_model = extract_tso_object(input_model,
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/jwst/extract_2d/grisms.py", line 125, in extract_tso_object
    subwcs = copy.deepcopy(input_model.meta.wcs)
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/stdatamodels/properties.py", line 330, in __getattr__
    raise AttributeError("No attribute '{0}'".format(attr))
AttributeError: No attribute 'wcs'
Traceback (most recent call last):
  File "/Users/tjbell1/Research/JWST/ERS/Eureka/ecfs/WASP80b_transit_F444W/run_eureka.ecf", line 21, in <module>
    s2_meta = s2.calibrateJWST(eventlabel)
  File "/Users/tjbell1/Research/JWST/ERS/Eureka/ecfs/WASP80b_transit_F444W/../../src/eureka/S2_calibrations/s2_calibrate.py", line 177, in calibrateJWST
    pipeline.run_eurekaS2(filename, meta, log)
  File "/Users/tjbell1/Research/JWST/ERS/Eureka/ecfs/WASP80b_transit_F444W/../../src/eureka/S2_calibrations/s2_calibrate.py", line 279, in run_eurekaS2
    self(filename)
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/stpipe/step.py", line 454, in run
    step_result = self.process(*args)
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 138, in process
    raise RuntimeError('\n'.join(failures))
RuntimeError: Traceback (most recent call last):
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/stdatamodels/properties.py", line 327, in __getattr__
    val = self._instance[attr]
KeyError: 'wcs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 120, in process
    result = self.process_exposure_product(
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 264, in process_exposure_product
    calibrated = self._process_grism(calibrated)
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/jwst/pipeline/calwebb_spec2.py", line 470, in _process_grism
    calibrated = self.extract_2d(calibrated)
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/stpipe/step.py", line 454, in run
    step_result = self.process(*args)
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/jwst/extract_2d/extract_2d_step.py", line 37, in process
    output_model = extract_2d.extract2d(dm, self.slit_name,
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/jwst/extract_2d/extract_2d.py", line 74, in extract2d
    output_model = extract_tso_object(input_model,
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/jwst/extract_2d/grisms.py", line 125, in extract_tso_object
    subwcs = copy.deepcopy(input_model.meta.wcs)
  File "/Users/tjbell1/miniconda3/envs/eureka_starry/lib/python3.9/site-packages/stdatamodels/properties.py", line 330, in __getattr__
    raise AttributeError("No attribute '{0}'".format(attr))
AttributeError: No attribute 'wcs'
```

### What operating system are you using?

macOS Ventura 13.6

### What version of Python are you running?

Python 3.9.7

### What Python packages do you have installed?

```
# Name                    Version                   Build  Channel
aesara-theano-fallback    0.1.0                    pypi_0    pypi
alabaster                 0.7.13                   pypi_0    pypi
anyio                     3.7.1                    pypi_0    pypi
appnope                   0.1.3                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
arviz                     0.12.1                   pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
asdf                      2.15.0                   pypi_0    pypi
asdf-astropy              0.4.0                    pypi_0    pypi
asdf-coordinates-schemas  0.2.0                    pypi_0    pypi
asdf-standard             1.0.3                    pypi_0    pypi
asdf-transform-schemas    0.3.0                    pypi_0    pypi
asdf-unit-schemas         0.1.0                    pypi_0    pypi
asdf-wcs-schemas          0.1.1                    pypi_0    pypi
asteval                   0.9.31                   pypi_0    pypi
astraeus                  0.3                      pypi_0    pypi
astropy                   5.3.1                    pypi_0    pypi
astropy-healpix           0.7                      pypi_0    pypi
astroquery                0.4.6                    pypi_0    pypi
astroscrappy              1.1.0                    pypi_0    pypi
asttokens                 2.2.1                    pypi_0    pypi
async-lru                 2.0.4                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
babel                     2.12.1                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
batman-package            2.4.9                    pypi_0    pypi
bayesicfitting            3.1.1                    pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
bidict                    0.22.1                   pypi_0    pypi
bleach                    6.0.0                    pypi_0    pypi
bokeh                     2.4.3                    pypi_0    pypi
bottleneck                1.3.7                    pypi_0    pypi
ca-certificates           2023.7.22            h8857fd0_0    conda-forge
cachetools                5.3.1                    pypi_0    pypi
ccdproc                   2.4.1                    pypi_0    pypi
celerite                  0.4.2                    pypi_0    pypi
celerite2                 0.3.0rc2.dev11+g74b0705.d20230915          pypi_0    pypi
certifi                   2023.7.22                pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
cftime                    1.6.2                    pypi_0    pypi
charset-normalizer        3.2.0                    pypi_0    pypi
click                     8.1.6                    pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
comm                      0.1.4                    pypi_0    pypi
contourpy                 1.1.0                    pypi_0    pypi
corner                    2.2.2                    pypi_0    pypi
coverage                  7.3.0                    pypi_0    pypi
crds                      11.17.2                  pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    3.0.0                    pypi_0    pypi
dask                      2023.8.0                 pypi_0    pypi
debugpy                   1.6.7.post1              pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
deprecat                  2.1.1                    pypi_0    pypi
dill                      0.3.7                    pypi_0    pypi
docutils                  0.18.1                   pypi_0    pypi
drizzle                   1.13.7                   pypi_0    pypi
dynesty                   2.1.2                    pypi_0    pypi
emcee                     3.1.4                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
eureka                    0.10.dev72+g819c00ba.d20230814          pypi_0    pypi
exceptiongroup            1.1.3                    pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
exoplanet                 0.5.3                    pypi_0    pypi
exoplanet-core            0.1.2                    pypi_0    pypi
exotic-ld                 3.0.0                    pypi_0    pypi
fasteners                 0.18                     pypi_0    pypi
fastjsonschema            2.18.0                   pypi_0    pypi
fastprogress              1.0.3                    pypi_0    pypi
filelock                  3.12.2                   pypi_0    pypi
flake8                    6.1.0                    pypi_0    pypi
fonttools                 4.42.0                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
fsspec                    2023.6.0                 pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
george                    0.4.0                    pypi_0    pypi
gwcs                      0.18.3                   pypi_0    pypi
h5netcdf                  1.2.0                    pypi_0    pypi
h5py                      3.9.0                    pypi_0    pypi
html5lib                  1.1                      pypi_0    pypi
idna                      3.4                      pypi_0    pypi
image-registration        0.2.7.dev20+gb42a1af          pypi_0    pypi
imageio                   2.31.1                   pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        6.8.0                    pypi_0    pypi
importlib-resources       6.0.1                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
ipykernel                 6.25.1                   pypi_0    pypi
ipython                   8.14.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.1.0                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
jaraco-classes            3.3.0                    pypi_0    pypi
jedi                      0.19.0                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
json5                     0.9.14                   pypi_0    pypi
jsonpointer               2.4                      pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            8.3.0                    pypi_0    pypi
jupyter-console           6.6.3                    pypi_0    pypi
jupyter-core              5.3.1                    pypi_0    pypi
jupyter-events            0.6.3                    pypi_0    pypi
jupyter-lsp               2.2.0                    pypi_0    pypi
jupyter-server            2.7.0                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyterlab                4.0.5                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.24.0                   pypi_0    pypi
jupyterlab-widgets        3.0.8                    pypi_0    pypi
jwst                      1.10.2                   pypi_0    pypi
keyring                   24.2.0                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
libcxx                    16.0.6               hd57cbcb_0    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libsqlite                 3.42.0               h58db7d2_0    conda-forge
libzlib                   1.2.13               h8a1eda9_5    conda-forge
llvm-openmp               16.0.6               hff08bdf_0    conda-forge
lmfit                     1.2.2                    pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mccabe                    0.7.0                    pypi_0    pypi
mdit-py-plugins           0.4.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mistune                   3.0.1                    pypi_0    pypi
mkl                       2022.2.1         h44ed08c_16952    conda-forge
mkl-service               2.4.0            py39hcf0e074_0    conda-forge
more-itertools            10.1.0                   pypi_0    pypi
myst-parser               2.0.0                    pypi_0    pypi
nbclient                  0.8.0                    pypi_0    pypi
nbconvert                 7.7.3                    pypi_0    pypi
nbformat                  5.9.2                    pypi_0    pypi
nbsphinx                  0.9.2                    pypi_0    pypi
ncurses                   6.4                  hf0c8a7f_0    conda-forge
nest-asyncio              1.5.7                    pypi_0    pypi
netcdf4                   1.6.4                    pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
notebook                  7.0.2                    pypi_0    pypi
notebook-shim             0.2.3                    pypi_0    pypi
numcodecs                 0.11.0                   pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
numpydoc                  1.5.0                    pypi_0    pypi
opencv-python             4.7.0.72                 pypi_0    pypi
opencv-python-headless    4.7.0.72                 pypi_0    pypi
openssl                   3.1.2                h8a1eda9_0    conda-forge
overrides                 7.4.0                    pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parsley                   1.3                      pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
partd                     1.4.0                    pypi_0    pypi
patsy                     0.5.3                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
photutils                 1.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.0.0                   pypi_0    pypi
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
platformdirs              3.10.0                   pypi_0    pypi
pluggy                    1.2.0                    pypi_0    pypi
poppy                     1.1.1                    pypi_0    pypi
prometheus-client         0.17.1                   pypi_0    pypi
prompt-toolkit            3.0.39                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyastronomy               0.19.0                   pypi_0    pypi
pycodestyle               2.11.0                   pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyerfa                    2.0.0.3                  pypi_0    pypi
pyflakes                  3.1.0                    pypi_0    pypi
pygments                  2.16.1                   pypi_0    pypi
pymc3                     3.11.5                   pypi_0    pypi
pymc3-ext                 0.1.1                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pysynphot                 2.0.0                    pypi_0    pypi
pytest                    7.4.0                    pypi_0    pypi
pytest-cov                4.1.0                    pypi_0    pypi
pytest-doctestplus        1.0.0                    pypi_0    pypi
python                    3.9.7           h38b4d05_3_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
python_abi                3.9                      3_cp39    conda-forge
pytz                      2023.3                   pypi_0    pypi
pyvo                      1.4.1                    pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.1.1                   pypi_0    pypi
qtconsole                 5.4.3                    pypi_0    pypi
qtpy                      2.3.1                    pypi_0    pypi
quantities                0.14.1                   pypi_0    pypi
readline                  8.2                  h9e318b2_1    conda-forge
reproject                 0.11.0                   pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
semver                    3.0.1                    pypi_0    pypi
send2trash                1.8.2                    pypi_0    pypi
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
setuptools-scm            7.1.0                    pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.3.0                    pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
spectres                  2.2.0                    pypi_0    pypi
spherical-geometry        1.2.23                   pypi_0    pypi
sphinx                    6.2.1                    pypi_0    pypi
sphinx-automodapi         0.15.0                   pypi_0    pypi
sphinx-rtd-theme          1.2.2                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.7                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.5                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.4                    pypi_0    pypi
sphinxcontrib-jquery      4.1                      pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.6                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.8                    pypi_0    pypi
sqlite                    3.42.0               h2b0dec6_0    conda-forge
stack-data                0.6.2                    pypi_0    pypi
starry                    1.2.0                    pypi_0    pypi
statsmodels               0.14.0                   pypi_0    pypi
stcal                     1.3.8                    pypi_0    pypi
stdatamodels              1.3.1                    pypi_0    pypi
stpipe                    0.4.6                    pypi_0    pypi
stsci-image               2.3.5                    pypi_0    pypi
stsci-imagestats          1.6.3                    pypi_0    pypi
stsci-stimage             0.2.6                    pypi_0    pypi
svo-filters               0.4.4                    pypi_0    pypi
tbb                       2021.10.0            h1c7c39f_0    conda-forge
terminado                 0.17.1                   pypi_0    pypi
theano-pymc               1.1.2                    pypi_0    pypi
tifffile                  2023.8.12                pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h5dbffcc_0    conda-forge
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
tornado                   6.3.3                    pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
tweakwcs                  0.8.2                    pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
uncertainties             3.1.7                    pypi_0    pypi
uri-template              1.3.0                    pypi_0    pypi
urllib3                   2.0.4                    pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.6.1                    pypi_0    pypi
wheel                     0.41.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.8                    pypi_0    pypi
wiimatch                  0.3.1                    pypi_0    pypi
wrapt                     1.15.0                   pypi_0    pypi
xarray                    2023.7.0                 pypi_0    pypi
xarray-einstats           0.6.0                    pypi_0    pypi
xz                        5.2.6                h775f41a_0    conda-forge
zarr                      2.16.0                   pypi_0    pypi
zipp                      3.16.2                   pypi_0    pypi
zlib                      1.2.13               h8a1eda9_5    conda-forge
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Huh, well I don't know whether or not this is resolvable with `jwst==1.10.2`, but upgrading to `jwst==1.11.4` (which updates `stcal`, `stdatamodels`, and `stpipe`, one of which is likely what is causing my bug, and none of which can be updated with `jwst==1.10.2`) and setting a new upper limit of `xarray<2023.10.0` (to avoid issues with `pymc3`) did the job for me. Any reservations against applying those changes, @kevin218?

One headache that we have coming is that `jwst>=1.12` requires `numpy>1.22` while all the `pymc3` code requires `numpy<1.22`... No idea how we're going to overcome that one in the future without (1) abandoning the `pymc3` code which would be such an enormous pain (so many hours spent on that code) and wouldn't allow for eclipse mapping, or (2) not allowing `jwst` and `pymc3` to be installed in the same environment...

**Comment by kevin218** [comment]
As long as it works for all instruments, I support applying these changes.  We should then move to v0.10.

Neither of these options is desirable.  Is there any hope of submitting a PR that updates `pymc3` to be compatible with newer versions of numpy?

**Comment by taylorbell57** [comment]
I re-ran the tests and they all worked fine, but I haven't had the time yet to re-run some old datasets to make sure they're processed reasonably; I'll do so in a few days when I get the chance.

As for updating `pymc3`, I'm pretty sure that version of the code (which is now called just `pymc`) is officially deprecated since `theano` is officially deprecated and not accepting edits, but I did find https://github.com/exoplanet-dev/theano-exoplanet which might help us get part of the way. I also know Dan and some other students/postdocs are working on revamping `starry` to eventually use `jax` or something else (potentially it is this under-development repo: https://github.com/exoplanet-dev/jaxoplanet).
