### ISSUE TITLE
Cannot use Stage3 reading x1dints files

### ISSUE THREAD

**Issue by Achrene** [kevin218/Eureka#672]
### Instrument

MIRI (Stages 1-3)

### What happened?

I made my own reduction up to stage 3 where I produced the x1dints files. In the Stage 3 configuration file, I set the suffix to x1dints and provided a set of FITS binary tables containing the 1D extracted spectra, as an input. I get an error saying that the SCI extension is not found. The code seems to be trying to read calints file instead of x1dints files. Could you please tell me how to use Eureka! stage 3 with x1dints files as an input? Thanks!

### Error traceback output

```
Starting Stage 3 Reduction

Input directory: /feynman/home/dap/lde3/ah258874/work/data/HD106315c/pipeline_output/test_2/
Output directory: /feynman/home/dap/lde3/ah258874/work/data/HD106315c/Stage3/S3_2024-07-12_HD106315c_run1/ap4_bg10/
Using ap=4, bg=10, expand=1
Copying S3 control file

Found 14 data file(s) ending in x1dints.fits
Starting batch 1 of 3 with 6 files
  Reading file 1...
Traceback (most recent call last):
  File "/feynman/work/dap/lde3/ah258874/data/HD106315c/scripts/eureka_stage3.py", line 28, in <module>
    s3_meta = s3.reduce(eventlabel, ecf_path=ecf_path)
  File "/feynman/home/dap/lde3/ah258874/.conda/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/s3_reduce.py", line 298, in reduce
    data, meta, log = inst.read(meta.segment_list[i], data,
  File "/feynman/home/dap/lde3/ah258874/.conda/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/miri.py", line 59, in read
    data.attrs['shdr'] = hdulist['SCI', 1].header
  File "/feynman/home/dap/lde3/ah258874/.conda/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 380, in __getitem__
    super().__getitem__, self._positive_index_of(key)
  File "/feynman/home/dap/lde3/ah258874/.conda/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 847, in _positive_index_of
    index = self.index_of(key)
  File "/feynman/home/dap/lde3/ah258874/.conda/envs/eureka/lib/python3.9/site-packages/astropy/io/fits/hdu/hdulist.py", line 829, in index_of
    raise KeyError(f"Extension {key!r} not found.")
KeyError: "Extension ('SCI', 1) not found."
```

### What operating system are you using?

I am running the code on a cluster.

### What version of Python are you running?

Python 3.9.7

### What Python packages do you have installed?

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
aesara-theano-fallback    0.1.0                    pypi_0    pypi
alabaster                 0.7.16                   pypi_0    pypi
arviz                     0.12.1                   pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
asdf                      2.15.0                   pypi_0    pypi
asdf-coordinates-schemas  0.3.0                    pypi_0    pypi
asdf-standard             1.1.1                    pypi_0    pypi
asdf-transform-schemas    0.5.0                    pypi_0    pypi
asdf-wcs-schemas          0.4.0                    pypi_0    pypi
asteval                   0.9.32                   pypi_0    pypi
astraeus                  0.3                      pypi_0    pypi
astropy                   5.3.4                    pypi_0    pypi
astropy-healpix           1.0.2                    pypi_0    pypi
astroscrappy              1.1.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
babel                     2.14.0                   pypi_0    pypi
batman-package            2.4.9                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
bokeh                     2.4.3                    pypi_0    pypi
bottleneck                1.3.8                    pypi_0    pypi
ca-certificates           2024.3.11            h06a4308_0  
cachetools                5.3.3                    pypi_0    pypi
ccdproc                   2.4.1                    pypi_0    pypi
celerite                  0.4.2                    pypi_0    pypi
certifi                   2024.2.2                 pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
cftime                    1.6.3                    pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.0.0                    pypi_0    pypi
contourpy                 1.2.0                    pypi_0    pypi
corner                    2.2.2                    pypi_0    pypi
crds                      11.17.19                 pypi_0    pypi
cryptography              42.0.5                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
dask                      2024.3.1                 pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
deprecat                  2.1.1                    pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
docutils                  0.20.1                   pypi_0    pypi
drizzle                   1.15.1                   pypi_0    pypi
dynesty                   2.1.3                    pypi_0    pypi
emcee                     3.1.4                    pypi_0    pypi
eureka                    0.11.dev0+g696df7c8.d20240325          pypi_0    pypi
exceptiongroup            1.2.0                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
exoplanet                 0.5.3                    pypi_0    pypi
exoplanet-core            0.1.2                    pypi_0    pypi
exotic-ld                 3.0.0                    pypi_0    pypi
fasteners                 0.19                     pypi_0    pypi
fastprogress              1.0.3                    pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
fonttools                 4.50.0                   pypi_0    pypi
fsspec                    2024.3.1                 pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
george                    0.4.1                    pypi_0    pypi
gwcs                      0.21.0                   pypi_0    pypi
h5netcdf                  1.3.0                    pypi_0    pypi
h5py                      3.10.0                   pypi_0    pypi
html5lib                  1.1                      pypi_0    pypi
idna                      3.6                      pypi_0    pypi
imageio                   2.34.0                   pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-resources       6.4.0                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
ipython                   8.18.1                   pypi_0    pypi
jaraco-classes            3.3.1                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jeepney                   0.8.0                    pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jwst                      1.11.4                   pypi_0    pypi
keyring                   24.3.1                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
lmfit                     1.2.2                    pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.8.3                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
more-itertools            10.2.0                   pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
netcdf4                   1.6.5                    pypi_0    pypi
networkx                  3.2.1                    pypi_0    pypi
numcodecs                 0.12.1                   pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
numpydoc                  1.6.0                    pypi_0    pypi
opencv-python             4.7.0.72                 pypi_0    pypi
opencv-python-headless    4.7.0.72                 pypi_0    pypi
openssl                   1.1.1w               h7f8727e_0  
packaging                 24.0                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
partd                     1.4.1                    pypi_0    pypi
patsy                     0.5.6                    pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
pillow                    10.2.0                   pypi_0    pypi
pip                       23.3.1           py39h06a4308_0  
pluggy                    1.4.0                    pypi_0    pypi
prompt-toolkit            3.0.43                   pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyerfa                    2.0.1.1                  pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pymc3                     3.11.5                   pypi_0    pypi
pymc3-ext                 0.1.1                    pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pyrsistent                0.20.0                   pypi_0    pypi
pysynphot                 2.0.0                    pypi_0    pypi
pytest                    8.1.1                    pypi_0    pypi
python                    3.9.7                h12debd9_1  
python-dateutil           2.9.0.post0              pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
reproject                 0.13.0                   pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
secretstorage             3.3.3                    pypi_0    pypi
semver                    3.0.2                    pypi_0    pypi
setuptools                68.2.2           py39h06a4308_0  
setuptools-scm            8.0.4                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1  
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
sphinx                    7.2.6                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.8                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.6                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.5                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.7                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.10                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
stack-data                0.6.3                    pypi_0    pypi
starry                    1.2.0                    pypi_0    pypi
stcal                     1.4.4                    pypi_0    pypi
stdatamodels              1.7.2                    pypi_0    pypi
stpipe                    0.5.1                    pypi_0    pypi
svo-filters               0.4.4                    pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
theano-pymc               1.1.2                    pypi_0    pypi
tifffile                  2024.2.12                pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.1                   pypi_0    pypi
tornado                   6.4                      pypi_0    pypi
tqdm                      4.66.2                   pypi_0    pypi
traitlets                 5.14.2                   pypi_0    pypi
tweakwcs                  0.8.6                    pypi_0    pypi
typing-extensions         4.10.0                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
uncertainties             3.1.7                    pypi_0    pypi
urllib3                   2.2.1                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.41.2           py39h06a4308_0  
wrapt                     1.16.0                   pypi_0    pypi
xarray                    2023.9.0                 pypi_0    pypi
xarray-einstats           0.6.0                    pypi_0    pypi
xz                        5.4.6                h5eee18b_0  
zarr                      2.17.1                   pypi_0    pypi
zipp                      3.18.1                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Hi Achrene, as detailed on [this docs page](https://eurekadocs.readthedocs.io/en/latest/stages.html), Stage 3 of Eureka! performs background suubtraction and optimal spectral extraction (among other things). As a result, it doesn't make sense to try to run Stage 3 on an x1dints file, and the only acceptable inputs are calints files. That said, if you want to stick with your own x1dints file and run the remaining stages of Eureka!, we just added the ability to start Stage 4 with your own custom outputs (regardless of which pipeline you used to do the spectral or photometric extraction), and Aarynn Carter wrote a tutorial on how to do so [here](https://github.com/kevin218/Eureka/blob/main/docs/source/tutorials/formatting_eureka_s4_compatible_data.ipynb). That said, if you're using the default x1dints file output from the `jwst` pipeline's `calwebb_spec2` or `calwebb_tso3`, I would strongly encourage you to consider using Eureka!'s Stage 3 to perform the spectral extraction and other reduction steps as I and others have had bad experiences with the `jwst` pipeline's treatment of TSO data.

As there's no actionable task for us here, I'm going to close this issue to keep our to-do list tidy, but you'll still be able to reply if you have any follow-up comments/questions.
