### ISSUE TITLE
I can't run run_eureka.py with the demo files

### ISSUE THREAD

**Issue by Paulinappl** [kevin218/Eureka#673]
### What happened?

I was using this line: python run_eureka.py and I haven't been able to run eureka!,

Regarding this comment that appears in the terminal: You likely need to change the inputdir in S2_nirspec_fs_template.ecf to point to the folder containing the "rateints.fits" files.

I already checked the route that points inputdir in S2_wasp39b.ecf (S2_nirspec_fs_template.ecf ):
inputdir:  Data/JWST-Sim/NIRSpec/Stage1
file that has rateints in the inputdir route is:  jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_TINY_injected_rateints.fits

I also haven't been able to download pymc3.

### Error traceback output

```
Could not import starry and/or pymc3 related packages. Functionality may be limited.
WARNING: Unable to find an output metadata file from Eureka!'s S1 in the folder:
"/home/User/Data/JWST-Sim/NIRSpec/Stage1/"
Assuming this S1 data was produced by the JWST pipeline instead.
Traceback (most recent call last):
  File "/home/iaunam/Eureka/demos/JWST/run_eureka.py", line 23, in <module>
    s2_meta = s2.calibrateJWST(eventlabel, ecf_path=ecf_path)
  File "/home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S2_calibrations/s2_calibrate.py", line 93, in calibrateJWST
    meta = util.find_fits(meta)
  File "/home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/lib/util.py", line 357, in find_fits
    raise AssertionError(message)
AssertionError: Unable to find any "rateints.fits" files in the inputdir: 
"/home/User/Data/JWST-Sim/NIRSpec/Stage1/"!
You likely need to change the inputdir in S2_nirspec_fs_template.ecf to point to the folder containing the "rateints.fits" files.
```

### What operating system are you using?

Ubuntu 18.04.6 LTS

### What version of Python are you running?

Python 3.9.7

### What Python packages do you have installed?

```
# packages in environment at /home/iaunam/anaconda3/envs/eureka:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
alabaster                 0.7.16                   pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
asdf                      3.2.0                    pypi_0    pypi
asdf-astropy              0.6.1                    pypi_0    pypi
asdf-coordinates-schemas  0.3.0                    pypi_0    pypi
asdf-standard             1.1.1                    pypi_0    pypi
asdf-transform-schemas    0.5.0                    pypi_0    pypi
asdf-wcs-schemas          0.4.0                    pypi_0    pypi
asteval                   1.0.0                    pypi_0    pypi
astraeus                  0.3                      pypi_0    pypi
astropy                   6.0.1                    pypi_0    pypi
astropy-healpix           1.0.3                    pypi_0    pypi
astropy-iers-data         0.2024.7.8.0.31.19          pypi_0    pypi
astroquery                0.4.7                    pypi_0    pypi
astroscrappy              1.2.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
babel                     2.15.0                   pypi_0    pypi
backports-tarfile         1.2.0                    pypi_0    pypi
batman-package            2.4.9                    pypi_0    pypi
bayesicfitting            3.2.1                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
bokeh                     2.4.3                    pypi_0    pypi
bottleneck                1.4.0                    pypi_0    pypi
ca-certificates           2024.7.2             h06a4308_0  
ccdproc                   2.4.2                    pypi_0    pypi
celerite                  0.4.3                    pypi_0    pypi
certifi                   2024.7.4                 pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
cftime                    1.6.4                    pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.0.0                    pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
corner                    2.2.2                    pypi_0    pypi
crds                      11.17.26                 pypi_0    pypi
cryptography              42.0.8                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
dask                      2024.7.0                 pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
docutils                  0.21.2                   pypi_0    pypi
drizzle                   1.15.1                   pypi_0    pypi
dynesty                   2.1.4                    pypi_0    pypi
emcee                     3.1.6                    pypi_0    pypi
eureka                    0.10                     pypi_0    pypi
exceptiongroup            1.2.1                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
exotic-ld                 3.2.0                    pypi_0    pypi
fasteners                 0.19                     pypi_0    pypi
filelock                  3.15.4                   pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
george                    0.4.2                    pypi_0    pypi
gwcs                      0.21.0                   pypi_0    pypi
h5netcdf                  1.3.0                    pypi_0    pypi
h5py                      3.11.0                   pypi_0    pypi
html5lib                  1.1                      pypi_0    pypi
idna                      3.7                      pypi_0    pypi
imageio                   2.34.2                   pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        8.0.0                    pypi_0    pypi
importlib-resources       6.4.0                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
ipython                   8.18.1                   pypi_0    pypi
jaraco-classes            3.4.0                    pypi_0    pypi
jaraco-context            5.3.0                    pypi_0    pypi
jaraco-functools          4.0.1                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jeepney                   0.8.0                    pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jwst                      1.11.4                   pypi_0    pypi
keyring                   25.2.1                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
lmfit                     1.3.1                    pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.1                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
more-itertools            10.3.0                   pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
netcdf4                   1.7.1.post1              pypi_0    pypi
networkx                  3.2.1                    pypi_0    pypi
numcodecs                 0.12.1                   pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
numpydoc                  1.7.0                    pypi_0    pypi
opencv-python-headless    4.10.0.84                pypi_0    pypi
openssl                   1.1.1w               h7f8727e_0  
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
parsley                   1.3                      pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
partd                     1.4.2                    pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
photutils                 1.11.0                   pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.0             py39h06a4308_0  
pluggy                    1.5.0                    pypi_0    pypi
poppy                     1.1.1                    pypi_0    pypi
prompt-toolkit            3.0.47                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pyerfa                    2.0.1.4                  pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pysynphot                 2.0.0                    pypi_0    pypi
pytest                    8.2.2                    pypi_0    pypi
python                    3.9.7                h12debd9_1  
python-dateutil           2.9.0.post0              pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pyvo                      1.5.2                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
referencing               0.35.1                   pypi_0    pypi
reproject                 0.13.0                   pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
rpds-py                   0.19.0                   pypi_0    pypi
scikit-image              0.24.0                   pypi_0    pypi
scipy                     1.9.3                    pypi_0    pypi
secretstorage             3.3.3                    pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
setuptools                69.5.1           py39h06a4308_0  
setuptools-scm            8.1.0                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1  
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
spherical-geometry        1.3.2                    pypi_0    pypi
sphinx                    7.3.7                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.8                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.6                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.5                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.7                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.10                   pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0  
stack-data                0.6.3                    pypi_0    pypi
stcal                     1.4.4                    pypi_0    pypi
stdatamodels              1.7.2                    pypi_0    pypi
stpipe                    0.5.1                    pypi_0    pypi
stsci-image               2.3.9                    pypi_0    pypi
stsci-imagestats          1.8.3                    pypi_0    pypi
stsci-stimage             0.2.9                    pypi_0    pypi
svo-filters               0.4.4                    pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tifffile                  2024.7.2                 pypi_0    pypi
tk                        8.6.14               h39e8969_0  
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.1                   pypi_0    pypi
tornado                   6.4.1                    pypi_0    pypi
tqdm                      4.66.4                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
tweakwcs                  0.8.7                    pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
uncertainties             3.2.2                    pypi_0    pypi
urllib3                   2.2.2                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.43.0           py39h06a4308_0  
wiimatch                  0.3.2                    pypi_0    pypi
xarray                    2024.6.0                 pypi_0    pypi
xz                        5.4.6                h5eee18b_1  
zarr                      2.18.2                   pypi_0    pypi
zipp                      3.19.2                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1 
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Paulinappl** [comment]
I changed the directory I was in, I was in /DataAnalysis/JWST/MyFirstEureka/demos, I changed to /DataAnalysis/JWST/MyFirstEureka/ in this route I have the copies of the .ecf files (with the changes that had to be made in step 3.2 of the  quickstar guide) and the run_eureka.py file, and with that directory change my error changed, but I still haven't gotten results.


This is my new Error traceback output:

Could not import starry and/or pymc3 related packages. Functionality may be limited.
WARNING: Unable to find an output metadata file from Eureka!'s S1 in the folder:
"/home/iaunam/Data/JWST-Sim/NIRSpec/Stage1/"
Assuming this S1 data was produced by the JWST pipeline instead.

Starting Stage 2 Reduction
Input directory: /home/iaunam/Data/JWST-Sim/NIRSpec/Stage1/
Output directory: /home/iaunam/DataAnalysis/JWST/MyFirstEureka/Stage2/S2_2024-07-12_wasp39b_run2/
Copying S2 control file

Found 1 data file(s) ending in rateints.fits
2024-07-12 11:45:50,482 - stpipe.EurekaSpec2Pipeline - INFO - EurekaSpec2Pipeline instance created.
2024-07-12 11:45:50,483 - stpipe.EurekaSpec2Pipeline.bkg_subtract - INFO - BackgroundStep instance created.
2024-07-12 11:45:50,484 - stpipe.EurekaSpec2Pipeline.assign_wcs - INFO - AssignWcsStep instance created.
2024-07-12 11:45:50,485 - stpipe.EurekaSpec2Pipeline.imprint_subtract - INFO - ImprintStep instance created.
2024-07-12 11:45:50,486 - stpipe.EurekaSpec2Pipeline.msa_flagging - INFO - MSAFlagOpenStep instance created.
2024-07-12 11:45:50,487 - stpipe.EurekaSpec2Pipeline.extract_2d - INFO - Extract2dStep instance created.
2024-07-12 11:45:50,490 - stpipe.EurekaSpec2Pipeline.master_background_mos - INFO - MasterBackgroundMosStep instance created.
2024-07-12 11:45:50,491 - stpipe.EurekaSpec2Pipeline.master_background_mos.flat_field - INFO - FlatFieldStep instance created.
2024-07-12 11:45:50,492 - stpipe.EurekaSpec2Pipeline.master_background_mos.pathloss - INFO - PathLossStep instance created.
2024-07-12 11:45:50,493 - stpipe.EurekaSpec2Pipeline.master_background_mos.barshadow - INFO - BarShadowStep instance created.
2024-07-12 11:45:50,494 - stpipe.EurekaSpec2Pipeline.master_background_mos.photom - INFO - PhotomStep instance created.
2024-07-12 11:45:50,495 - stpipe.EurekaSpec2Pipeline.wavecorr - INFO - WavecorrStep instance created.
2024-07-12 11:45:50,496 - stpipe.EurekaSpec2Pipeline.flat_field - INFO - FlatFieldStep instance created.
2024-07-12 11:45:50,497 - stpipe.EurekaSpec2Pipeline.srctype - INFO - SourceTypeStep instance created.
2024-07-12 11:45:50,498 - stpipe.EurekaSpec2Pipeline.straylight - INFO - StraylightStep instance created.
2024-07-12 11:45:50,499 - stpipe.EurekaSpec2Pipeline.fringe - INFO - FringeStep instance created.
2024-07-12 11:45:50,500 - stpipe.EurekaSpec2Pipeline.residual_fringe - INFO - ResidualFringeStep instance created.
2024-07-12 11:45:50,501 - stpipe.EurekaSpec2Pipeline.pathloss - INFO - PathLossStep instance created.
2024-07-12 11:45:50,502 - stpipe.EurekaSpec2Pipeline.barshadow - INFO - BarShadowStep instance created.
2024-07-12 11:45:50,503 - stpipe.EurekaSpec2Pipeline.wfss_contam - INFO - WfssContamStep instance created.
2024-07-12 11:45:50,504 - stpipe.EurekaSpec2Pipeline.photom - INFO - PhotomStep instance created.
2024-07-12 11:45:50,504 - stpipe.EurekaSpec2Pipeline.pixel_replace - INFO - PixelReplaceStep instance created.
2024-07-12 11:45:50,506 - stpipe.EurekaSpec2Pipeline.resample_spec - INFO - ResampleSpecStep instance created.
2024-07-12 11:45:50,507 - stpipe.EurekaSpec2Pipeline.cube_build - INFO - CubeBuildStep instance created.
2024-07-12 11:45:50,508 - stpipe.EurekaSpec2Pipeline.extract_1d - INFO - Extract1dStep instance created.
Starting file 1 of 1
Running the Spec2Pipeline

2024-07-12 11:45:50,609 - stpipe.EurekaSpec2Pipeline - INFO - Step EurekaSpec2Pipeline running with args ('/home/iaunam/Data/JWST-Sim/NIRSpec/Stage1/jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_TINY_injected_rateints.fits',).
2024-07-12 11:45:50,638 - stpipe.EurekaSpec2Pipeline - INFO - Step EurekaSpec2Pipeline parameters are: {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': '/home/iaunam/DataAnalysis/JWST/MyFirstEureka/Stage2/S2_2024-07-12_wasp39b_run2/', 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': True, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'save_bsub': False, 'fail_on_exception': True, 'save_wfss_esec': False, 'steps': {'bkg_subtract': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'save_combined_background': False, 'sigma': 3.0, 'maxiters': None, 'wfss_mmag_extract': None}, 'assign_wcs': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'sip_approx': True, 'sip_max_pix_error': 0.1, 'sip_degree': None, 'sip_max_inv_pix_error': 0.1, 'sip_inv_degree': None, 'sip_npoints': 12, 'slit_y_low': -1, 'slit_y_high': 50}, 'imprint_subtract': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'msa_flagging': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'extract_2d': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'slit_name': None, 'extract_orders': None, 'grism_objects': None, 'tsgrism_extract_height': None, 'wfss_extract_half_height': 5, 'wfss_mmag_extract': None, 'wfss_nbright': 1000}, 'master_background_mos': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': True, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'force_subtract': False, 'save_background': False, 'user_background': None, 'inverse': False, 'steps': {'flat_field': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'save_interpolated_flat': False, 'user_supplied_flat': None, 'inverse': False}, 'pathloss': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'inverse': False, 'source_type': None}, 'barshadow': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'inverse': False, 'source_type': None}, 'photom': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'inverse': False, 'source_type': None, 'mrs_time_correction': True}}}, 'wavecorr': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'flat_field': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'save_interpolated_flat': False, 'user_supplied_flat': None, 'inverse': False}, 'srctype': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'source_type': None}, 'straylight': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'fringe': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': ''}, 'residual_fringe': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': 'residual_fringe', 'search_output_file': False, 'input_dir': '', 'save_intermediate_results': False, 'ignore_region_min': None, 'ignore_region_max': None}, 'pathloss': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'inverse': False, 'source_type': None}, 'barshadow': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'inverse': False, 'source_type': None}, 'wfss_contam': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'save_simulated_image': False, 'save_contam_images': False, 'maximum_cores': 'none'}, 'photom': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'inverse': False, 'source_type': None, 'mrs_time_correction': True}, 'pixel_replace': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'algorithm': 'fit_profile', 'n_adjacent_cols': 3}, 'resample_spec': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'pixfrac': 1.0, 'kernel': 'square', 'fillval': 'INDEF', 'weight_type': 'ivm', 'output_shape': None, 'crpix': None, 'crval': None, 'rotation': None, 'pixel_scale_ratio': 1.0, 'pixel_scale': None, 'output_wcs': '', 'single': False, 'blendheaders': True, 'allowed_memory': None, 'in_memory': True}, 'cube_build': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': True, 'output_use_index': True, 'save_results': False, 'skip': True, 'suffix': 's3d', 'search_output_file': False, 'input_dir': '', 'channel': 'all', 'band': 'all', 'grating': 'all', 'filter': 'all', 'output_type': 'band', 'scale1': 0.0, 'scale2': 0.0, 'scalew': 0.0, 'weighting': 'drizzle', 'coord_system': 'skyalign', 'rois': 0.0, 'roiw': 0.0, 'weight_power': 2.0, 'wavemin': None, 'wavemax': None, 'single': False, 'skip_dqflagging': False}, 'extract_1d': {'pre_hooks': [], 'post_hooks': [], 'output_file': None, 'output_dir': None, 'output_ext': '.fits', 'output_use_model': False, 'output_use_index': True, 'save_results': False, 'skip': False, 'suffix': None, 'search_output_file': True, 'input_dir': '', 'smoothing_length': None, 'bkg_fit': None, 'bkg_order': None, 'bkg_sigma_clip': 3.0, 'log_increment': 50, 'subtract_background': None, 'use_source_posn': None, 'center_xy': None, 'apply_apcorr': True, 'ifu_autocen': False, 'ifu_rfcorr': False, 'soss_atoca': True, 'soss_threshold': 0.01, 'soss_n_os': 2, 'soss_wave_grid_in': None, 'soss_wave_grid_out': None, 'soss_estimate': None, 'soss_rtol': 0.0001, 'soss_max_grid_size': 20000, 'soss_transform': None, 'soss_tikfac': None, 'soss_width': 40.0, 'soss_bad_pix': 'masking', 'soss_modelname': None}}}
2024-07-12 11:45:51,278 - stpipe.EurekaSpec2Pipeline - WARNING - /home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/asdf/yamlutil.py:282: AsdfConversionWarning: A ndarray subclass (<class 'astropy.io.fits.fitsrec.FITS_rec'>) was converted as a ndarray. This behavior will be removed from a future version of ASDF. See https://asdf.readthedocs.io/en/latest/asdf/config.html#convert-unknown-ndarray-subclasses
  warnings.warn(

2024-07-12 11:45:51,298 - stpipe.EurekaSpec2Pipeline - WARNING - /home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/asdf/yamlutil.py:282: AsdfConversionWarning: A ndarray subclass (<class 'astropy.io.fits.fitsrec.FITS_rec'>) was converted as a ndarray. This behavior will be removed from a future version of ASDF. See https://asdf.readthedocs.io/en/latest/asdf/config.html#convert-unknown-ndarray-subclasses
  warnings.warn(

2024-07-12 11:45:51,310 - stpipe.EurekaSpec2Pipeline - INFO - Prefetching reference files for dataset: 'jwdata0010010_11010_0001_NRS1_uncal_updatedHDR_TINY_injected_rateints.fits' reftypes = ['apcorr', 'camera', 'collimator', 'disperser', 'distortion', 'extract1d', 'filteroffset', 'fore', 'fpa', 'ifufore', 'ifupost', 'ifuslicer', 'msa', 'ote', 'regions', 'speckernel', 'specprofile', 'spectrace', 'specwcs', 'wavecorr', 'wavelengthrange', 'wavemap']
2024-07-12 11:45:51,310 - CRDS - ERROR -  (FATAL) CRDS server connection and cache load FAILED.  Cannot continue.
 See https://hst-crds.stsci.edu/docs/cmdline_bestrefs/ or https://jwst-crds.stsci.edu/docs/cmdline_bestrefs/
 for more information on configuring CRDS,  particularly CRDS_PATH and CRDS_SERVER_URL. : [Errno 2] No such file or directory: '/grp/crds/cache/config/jwst/server_config'

**Comment by taylorbell57** [comment]
Hi @Paulinappl, the answer to your concern is explained in the error message you have copy-pasted above. Your `run_eureka.py` file has a line that reads `eventlabel = 'nirspec_fs_template'`, and as a result the pipeline will use the Eureka! Control Files (.ecf files) that have the form `S#_nirspec_fs_template.ecf`. So in your S2_nirspec_fs_template.ecf file, there is a line which is apparently set to `topdir    /home/User/Data/JWST-Sim/NIRSpec` which is just the place-holder setting we put there, and you will need to adjust that setting to point to the correct location (which is presumably `/home/iaunam/Data/JWST-Sim/NIRSpec` based on what I can gleam from your error message).

**Comment by taylorbell57** [comment]
As for your second issue related to CRDS, please carefully read all of the instructions on our installation page as the answer is documented there: https://eurekadocs.readthedocs.io/en/latest/installation.html

**Comment by Paulinappl** [comment]
Thank you Taylor, I really appreciate your help!, thanks to you I now understand my first error, regrading the second one, I don't know if I'm not doing the CRDS step the right way (https://eurekadocs.readthedocs.io/en/latest/installation.html#crds-environment-variables), but if you could also help me find out if I'm not doing it the right way that would be awesome.

Here's the steps that I'm doing:

1. I typed this in this path in the terminal:
(eureka) iaunam@ia-unam:~/DataAnalysis/JWST/MyFirstEureka$ nano ~/.bashrc

2.  Once in there I wrote a the end these two lines:
export CRDS_PATH=/home/iaunam/crds_cache
export CRDS_SERVER_URL=https://jwst-crds.stsci.edu

3. I clicked ctr+o to save and then ctrl+x to exit nano

4. Then I put on the terminal: python run_eureka.py, in the same path as before (/DataAnalysis/JWST/MyFirstEureka).

And I still get the same error as my second error :(.

I'll attatch a txt document with everything that the bash.rc has in it, maybe that could help. 

Thank you again!
[bashrc.txt](https://github.com/user-attachments/files/16198689/bashrc.txt)

**Comment by taylorbell57** [comment]
Ah, I see we forgot to mention in those instructions that after editing the .bashrc file you need to close your terminal and open a new one for that change to apply

**Comment by Paulinappl** [comment]
Thank you so much Taylor!, it worked.
