### ISSUE TITLE
[Bug]:  Eureka! stops running at the beginning of stage 3

### ISSUE THREAD

**Issue by Paulinappl** [kevin218/Eureka#679]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

NIRSpec (Stages 1-3)

### What happened?

I was running Eureka! with 6 MAST files of WASP 39 from JWST and it stopped running almost at the beginning of stage 3.

### Error traceback output

Starting Stage 3 Reduction

Input directory: /home/iaunam/1st_trial_eureka/Stage2/S2_2024-08-08_WASP39b_byme_run1/
Output directory: /home/iaunam/1st_trial_eureka/Stage3/S3_2024-08-08_WASP39b_byme_run1/ap6_bg7/
Using ap=6, bg=7, expand=2
Copying S3 control file

Found 6 data file(s) ending in calints.fits
Starting file 1 of 6
  Reading file 1...
    Super-sampling y axis from 31 to 62 pixels...
2024-08-08 12:22:22,429 - stpipe - WARNING - /home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/s3_reduce.py:298: ResourceWarning: unclosed file <_io.BufferedReader name='/home/iaunam/1st_trial_eureka/Stage2/S2_2024-08-08_WASP39b_byme_run1/jw01366003001_04101_00001-seg001_nrs1_calints.fits'>
  data, meta, log = inst.read(meta.segment_list[i], data,

  Masking NaNs/infs in data arrays...
  Locating source position...
    Source position on detector is row 47.
  Automatically getting reference files to convert units to electrons...
  Converting from data numbers per second (DN/s) to electrons...
  Computing clean median frame...
  Correcting curvature and bringing the trace to the center of the detector...
  !!! Ensure that you are using meddata for the optimal extraction profile !!!
    Correcting the wavelength solution...
    Correcting the curvature over all integrations...
    Updating src_ypos to new center, row 25...
  Performing background outlier rejection...
  Performing CxC background subtraction...
100%|███████████████████████████████████████████████████████████████████████████████████| 155/155 [00:10<00:00, 14.83it/s]
  Creating figures for background subtraction...
100%|███████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:06<00:00,  1.29s/it]
  Recording y position and width for all integrations...
  0%|                                                                                             | 0/155 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/iaunam/Escritorio/Verano_2024/ECF_files_byme/run_eureka_wasp39_1.py", line 27, in <module>
    s3_spec, s3_meta = s3.reduce(eventlabel, ecf_path=ecf_path,
  File "/home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/s3_reduce.py", line 447, in reduce
    source_pos.source_pos_wrapper(data, meta, log,
  File "/home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/source_pos.py", line 73, in source_pos_wrapper
    writePos(source_pos(flux[n], meta, data.attrs['shdr'],
  File "/home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/source_pos.py", line 162, in source_pos
    src_ypos, src_ywidth = source_pos_gauss(flux, meta, m, n, plot)
  File "/home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/source_pos.py", line 405, in source_pos_gauss
    popt, pcov = curve_fit(gauss, y_pixels, med_row, p0)
  File "/home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/scipy/optimize/_minpack_py.py", line 839, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 1000.
2024-08-08 12:22:45,249 - stpipe - WARNING - sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/iaunam/1st_trial_eureka/Stage3/S3_2024-08-08_WASP39b_byme_run1/ap6_bg7/S3_WASP39b_byme_ap6_bg7.log' mode='w' encoding='UTF-8'>

### What operating system are you using?

Ubuntu 18.04.6 LTS

### What version of Python are you running?

Python 3.9.7

### What Python packages do you have installed?

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
alabaster                 0.7.16                   pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
asdf                      3.2.0                    pypi_0    pypi
asdf-astropy              0.6.1                    pypi_0    pypi
asdf-coordinates-schemas  0.3.0                    pypi_0    pypi
asdf-standard             1.1.1                    pypi_0    pypi
asdf-transform-schemas    0.5.0                    pypi_0    pypi
asdf-wcs-schemas          0.4.0                    pypi_0    pypi
asteval                   1.0.0                    pypi_0    pypi
astraeus                  0.3                      pypi_0    pypi
astropy                   6.0.1                    pypi_0    pypi
astropy-healpix           1.0.3                    pypi_0    pypi
astropy-iers-data         0.2024.7.8.0.31.19          pypi_0    pypi
astroquery                0.4.7                    pypi_0    pypi
astroscrappy              1.2.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
babel                     2.15.0                   pypi_0    pypi
backports-tarfile         1.2.0                    pypi_0    pypi
batman-package            2.4.9                    pypi_0    pypi
bayesicfitting            3.2.1                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
bokeh                     2.4.3                    pypi_0    pypi
bottleneck                1.4.0                    pypi_0    pypi
ca-certificates           2024.7.2             h06a4308_0  
ccdproc                   2.4.2                    pypi_0    pypi
celerite                  0.4.3                    pypi_0    pypi
certifi                   2024.7.4                 pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
cftime                    1.6.4                    pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.0.0                    pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
corner                    2.2.2                    pypi_0    pypi
crds                      11.17.26                 pypi_0    pypi
cryptography              42.0.8                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
dask                      2024.7.0                 pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
docutils                  0.21.2                   pypi_0    pypi
drizzle                   1.15.1                   pypi_0    pypi
dynesty                   2.1.4                    pypi_0    pypi
emcee                     3.1.6                    pypi_0    pypi
eureka                    0.10                     pypi_0    pypi
exceptiongroup            1.2.1                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
exotic-ld                 3.2.0                    pypi_0    pypi
fasteners                 0.19                     pypi_0    pypi
filelock                  3.15.4                   pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
george                    0.4.2                    pypi_0    pypi
gwcs                      0.21.0                   pypi_0    pypi
h5netcdf                  1.3.0                    pypi_0    pypi
h5py                      3.11.0                   pypi_0    pypi
html5lib                  1.1                      pypi_0    pypi
idna                      3.7                      pypi_0    pypi
imageio                   2.34.2                   pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        8.0.0                    pypi_0    pypi
importlib-resources       6.4.0                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
ipython                   8.18.1                   pypi_0    pypi
jaraco-classes            3.4.0                    pypi_0    pypi
jaraco-context            5.3.0                    pypi_0    pypi
jaraco-functools          4.0.1                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jeepney                   0.8.0                    pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jwst                      1.11.4                   pypi_0    pypi
keyring                   25.2.1                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
lmfit                     1.3.1                    pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.1                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
more-itertools            10.3.0                   pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
netcdf4                   1.7.1.post1              pypi_0    pypi
networkx                  3.2.1                    pypi_0    pypi
numcodecs                 0.12.1                   pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
numpydoc                  1.7.0                    pypi_0    pypi
opencv-python-headless    4.10.0.84                pypi_0    pypi
openssl                   1.1.1w               h7f8727e_0  
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
parsley                   1.3                      pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
partd                     1.4.2                    pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
photutils                 1.11.0                   pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.0             py39h06a4308_0  
pluggy                    1.5.0                    pypi_0    pypi
poppy                     1.1.1                    pypi_0    pypi
prompt-toolkit            3.0.47                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pyerfa                    2.0.1.4                  pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pysynphot                 2.0.0                    pypi_0    pypi
pytest                    8.2.2                    pypi_0    pypi
python                    3.9.7                h12debd9_1  
python-dateutil           2.9.0.post0              pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pyvo                      1.5.2                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
referencing               0.35.1                   pypi_0    pypi
reproject                 0.13.0                   pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
rpds-py                   0.19.0                   pypi_0    pypi
scikit-image              0.24.0                   pypi_0    pypi
scipy                     1.9.3                    pypi_0    pypi
secretstorage             3.3.3                    pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
setuptools                69.5.1           py39h06a4308_0  
setuptools-scm            8.1.0                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1  
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
spherical-geometry        1.3.2                    pypi_0    pypi
sphinx                    7.3.7                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.8                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.6                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.5                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.7                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.10                   pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0  
stack-data                0.6.3                    pypi_0    pypi
stcal                     1.4.4                    pypi_0    pypi
stdatamodels              1.7.2                    pypi_0    pypi
stpipe                    0.5.1                    pypi_0    pypi
stsci-image               2.3.9                    pypi_0    pypi
stsci-imagestats          1.8.3                    pypi_0    pypi
stsci-stimage             0.2.9                    pypi_0    pypi
svo-filters               0.4.4                    pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tifffile                  2024.7.2                 pypi_0    pypi
tk                        8.6.14               h39e8969_0  
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.1                   pypi_0    pypi
tornado                   6.4.1                    pypi_0    pypi
tqdm                      4.66.4                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
tweakwcs                  0.8.7                    pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
uncertainties             3.2.2                    pypi_0    pypi
urllib3                   2.2.2                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.43.0           py39h06a4308_0  
wiimatch                  0.3.2                    pypi_0    pypi
xarray                    2024.6.0                 pypi_0    pypi
xz                        5.4.6                h5eee18b_1  
zarr                      2.18.2                   pypi_0    pypi
zipp                      3.19.2                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
The code crashed while trying to compute the position and width of the spectral trace for each integration. It's tricky for me to troubleshoot this with the limited information I currently have. Can you please first set `isplots_S3` to `5` and set `nplots` to `5` in your ECF to get several potentially useful figures, and then look through all of those output figures to see if you can identify the source of your issue? Please also look through the NIRSpec-relevant templates which can be found [here](https://github.com/kevin218/Eureka/tree/main/demos/JWST) to make sure that your ECF settings are appropriate for your current instrument.

If after all of that you're still unable to troubleshoot the issue yourself, please copy-paste the contents of your Stage 3 ECF into a comment on this Issue so that I can check that there aren't any obvious issues there. If you're open to doing so, attaching a .zip folder with the figures output from Stage 3 would also be helpful to me

**Comment by kevin218** [comment]
The first settings to check would be xwindow and ywindow. Compare them to the position of the spectrum in ds9.

**Comment by Paulinappl** [comment]
Hi Kevin and Taylor,

I already did the next things:

1. Checked that my ecf file was like the ecf template for stage 3 (v0.10, since that's the version I'm using) and made sure that they were the same.
2. Set  isplots_S3 to 5 and set nplots to 5.
3. Checked xwindow and ywindow in ds9, and I did had to change those variables to match the spectrum in my six fit files (calints).

Regarding the third thing I did, I'm using fits files from WASP 39 from MAST and I downloaded 6 fits files, from seg001, seg002, seg003, each one has a nrs1 and nrs2 fits file, so I have 6 fits files that entered the pipeline in stage 1, is it ok that I used the 6 of them?, because the spectrum in the nrs1 and the nrs2 fits files is in different xwindow and ywindow position, but for the ecf file I used a range for xwindow and ywindow where you could see the spectrum in the nrs1 and nrs2 fits files, was that the right choice?, if I'm not being clear please let me know.

After doing 1-3, I'm no longer getting the error that I posted in this issue, I'm getting this one now:

Starting Stage 3 Reduction

Input directory: /home/iaunam/1st_trial_eureka/Stage2/S2_2024-08-13_WASP39b_byme_run4/
Output directory: /home/iaunam/1st_trial_eureka/Stage3/S3_2024-08-13_WASP39b_byme_run6/ap6_bg7/
Using ap=6, bg=7, expand=1
Copying S3 control file

Found 6 data file(s) ending in calints.fits
Starting file 1 of 6
  Reading file 1...
  Masking NaNs/infs in data arrays...
  FLUX has 58745 NaNs/infs, which is 0.88% of all pixels.
  ERR has 58745 NaNs/infs, which is 0.88% of all pixels.
  V0 has 58745 NaNs/infs, which is 0.88% of all pixels.
  Locating source position...
    Source position on detector is row 7.
  Automatically getting reference files to convert units to electrons...
  Converting from data numbers per second (DN/s) to electrons...
Traceback (most recent call last):
  File "/home/iaunam/Escritorio/Verano_2024/ECF_files_byme/run_eureka_wasp39_2.py", line 30, in <module>
    spec, meta = s3.reduce(eventlabel, ecf_path=ecf_path)
  File "/home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/s3_reduce.py", line 400, in reduce
    data, meta = b2f.convert_to_e(data, meta, log)
  File "/home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/bright2flux.py", line 341, in convert_to_e
    data = dn2electrons(data, meta)
  File "/home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/bright2flux.py", line 117, in dn2electrons
    data['flux'] *= gain
  File "/home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/xarray/core/_typed_ops.py", line 343, in __imul__
    return self._inplace_binary_op(other, operator.imul)
  File "/home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/xarray/core/dataarray.py", line 4751, in _inplace_binary_op
    f(self.variable, other_variable)
  File "/home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/xarray/core/_typed_ops.py", line 663, in __imul__
    return self._inplace_binary_op(other, operator.imul)
  File "/home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/xarray/core/variable.py", line 2329, in _inplace_binary_op
    self.values = f(self_data, other_data)
ValueError: operands could not be broadcast together with shapes (155,21,2048) (21,2047) (155,21,2048) 


If I need to post this as another issue or if you need more data in order to help me, please let me know, thank you both for your help.

**Comment by kevin218** [comment]
It's probably ok to run Stages 1 and 2 as you did, but you'll want to place the nrs1 and nrs2 files into different folders and run them separately through Stage 3.

**Comment by taylorbell57** [comment]
An option is to put `nrs1_calints` for the `suffix` setting in your Stage 3 and make the `outputdir` to something like `Stage3_nrs1`, and then do another Stage 3 run for the NRS2 data after adjusting the `suffix` and `outputdir` settings.

**Comment by Paulinappl** [comment]
Hi Kevin and Taylor, I followed your advice and started running satge 3 first just in nrs2 data, (I'll try seperately with nrs1 later). As i said in a previous comment I was now getting this error: ValueError: operands could not be broadcast together with shapes (155,21,2048) (21,2047) (155,21,2048), so trying to fix this bug I added this line to stage 3 ecf file: gain            True, and stage 3 started finally running, until a few minutes ago that I got a new error, so here is my terminals log with this new error:

Could not import starry and/or pymc3 related packages. Functionality may be limited.

Starting Stage 3 Reduction

Input directory: /home/iaunam/1st_trial_eureka/Stage2nrs2/
Output directory: /home/iaunam/1st_trial_eureka/Stage3/S3_2024-08-14_WASP39b_byme_run10/ap6_bg7/
Using ap=6, bg=7, expand=1
Copying S3 control file

Found 3 data file(s) ending in calints.fits
Starting file 1 of 3
  Reading file 1...
  Masking NaNs/infs in data arrays...
  FLUX has 95635 NaNs/infs, which is 0.94% of all pixels.
  ERR has 95635 NaNs/infs, which is 0.94% of all pixels.
  V0 has 95635 NaNs/infs, which is 0.94% of all pixels.
  Locating source position...
    Source position on detector is row 10.
  Using provided gain=True to convert units to electrons...
  Converting from data numbers per second (DN/s) to electrons...
  Computing clean median frame...
WARNING: NIRSpec GRISM spectra is significantly curved and will very likely benefit from setting meta.curvature to "correct".
  Performing background outlier rejection...
  Performing CxC background subtraction...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 155/155 [00:46<00:00,  3.36it/s]
  Creating figures for background subtraction...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:04<00:00,  1.04it/s]
  Recording y position and width for all integrations...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 155/155 [00:01<00:00, 130.48it/s]
  Extracting aperture region...
2024-08-14 09:28:55,457 - stpipe - WARNING - /home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/optspex.py:52: RuntimeWarning: invalid value encountered in divide
  replacement_val = np.nansum(replacement_val)/denom

2024-08-14 09:28:55,458 - stpipe - WARNING - /home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/optspex.py:60: RuntimeWarning: invalid value encountered in divide
  replacement_val = np.nansum(replacement_val)/denom

  Performing optimal spectral extraction...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 155/155 [3:35:57<00:00, 83.60s/it]
  Creating figures for optimal spectral extraction
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:07<00:00,  1.46s/it]
Finished writing to /home/iaunam/1st_trial_eureka/Stage3/S3_2024-08-14_WASP39b_byme_run10/ap6_bg7/S3_WASP39b_byme_ap6_bg7_FluxData_seg0000.h5
Starting file 2 of 3
  Reading file 2...
  Masking NaNs/infs in data arrays...
  FLUX has 95635 NaNs/infs, which is 0.94% of all pixels.
  ERR has 95635 NaNs/infs, which is 0.94% of all pixels.
  V0 has 95635 NaNs/infs, which is 0.94% of all pixels.
  Locating source position...
    Source position on detector is row 10.
  Using provided gain=True to convert units to electrons...
  Converting from data numbers per second (DN/s) to electrons...
  Computing clean median frame...
WARNING: NIRSpec GRISM spectra is significantly curved and will very likely benefit from setting meta.curvature to "correct".
  Performing background outlier rejection...
  Performing CxC background subtraction...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 155/155 [00:49<00:00,  3.12it/s]
  Creating figures for background subtraction...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:06<00:00,  1.32s/it]
  Recording y position and width for all integrations...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 155/155 [00:01<00:00, 128.83it/s]
  Extracting aperture region...
2024-08-14 13:06:13,325 - stpipe - WARNING - /home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/optspex.py:52: RuntimeWarning: invalid value encountered in divide
  replacement_val = np.nansum(replacement_val)/denom

2024-08-14 13:06:13,325 - stpipe - WARNING - /home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/optspex.py:60: RuntimeWarning: invalid value encountered in divide
  replacement_val = np.nansum(replacement_val)/denom

  Performing optimal spectral extraction...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 155/155 [3:32:23<00:00, 82.21s/it]
  Creating figures for optimal spectral extraction
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:11<00:00,  2.35s/it]
Finished writing to /home/iaunam/1st_trial_eureka/Stage3/S3_2024-08-14_WASP39b_byme_run10/ap6_bg7/S3_WASP39b_byme_ap6_bg7_FluxData_seg0001.h5
Starting file 3 of 3
  Reading file 3...
  Masking NaNs/infs in data arrays...
  FLUX has 95644 NaNs/infs, which is 0.94% of all pixels.
  ERR has 95644 NaNs/infs, which is 0.94% of all pixels.
  V0 has 95644 NaNs/infs, which is 0.94% of all pixels.
  Locating source position...
    Source position on detector is row 10.
  Using provided gain=True to convert units to electrons...
  Converting from data numbers per second (DN/s) to electrons...
  Computing clean median frame...
WARNING: NIRSpec GRISM spectra is significantly curved and will very likely benefit from setting meta.curvature to "correct".
  Performing background outlier rejection...
  Performing CxC background subtraction...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 155/155 [00:53<00:00,  2.88it/s]
  Creating figures for background subtraction...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:06<00:00,  1.38s/it]
  Recording y position and width for all integrations...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 155/155 [00:01<00:00, 120.97it/s]
  Extracting aperture region...
2024-08-14 16:40:07,287 - stpipe - WARNING - /home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/optspex.py:52: RuntimeWarning: invalid value encountered in divide
  replacement_val = np.nansum(replacement_val)/denom

2024-08-14 16:40:07,287 - stpipe - WARNING - /home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/optspex.py:60: RuntimeWarning: invalid value encountered in divide
  replacement_val = np.nansum(replacement_val)/denom

  Performing optimal spectral extraction...
  3%|██▊                                                                                                         | 4/155 [5:50:50<186:22:03, 4443.20s/it]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 155/155 [12:47:32<00:00, 297.11s/it]
  Creating figures for optimal spectral extraction
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:11<00:00,  2.33s/it]
Finished writing to /home/iaunam/1st_trial_eureka/Stage3/S3_2024-08-14_WASP39b_byme_run10/ap6_bg7/S3_WASP39b_byme_ap6_bg7_FluxData_seg0002.h5
Finished writing to /home/iaunam/1st_trial_eureka/Stage3/S3_2024-08-14_WASP39b_byme_run10/ap6_bg7/S3_WASP39b_byme_ap6_bg7_SpecData.h5
Traceback (most recent call last):
  File "/home/iaunam/Escritorio/Verano_2024/ECF_files_byme/run_eureka_wasp39_2.py", line 30, in <module>
    spec, meta = s3.reduce(eventlabel, ecf_path=ecf_path)
  File "/home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/eureka/S3_data_reduction/s3_reduce.py", line 699, in reduce
    log.writelog(f"Stage 3 MAD = {int(np.round(meta.mad_s3))} ppm")
  File "/home/iaunam/anaconda3/envs/eureka/lib/python3.9/site-packages/numpy/ma/core.py", line 4451, in __int__
    raise MaskError('Cannot convert masked element to a Python int.')
numpy.ma.core.MaskError: Cannot convert masked element to a Python int.

I really hope that you can help me, and thank you both so much for all your help.

**Comment by Paulinappl** [comment]
Here is my stage 3 ecf file if it helps.

########  Stage 3 ecf file creado 

# Eureka! Control File for Stage 3: Data Reduction

# Stage 3 Documentation: https://eurekadocs.readthedocs.io/en/latest/ecf.html#stage-3

ncpu            1           # Number of CPUs a usar cuando se corre eureka!
## LOS TENIA EN 1 Y CAMBIE A 4 POR EL TEMPLATE pero de la main branch
## el de la v 0.10 lo tiene en 1 asi que lo volvi a cambiar
nfiles          1           # The number of data files to analyze simultaneously
max_memory      0.5         # (0–1), mejor <=.5 The maximum fraction of memory you want utilized by read-in frames (this will reduce nfiles if need be)
indep_batches   False       # Strongly recommended to leave this as False. Independently treat each batch of files? Strongly recommended to leave this as False unless you have a clear reason to set it to True.
suffix          calints     # Data file suffix

######## elegir true or false
calibrated_spectra  False   # Set True to generate flux-calibrated spectra/photometry in mJy
                            # Set False to convert to electrons

# Subarray region of interest
## elegir la sección que te interesa 
######## elegiiiiirrrr
#ywindow         [10,21]      # Vertical axis as seen in DS9      nrs1
#ywindow         [6,27]      # Vertical axis as seen in DS9     nrs2
ywindow         [0,32]      # Vertical axis as seen in DS9     nrs2
########################## aqui cambie a 25 por las nrs2

xwindow         [0,2048]    # Horizontal axis as seen in DS9    nrs2
#xwindow         [567,2048]    # Horizontal axis as seen in DS9    nrs1
#xwindow         [0,2048]    # Horizontal axis as seen in DS9    nrs2


### agregue por el error actual dif size arrays
gain            True


### asi estaba [60,410], lo cambie por lo que vi en el ds9
## Gaussian adecuado para fuentes puntuales (como el caso de wasp 39)
src_pos_type    gaussian    # Determine source position when not given in header (Options: header, gaussian, weighted, max, or hst)
######## yo elijo gaussian
record_ypos     True        # Option to record the y position and width for each integration (only records if src_pos_type is gaussian)
dqmask          True        # Mask pixels with an odd entry in the DQ array
######## vamos a ver como salen los resultados con 2
expand          1           # Ayuda a mejorar la resolución, p or ejemplo, un expand de 2 duplicaría la resolución en esa dirección. // Super-sampling factor along cross-dispersion direction
## LO TENIA EN 2 Y LO CAMBIE A 1 POR EL TEMPLATE

# Outlier rejection along time axis
####### la TD de WASP 39 en el ERS es de ~2% so false? Si dejarlo en false porque si es mas como deep transit
ff_outlier      False       # Set False to use only background region (recommended for deep transits)
                            # Set True to use full frame (works well for shallow transits/eclipses)
                            ## Be sure to check the percentage of pixels that were flagged while ff_outlier = True; the value should be << 1% when bg_thresh = [5,5].
bg_thresh       [4,4]       ## itera dos veces buscando outliers con desviaciones mayores a 4. // Double-iteration X-sigma threshold for outlier rejection along time axis

# Background parameters
##  yo creo que lo mas importante a determinar
bg_hw           7           # Half-width of exclusion region for BG subtraction (relative to source position)
###########  se determina con ds9 ???
bg_deg          0           # Polynomial order for column-by-column background subtraction, -1 for median of entire frame
########### determinar que metodo le va mejor a los datos 
bg_method       mean        ## metodo para calcular sigma Options: std (Standard Deviation), median (Median Absolute Deviation), mean (Mean Absolute Deviation)
########### determinar cual std es la mejor
p3thresh        10          # X-sigma threshold for outlier rejection during background subtraction

# Spectral extraction parameters
spec_hw         6           # Half-width of aperture region for spectral extraction (relative to source position)
fittype         smooth     ## Method for constructing spatial profile (Options: smooth, meddata, poly, gauss, wavelet, or wavelet2D)
### for jwst meddata or smooth is recommended
## lo cambie a smooth xq asi estaba la template de v0.10
median_thresh   5           ## Sigma threshold when flagging outliers in median frame, when fittype=meddata and window_len > 1
### puedo probar con 5 primero, el default
window_len      13          ## toma los valores alrededor del punto, 6 y 6, saca un promedio y sustituye el pixel central por ese valor, Smoothing window length, for median frame or when fittype = smooth or meddata (when computing median frame). Can set to 1 for no smoothing when computing median frame for fittype=meddata.
### puedo probar con esto y ver como funciona
prof_deg        3           # Polynomial degree, when fittype = poly
p5thresh        10          # # X-sigma threshold for outlier rejection while constructing spatial profile
p7thresh        60          # # X-sigma threshold for outlier rejection during optimal spectral extraction

# G395H curvature treatment
## para NIRSpec/G395 usar correrct en vez de None !!!!!
## es un efecto del instrumento cuando dispersa la luz
curvature       none        # How to manage the curved trace on the detector (Options: None, correct). Use correct for NIRSpec/G395.

# Diagnostics
isplots_S3      5           ## Generate few (1), some (3), or many (5) figures (Options: 1 - 5)
nplots          5           ## How many of each type of figure do you want to make per file?

## cual es la figura 3101??
vmin            0.97        # Sets the vmin of the color bar for Figure 3101.
vmax            1.03        # Sets the vmax of the color bar for Figure 3101.
time_axis       'y'         # Determines whether the time axis in Figure 3101 is along the y-axis ('y') or the x-axis ('x')

testing_S3      False       ## If set to True only the last segment (which is usually the smallest) in the inputdir will be run. Also, only five integrations from the last segment will be reduced. Boolean, set True to only use last file and generate select figures
hide_plots      False       # If True, plots will automatically be closed rather than popping up
save_output     True        # Save outputs for use in S4
verbose         True        # If True, more details will be printed about steps

# Project directory
topdir          /home/iaunam/1st_trial_eureka/

# Directories relative to topdir
inputdir        Stage2nrs2   # The folder containing the outputs from Eureka!'s S2 or JWST's S2 pipeline (will be overwritten if calling S2 and S3 sequentially)
outputdir       Stage3

**Comment by taylorbell57** [comment]
For NIRSpec G395H data, it is important that you set `curvature` to `correct` because the curvature of the spectral trace is quite strong and without correcting for the curvature the spectral trace will end up falling outside of your aperture.

**Comment by taylorbell57** [comment]
Since I think this issue was resolved in #685, I'm now closing this issue - feel free to reopen the issue if I am wrong about that
