### ISSUE TITLE
[Bug]: Eureka fails on new installation;  

### ISSUE THREAD

**Issue by iancrossfield** [kevin218/Eureka#706]
### FAQ check

- [X] Yes, I checked the FAQ and my question has not been addressed.

### Instrument

Other (any stage)

### What happened?

When following the installation instructions in a brand-new Conda environment:
> conda create -n eureka1 python==3.10.14
> conda activate eureka1
> git clone -b v1.0 https://github.com/kevin218/Eureka.git
> cd Eureka
> pip install -e '.[jwst]'
installation succeeds, but apparently other necessary dependencies don't get installed. So when trying to `run_eureka.py` I get:

> WARNING: The package jwst has not been installed.
> WARNING: Unable to load the jwst package.
> ModuleNotFoundError: No module named 'pandexo'

### Error traceback output

python run_eureka.py 
WARNING: The package jwst has not been installed. As a result, Eureka!'s Stages 1 and 2 will not work.
WARNING: Unable to load the jwst package. As a result, the MIRI wavelength solution will not be able to be calculated in Stage 3.
Traceback (most recent call last):
  File "/disk2/jwst/data/eureka_ltt9779/run_eureka.py", line 3, in <module>
    import eureka.S1_detector_processing.s1_process as s1
  File "/home/i620c788/Downloads/Eureka/src/eureka/S1_detector_processing/__init__.py", line 2, in <module>
    from . import bias_sub
  File "/home/i620c788/Downloads/Eureka/src/eureka/S1_detector_processing/bias_sub.py", line 7, in <module>
    from jwst.lib import reffile_utils
  File "/home/exolab/ianpython/jwst.py", line 6, in <module>
    import pandexo.engine.justdoit as jdi # THIS IS THE HOLY GRAIL OF PANDEXO
ModuleNotFoundError: No module named 'pandexo'

### What operating system are you using?

Ubuntu

### What version of Python are you running?

3.10.14

### What Python packages do you have installed?

```
# packages in environment at /home/exolab/anaconda3/envs/eureka1:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alabaster                 1.0.0                    pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
asdf                      3.5.0                    pypi_0    pypi
asdf-astropy              0.6.1                    pypi_0    pypi
asdf-coordinates-schemas  0.3.0                    pypi_0    pypi
asdf-standard             1.1.1                    pypi_0    pypi
asdf-transform-schemas    0.5.0                    pypi_0    pypi
asdf-wcs-schemas          0.4.0                    pypi_0    pypi
asteval                   1.0.5                    pypi_0    pypi
astraeus                  0.3                      pypi_0    pypi
astropy                   6.1.4                    pypi_0    pypi
astropy-healpix           1.0.3                    pypi_0    pypi
astropy-iers-data         0.2024.10.14.0.32.55          pypi_0    pypi
astroquery                0.4.7                    pypi_0    pypi
astroscrappy              1.2.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
babel                     2.16.0                   pypi_0    pypi
backports-tarfile         1.2.0                    pypi_0    pypi
batman-package            2.4.9                    pypi_0    pypi
bayesicfitting            3.2.1                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
bokeh                     2.4.3                    pypi_0    pypi
bottleneck                1.4.2                    pypi_0    pypi
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
ccdproc                   2.4.2                    pypi_0    pypi
celerite2                 0.3.2                    pypi_0    pypi
certifi                   2024.8.30                pypi_0    pypi
cffi                      1.17.1                   pypi_0    pypi
cftime                    1.6.4                    pypi_0    pypi
charset-normalizer        3.4.0                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.1.0                    pypi_0    pypi
contourpy                 1.3.0                    pypi_0    pypi
corner                    2.2.2                    pypi_0    pypi
crds                      11.18.4                  pypi_0    pypi
cryptography              43.0.3                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
dask                      2024.10.0                pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
dill                      0.3.9                    pypi_0    pypi
docutils                  0.21.2                   pypi_0    pypi
drizzle                   1.15.3                   pypi_0    pypi
dynesty                   2.1.4                    pypi_0    pypi
emcee                     3.1.6                    pypi_0    pypi
eureka                    1.0                      pypi_0    pypi
exceptiongroup            1.2.2                    pypi_0    pypi
executing                 2.1.0                    pypi_0    pypi
exotic-ld                 3.2.0                    pypi_0    pypi
fasteners                 0.19                     pypi_0    pypi
filelock                  3.16.1                   pypi_0    pypi
fleck                     1.1.2                    pypi_0    pypi
fonttools                 4.54.1                   pypi_0    pypi
fsspec                    2024.9.0                 pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
george                    0.4.3                    pypi_0    pypi
gwcs                      0.21.0                   pypi_0    pypi
h5netcdf                  1.4.0                    pypi_0    pypi
h5py                      3.12.1                   pypi_0    pypi
html5lib                  1.1                      pypi_0    pypi
idna                      3.10                     pypi_0    pypi
imageio                   2.36.0                   pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        8.5.0                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
ipython                   8.28.0                   pypi_0    pypi
jaraco-classes            3.4.0                    pypi_0    pypi
jaraco-context            6.0.1                    pypi_0    pypi
jaraco-functools          4.1.0                    pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jeepney                   0.8.0                    pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2024.10.1                pypi_0    pypi
jwst                      1.15.1                   pypi_0    pypi
keyring                   25.4.1                   pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
ld_impl_linux-64          2.43                 h712a8e2_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.46.1               hadc24fc_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
lmfit                     1.3.2                    pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
markupsafe                3.0.2                    pypi_0    pypi
matplotlib                3.9.2                    pypi_0    pypi
matplotlib-inline         0.1.7                    pypi_0    pypi
mc3                       3.2.0                    pypi_0    pypi
more-itertools            10.5.0                   pypi_0    pypi
ncurses                   6.5                  he02047a_1    conda-forge
netcdf4                   1.6.5                    pypi_0    pypi
networkx                  3.4.1                    pypi_0    pypi
numcodecs                 0.13.1                   pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
numpydoc                  1.8.0                    pypi_0    pypi
opencv-python-headless    4.10.0.84                pypi_0    pypi
openssl                   3.3.2                hb9d3cd8_0    conda-forge
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.3                    pypi_0    pypi
parsley                   1.3                      pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
partd                     1.4.2                    pypi_0    pypi
pexpect                   4.9.0                    pypi_0    pypi
photutils                 2.0.1                    pypi_0    pypi
pillow                    11.0.0                   pypi_0    pypi
pip                       24.2               pyh8b19718_1    conda-forge
pluggy                    1.5.0                    pypi_0    pypi
poppy                     1.1.1                    pypi_0    pypi
prompt-toolkit            3.0.48                   pypi_0    pypi
psutil                    6.1.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.3                    pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pyerfa                    2.0.1.4                  pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyparsing                 3.2.0                    pypi_0    pypi
pysynphot                 2.0.0                    pypi_0    pypi
pytest                    8.3.3                    pypi_0    pypi
python                    3.10.14         hd12c33a_0_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
pytz                      2024.2                   pypi_0    pypi
pyvo                      1.5.3                    pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
referencing               0.35.1                   pypi_0    pypi
reproject                 0.14.0                   pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
rpds-py                   0.20.0                   pypi_0    pypi
scikit-image              0.24.0                   pypi_0    pypi
scipy                     1.14.1                   pypi_0    pypi
secretstorage             3.3.3                    pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
setuptools                75.1.0             pyhd8ed1ab_0    conda-forge
setuptools-scm            8.1.0                    pypi_0    pypi
shapely                   2.0.6                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
soupsieve                 2.6                      pypi_0    pypi
spherical-geometry        1.3.2                    pypi_0    pypi
sphinx                    8.1.3                    pypi_0    pypi
sphinxcontrib-applehelp   2.0.0                    pypi_0    pypi
sphinxcontrib-devhelp     2.0.0                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.1.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      2.0.0                    pypi_0    pypi
sphinxcontrib-serializinghtml 2.0.0                    pypi_0    pypi
stack-data                0.6.3                    pypi_0    pypi
stcal                     1.7.3                    pypi_0    pypi
stdatamodels              2.0.0                    pypi_0    pypi
stpipe                    0.6.0                    pypi_0    pypi
stsci-image               2.3.9                    pypi_0    pypi
stsci-imagestats          1.8.3                    pypi_0    pypi
stsci-stimage             0.2.9                    pypi_0    pypi
svo-filters               0.4.4                    pypi_0    pypi
synphot                   1.4.0                    pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tifffile                  2024.9.20                pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomli                     2.0.2                    pypi_0    pypi
toolz                     1.0.0                    pypi_0    pypi
tornado                   6.4.1                    pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
traitlets                 5.14.3                   pypi_0    pypi
tweakwcs                  0.8.9                    pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.2                   pypi_0    pypi
uncertainties             3.2.2                    pypi_0    pypi
urllib3                   2.2.3                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
wiimatch                  0.3.2                    pypi_0    pypi
xarray                    2024.9.0                 pypi_0    pypi
xz                        5.2.6                h166bdaf_0    conda-forge
zarr                      2.18.3                   pypi_0    pypi
zipp                      3.20.2                   pypi_0    pypi

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iancrossfield** [comment]
Trying to install both Eureka and pandexo just brings me into deeper circles of Python dependency hell.  The main issues seem to be:
> pandexo-engine 1.9.0 requires bokeh==3.0.2, but you have bokeh U.V.W which is incompatible.
and/or
> eureka 1.0 requires bokeh<3.0, but you have bokeh X.Y.Z which is incompatible.
These seem to be mutually incompatible.

**Comment by kevin218** [comment]
You definitely want to keep your Eureka! and PandExo installs in separate conda environments. Also, PandExo isn't part of the requirements, so I don't know what voodoo magic has decided otherwise.

Unfortunately (for you, fortunate for me), I'm on vacation until Tuesday and won't be able to look into this until I get back.

**Comment by jbrande** [comment]
Ian and I talked about this offline, and it looks to be an unintentional clash between another script in the same directory as his run_eureka.py and the jwst pipeline. This isn't actually an issue on our end.

**Comment by iancrossfield** [comment]
Specifically, it was because Eureka depends on a module called 'jwst' and I already had a similar (self-written) file named "jwst.py" in my PYTHONPATH.
