### ISSUE TITLE
The file ./S4_nircam_wfss_template.ecf does not exist

### ISSUE THREAD

**Issue by mithun1996-png** [kevin218/Eureka#718]
### Instrument

Light curve fitting (Stages 4-6)

### What happened?

When I am going to run Stage 4 of Eureka Jwst pipe line then why this show .like file missing 

### Error traceback output

```
Traceback (most recent call last):
  File "/media/seps3/abb231cd-8a52-48df-a46a-5caa396b751c/data_anlysis_01/Eureka/demos/JWST/run_eureka.py", line 29, in <module>
    spec, lc, meta = s4.genlc(eventlabel, ecf_path=ecf_path)
  File "/media/seps3/abb231cd-8a52-48df-a46a-5caa396b751c/data_anlysis_01/Eureka/src/eureka/S4_generate_lightcurves/s4_genLC.py", line 84, in genlc
    meta = S4MetaClass(ecf_path, ecffile)
  File "/media/seps3/abb231cd-8a52-48df-a46a-5caa396b751c/data_anlysis_01/Eureka/src/eureka/S4_generate_lightcurves/s4_meta.py", line 45, in __init__
    super().__init__(folder, file, eventlabel, stage=4, **kwargs)
  File "/media/seps3/abb231cd-8a52-48df-a46a-5caa396b751c/data_anlysis_01/Eureka/src/eureka/lib/readECF.py", line 71, in __init__
    raise ValueError(f"The file {os.path.join(folder, file)} "
ValueError: The file ./S4_nircam_wfss_template.ecf does not exist.
```

### What operating system are you using?

linux

### What version of Python are you running?

Python 3.10.14

### What Python packages do you have installed?

```
# packages in environment at /home/seps3/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aext-assistant            4.0.15          py312h06a4308_jl4_0  
aext-assistant-server     4.0.15          py312h06a4308_0  
aext-core                 4.0.15          py312h06a4308_jl4_0  
aext-core-server          4.0.15          py312h06a4308_1  
aext-panels               4.0.15          py312h06a4308_0  
aext-panels-server        4.0.15          py312h06a4308_0  
aext-share-notebook       4.0.15          py312h06a4308_0  
aext-share-notebook-server 4.0.15          py312h06a4308_0  
aext-shared               4.0.15          py312h06a4308_0  
alabaster                 0.7.16          py312h06a4308_0  
anaconda-anon-usage       0.4.4           py312hfc0e8ea_100  
anaconda-cloud-auth       0.5.1           py312h06a4308_0  
anaconda-toolbox          4.0.15          py312h06a4308_0  
annotated-types           0.6.0           py312h06a4308_0  
anyio                     4.2.0           py312h06a4308_0  
archspec                  0.2.3              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0          py312h5eee18b_0  
arrow                     1.2.3           py312h06a4308_1  
asdf                      3.5.0                    pypi_0    pypi
asdf-astropy              0.6.1                    pypi_0    pypi
asdf-coordinates-schemas  0.3.0                    pypi_0    pypi
asdf-standard             1.1.1                    pypi_0    pypi
asdf-transform-schemas    0.5.0                    pypi_0    pypi
asdf-wcs-schemas          0.4.0                    pypi_0    pypi
astroid                   2.14.2          py312h06a4308_0  
astropy                   6.1.2                    pypi_0    pypi
astropy-iers-data         0.2024.10.28.0.34.7          pypi_0    pypi
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4           py312h06a4308_0  
atomicwrites              1.4.0                      py_0  
attrs                     23.1.0          py312h06a4308_0  
autopep8                  2.0.4              pyhd3eb1b0_0  
babel                     2.11.0          py312h06a4308_0  
bayesicfitting            3.2.1                    pypi_0    pypi
beautifulsoup4            4.12.3          py312h06a4308_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
black                     24.4.2          py312h06a4308_0  
blas                      1.0                    openblas  
bleach                    4.1.0              pyhd3eb1b0_0  
boltons                   23.0.0          py312h06a4308_0  
bottleneck                1.3.7           py312ha883a20_0  
brotli-python             1.0.9           py312h6a678d5_8  
bzip2                     1.0.8                h5eee18b_6  
c-ares                    1.19.1               h5eee18b_0  
ca-certificates           2024.7.4             hbcca054_0    conda-forge
certifi                   2024.8.30       py312h06a4308_0  
cffi                      1.16.0          py312h5eee18b_1  
chardet                   4.0.0           py312h06a4308_1003  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.7           py312h06a4308_0  
cloudpickle               3.0.0           py312h06a4308_0  
colorama                  0.4.6           py312h06a4308_0  
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
conda                     24.7.1          py312h06a4308_0  
conda-content-trust       0.2.0           py312h06a4308_1  
conda-libmamba-solver     24.1.0             pyhd3eb1b0_0  
conda-package-handling    2.2.0           py312h06a4308_1  
conda-package-streaming   0.9.0           py312h06a4308_0  
contourpy                 1.2.1                    pypi_0    pypi
cookiecutter              2.6.0           py312h06a4308_0  
crds                      12.0.4                   pypi_0    pypi
cryptography              42.0.5          py312hdda0065_1  
cycler                    0.12.1                   pypi_0    pypi
cyrus-sasl                2.1.28               h52b45da_1  
dbus                      1.13.18              hb2f20db_0  
debugpy                   1.6.7           py312h6a678d5_0  
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713           pyhd3eb1b0_0  
dill                      0.3.8           py312h06a4308_0  
distro                    1.9.0           py312h06a4308_0  
docstring-to-markdown     0.11            py312h06a4308_0  
docutils                  0.18.1          py312h06a4308_3  
drizzle                   2.0.0                    pypi_0    pypi
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                h6a678d5_0  
filelock                  3.16.1                   pypi_0    pypi
flake8                    7.0.0           py312h06a4308_0  
fmt                       9.1.0                hdb19cb5_1  
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonttools                 4.53.0                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
frozendict                2.4.2           py312h06a4308_0  
future                    1.0.0                    pypi_0    pypi
glib                      2.78.4               h6a678d5_0  
glib-tools                2.78.4               h6a678d5_0  
gst-plugins-base          1.14.1               h6a678d5_1  
gstreamer                 1.14.1               h5eee18b_1  
gwcs                      0.21.0                   pypi_0    pypi
h11                       0.14.0          py312h06a4308_0  
h5py                      3.11.0          py312h34c39bb_0  
hdf5                      1.12.1               h2b7332f_3  
httpcore                  1.0.2           py312h06a4308_0  
httpx                     0.26.0          py312h06a4308_0  
icu                       73.1                 h6a678d5_0  
idna                      3.7             py312h06a4308_0  
imageio                   2.36.0                   pypi_0    pypi
imagesize                 1.4.1           py312h06a4308_0  
importlib-metadata        8.2.0              pyha770c72_0    conda-forge
importlib_metadata        8.2.0                hd8ed1ab_0    conda-forge
inflection                0.5.1           py312h06a4308_1  
intervaltree              3.1.0              pyhd3eb1b0_0  
ipykernel                 6.29.5             pyh3099207_0    conda-forge
ipython                   8.26.0             pyh707e725_0    conda-forge
isort                     5.13.2          py312h06a4308_0  
jaraco.classes            3.2.1              pyhd3eb1b0_0  
jax                       0.4.23          py312h06a4308_0  
jaxlib                    0.4.23          py312h6a678d5_0  
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jeepney                   0.7.1              pyhd3eb1b0_0  
jellyfish                 1.0.1           py312hb02cf49_0  
jinja2                    3.1.4           py312h06a4308_0  
jmespath                  1.0.1                    pypi_0    pypi
jpeg                      9e                   h5eee18b_2  
json5                     0.9.6              pyhd3eb1b0_0  
jsonpatch                 1.33            py312h06a4308_1  
jsonpointer               2.1                pyhd3eb1b0_0  
jsonschema                4.19.2          py312h06a4308_0  
jsonschema-specifications 2023.7.1        py312h06a4308_0  
jupyter-lsp               2.2.0           py312h06a4308_0  
jupyter_client            8.6.2              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2           py312h06a4308_0  
jupyter_events            0.10.0          py312h06a4308_0  
jupyter_server            2.14.1          py312h06a4308_0  
jupyter_server_terminals  0.4.4           py312h06a4308_1  
jupyterlab                4.0.11          py312h06a4308_0  
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.25.1          py312h06a4308_0  
jwst                      1.16.0                   pypi_0    pypi
keyring                   24.3.1          py312h06a4308_0  
kiwisolver                1.4.5                    pypi_0    pypi
krb5                      1.20.1               h143b758_1  
lazy-loader               0.4                      pypi_0    pypi
lazy-object-proxy         1.10.0          py312h5eee18b_0  
ld_impl_linux-64          2.38                 h1181459_1  
libarchive                3.6.2                h6ac8c49_3  
libclang                  14.0.6          default_hc6dbbc7_1  
libclang13                14.0.6          default_he11475f_1  
libcups                   2.4.2                h2d74bed_1  
libcurl                   8.7.1                h251f7ec_0  
libedit                   3.1.20230828         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libevent                  2.1.12               hdbd6064_1  
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgfortran-ng            14.1.0               h69a702a_0    conda-forge
libgfortran5              14.1.0               hc5f4f2c_0    conda-forge
libglib                   2.78.4               hdc74915_0  
libgomp                   14.1.0               h77fa898_0    conda-forge
libiconv                  1.16                 h5eee18b_3  
libllvm14                 14.0.6               hdb19cb5_3  
libmamba                  1.5.8                hfe524e5_2  
libmambapy                1.5.8           py312h2dafd23_2  
libnghttp2                1.57.0               h2d74bed_0  
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.21               h043d6bf_0  
libpng                    1.6.39               h5eee18b_0  
libpq                     12.17                hdbd6064_0  
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsolv                   0.7.24               he621ea3_1  
libspatialindex           1.9.3                h2531618_0  
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libssh2                   1.11.0               h251f7ec_0  
libstdcxx-ng              14.1.0               hc0a3c3a_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcb                    1.15                 h7f8727e_0  
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxkbcommon              1.0.1                h5eee18b_1  
libxml2                   2.10.4               hfdd30dd_2  
libzlib                   1.2.13               h4ab18f5_6    conda-forge
llvmlite                  0.43.0                   pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_1  
markdown-it-py            2.2.0           py312h06a4308_1  
markupsafe                2.1.3           py312h5eee18b_0  
matplotlib                3.9.0                    pypi_0    pypi
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mccabe                    0.7.0              pyhd3eb1b0_0  
mdurl                     0.1.0           py312h06a4308_0  
menuinst                  2.0.2           py312h06a4308_1  
mistune                   2.0.4           py312h06a4308_0  
ml_dtypes                 0.4.0           py312h526ad5a_0  
more-itertools            10.1.0          py312h06a4308_0  
mpi                       1.0                       mpich  
mpi4py                    4.0.0           py312h5924d30_1    conda-forge
mpich                     4.2.2              h4a7f18d_101    conda-forge
mypy_extensions           1.0.0           py312h06a4308_0  
mysql                     5.7.24               h721c034_2  
nbclient                  0.8.0           py312h06a4308_0  
nbconvert                 7.10.0          py312h06a4308_0  
nbformat                  5.9.2           py312h06a4308_0  
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
networkx                  3.4.2                    pypi_0    pypi
notebook                  7.0.8           py312h06a4308_2  
notebook-shim             0.2.3           py312h06a4308_0  
nspr                      4.35                 h6a678d5_0  
nss                       3.89.1               h6a678d5_0  
numba                     0.60.0                   pypi_0    pypi
numexpr                   2.8.7           py312he7dcb8a_0  
numpy                     1.26.4          py312h2809609_0  
numpy-base                1.26.4          py312he1a6c75_0  
numpydoc                  1.7.0           py312h06a4308_0  
opencv-python-headless    4.10.0.84                pypi_0    pypi
openssl                   3.3.1                h4bc722e_2    conda-forge
opt_einsum                3.3.0              pyhd3eb1b0_1  
overrides                 7.4.0           py312h06a4308_0  
packaging                 23.2            py312h06a4308_0  
panadas                   0.2                      pypi_0    pypi
pandas                    2.2.2           py312h526ad5a_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
parsley                   1.3                      pypi_0    pypi
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
pathspec                  0.10.3          py312h06a4308_0  
pcre2                     10.42                hebb0a14_1  
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
photutils                 2.0.2                    pypi_0    pypi
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.3.0                   pypi_0    pypi
pip                       24.0            py312h06a4308_0  
pkce                      1.0.3           py312h06a4308_0  
platformdirs              3.10.0          py312h06a4308_0  
pluggy                    1.0.0           py312h06a4308_1  
ply                       3.11            py312h06a4308_1  
poppy                     1.1.1                    pypi_0    pypi
prometheus_client         0.14.1          py312h06a4308_0  
prompt-toolkit            3.0.47             pyha770c72_0    conda-forge
psutil                    5.9.0           py312h5eee18b_0  
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_0    conda-forge
pybind11-abi              5                    hd3eb1b0_0  
pycodestyle               2.11.1          py312h06a4308_0  
pycosat                   0.6.6           py312h5eee18b_1  
pycparser                 2.21               pyhd3eb1b0_0  
pydantic                  2.5.3           py312h06a4308_0  
pydantic-core             2.14.6          py312hb02cf49_0  
pydocstyle                6.3.0           py312h06a4308_0  
pyerfa                    2.0.1.4         py312ha883a20_0  
pyflakes                  3.2.0           py312h06a4308_0  
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.8.0           py312h06a4308_0  
pylint                    2.16.2          py312h06a4308_0  
pylint-venv               3.0.3           py312h06a4308_0  
pyls-spyder               0.4.0              pyhd3eb1b0_0  
pyparsing                 3.1.2                    pypi_0    pypi
pyqt                      5.15.10         py312h6a678d5_0  
pyqt5-sip                 12.13.0         py312h5eee18b_0  
pyqtwebengine             5.15.10         py312h6a678d5_0  
pysocks                   1.7.1           py312h06a4308_0  
python                    3.12.2          hab00c5b_0_cpython    conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python-dotenv             0.21.0          py312h06a4308_0  
python-fastjsonschema     2.16.2          py312h06a4308_0  
python-json-logger        2.0.7           py312h06a4308_0  
python-lsp-black          2.0.0           py312h06a4308_0  
python-lsp-jsonrpc        1.1.2              pyhd3eb1b0_0  
python-lsp-server         1.10.0          py312h06a4308_0  
python-slugify            5.0.2              pyhd3eb1b0_0  
python-tzdata             2023.3             pyhd3eb1b0_0  
python_abi                3.12                    4_cp312    conda-forge
pytoolconfig              1.2.6           py312h06a4308_0  
pytz                      2024.1          py312h06a4308_0  
pyxdg                     0.27               pyhd3eb1b0_0  
pyyaml                    6.0.1           py312h5eee18b_0  
pyzmq                     25.1.2          py312h6a678d5_0  
qdarkstyle                3.2.3              pyhd3eb1b0_0  
qstylizer                 0.2.2           py312h06a4308_0  
qt-main                   5.15.2              h53bd1ea_10  
qt-webengine              5.15.9               h9ab4d14_7  
qtawesome                 1.2.2           py312h06a4308_0  
qtconsole                 5.5.1           py312h06a4308_0  
qtpy                      2.4.1           py312h06a4308_0  
readline                  8.2                  h5eee18b_0  
referencing               0.30.2          py312h06a4308_0  
reproc                    14.2.4               h6a678d5_2  
reproc-cpp                14.2.4               h6a678d5_2  
requests                  2.31.0          py312h06a4308_1  
rfc3339-validator         0.1.4           py312h06a4308_0  
rfc3986-validator         0.1.1           py312h06a4308_0  
rich                      13.7.1          py312h06a4308_0  
rope                      1.12.0          py312h06a4308_0  
rpds-py                   0.10.6          py312hb02cf49_0  
rtree                     1.0.1           py312h06a4308_0  
ruamel.yaml               0.17.21         py312h5eee18b_0  
scikit-image              0.24.0                   pypi_0    pypi
scipy                     1.13.1          py312h2809609_0  
secretstorage             3.3.1           py312h06a4308_1  
semantic-version          2.10.0                   pypi_0    pypi
semver                    3.0.2           py312h06a4308_0  
send2trash                1.8.2           py312h06a4308_0  
setuptools                74.1.2                   pypi_0    pypi
sip                       6.7.12          py312h6a678d5_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.3.0           py312h06a4308_0  
snowballstemmer           2.2.0              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.5             py312h06a4308_0  
spherical-geometry        1.3.2                    pypi_0    pypi
sphinx                    7.3.7           py312h5eee18b_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.10          py312h06a4308_0  
spyder                    5.5.1           py312h06a4308_3  
spyder-kernels            2.5.0           py312h06a4308_0  
sqlite                    3.45.3               h5eee18b_0  
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
stcal                     1.9.0                    pypi_0    pypi
stdatamodels              2.1.1                    pypi_0    pypi
stpipe                    0.7.0                    pypi_0    pypi
stsci-imagestats          1.8.3                    pypi_0    pypi
stsci-stimage             0.2.9                    pypi_0    pypi
synphot                   1.4.0                    pypi_0    pypi
tabulate                  0.9.0           py312h06a4308_0  
terminado                 0.17.1          py312h06a4308_0  
text-unidecode            1.3                pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tifffile                  2024.9.20                pypi_0    pypi
tinycss2                  1.2.1           py312h06a4308_0  
tk                        8.6.14               h39e8969_0  
tomli                     2.0.1           py312h06a4308_1  
tomlkit                   0.11.1          py312h06a4308_0  
tornado                   6.4.1           py312h5eee18b_0  
tqdm                      4.66.2          py312he106c6f_0  
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
truststore                0.8.0           py312h06a4308_0  
tweakwcs                  0.8.9                    pypi_0    pypi
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024a                h04d1e81_0  
ujson                     5.10.0          py312h6a678d5_0  
unidecode                 1.2.0              pyhd3eb1b0_0  
urllib3                   2.1.0           py312h06a4308_1  
watchdog                  4.0.1           py312h06a4308_0  
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
webencodings              0.5.1           py312h06a4308_2  
websocket-client          1.8.0           py312h06a4308_0  
whatthepatch              1.0.2           py312h06a4308_0  
wheel                     0.43.0          py312h06a4308_0  
wiimatch                  0.3.2                    pypi_0    pypi
wrapt                     1.14.1          py312h5eee18b_0  
wurlitzer                 3.0.2           py312h06a4308_0  
xz                        5.4.6                h5eee18b_1  
yaml                      0.2.5                h7b6447c_0  
yaml-cpp                  0.8.0                h6a678d5_1  
yapf                      0.40.2          py312h06a4308_0  
zeromq                    4.3.5                h6a678d5_0  
zipp                      3.19.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstandard                 0.22.0          py312h2c38b39_0  
zstd                      1.5.5                hc292b87_2 
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorbell57** [comment]
Hi, the answer to your question is in your post itself - `The file ./S4_nircam_wfss_template.ecf does not exist.` This is telling you that your `run_eureka.py` file is trying to access a Stage 4 Eureka! Control File in the current directory called `./S4_nircam_wfss_template.ecf` which evidently doesn't exist. This is happening for one of two reasons - either you don't have a Stage 4 ECF in the folder that you ran this command from, or you created an ECF file with a different file name (and as a result you need to update the `eventlabel` setting inside of your `run_eureka.py` file.

Please carefully read through our quickstart tutorial (available [here](https://eurekadocs.readthedocs.io/en/latest/quickstart.html)) which describes how to use the pipeline and should help set you up for success. Additionally, it seems that you have not installed Eureka! properly (your list of installed packages doesn't even show that Eureka! is installed at all). Please read and carefully follow our installation instructions which are available [here](https://eurekadocs.readthedocs.io/en/latest/installation.html).

**Comment by mithun1996-png** [comment]
thank you  , its working also i  know my mistake which i done during the process
